/**
 * `_category_.json` — how Docusaurus's autogenerated sidebar labels and orders a folder.
 *
 * Written for every generated folder rather than left to Docusaurus's defaults, because without
 * one a folder takes its label from the directory name (`api-reference`, not "API Reference") and
 * sorts alphabetically instead of in contract order.
 */

/** What a category links to when its label is clicked. */
export interface CategoryLink {
    type: 'generated-index';
    title?: string;
}

export interface Category {
    label: string;
    /** Sort key among its siblings. Unset leaves the item unpositioned, which sorts it last. */
    position?: number;
    /**
     * Landing page for the category. Pass `'generated-index'` for a generated one, or leave it
     * out to let Docusaurus apply its own convention.
     */
    link?: CategoryLink;
}

/**
 * Serialize a category with the repo's four-space JSON style and a trailing newline, matching
 * how the Mintlify target writes `docs.json`.
 */
export function renderCategory(category: Category): string {
    const doc: Record<string, unknown> = { label: category.label };
    if (category.position !== undefined) doc.position = category.position;
    if (category.link !== undefined) doc.link = category.link;
    return `${JSON.stringify(doc, null, 4)}\n`;
}

/**
 * A generated index for a folder of pages.
 *
 * Every generated category gets one, and the reason is not cosmetic: without an explicit `link`,
 * Docusaurus promotes any doc named `index`, `readme`, or the same as its folder into the
 * category's landing page and drops it from the sidebar. A model called `Models`, or an endpoint
 * whose slug matches its area, would silently disappear.
 */
export function generatedIndex(title: string): CategoryLink {
    return { type: 'generated-index', title };
}
