// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// Operations declared in `billing.ck`.
public final class BillingClient: Sendable {
    private let http: SdkHttp

    public init(http: SdkHttp) {
        self.http = http
    }

    /// create a payment
    /// - Throws: `SdkError` on 400
    public func createPayment(body: PaymentInput) async throws -> CreatePaymentResult {
        var request = SdkRequest(method: "POST", path: ["payments"])
        try http.setJSONBody(&request, body, contentType: "application/json")
        let response = try await http.execute(request)
        let headers = try CreatePaymentHeaders(
            xRequestId: http.requireHeader(response, "x-request-id", as: String.self),
            xRatelimitRemaining: http.requireHeader(response, "x-ratelimit-remaining", as: Int.self),
            xCacheHit: http.optionalHeader(response, "x-cache-hit", as: Bool.self),
            xExpiresAfter: http.optionalHeader(response, "x-expires-after", as: Date.self)
        )
        return CreatePaymentResult(data: try http.decodeJSON(Payment.self, from: response), headers: headers)
    }

    /// list payments
    public func listPayments(query: ListPaymentsQuery, customHeaders: ListPaymentsHeaders) async throws -> [Payment] {
        var request = SdkRequest(method: "GET", path: ["payments"])
        try http.addQuery(&request, query)
        try http.addHeaders(&request, customHeaders)
        let response = try await http.execute(request)
        return try http.decodeJSON([Payment].self, from: response)
    }

    /// create several payments at once
    public func createPayments(body: [PaymentInput]) async throws -> [Payment] {
        var request = SdkRequest(method: "POST", path: ["payments", "batch"])
        try http.setJSONBody(&request, body, contentType: "application/json")
        let response = try await http.execute(request)
        return try http.decodeJSON([Payment].self, from: response)
    }

    /// fetch one payment
    /// - Throws: `SdkError` on 404
    public func getPayment(paymentId: UUID) async throws -> Payment {
        let request = try SdkRequest(method: "GET", path: ["payments", http.segment(paymentId)])
        let response = try await http.execute(request)
        return try http.decodeJSON(Payment.self, from: response)
    }

    /// update a payment with form data
    public func updatePaymentWithForm(paymentId: UUID, body: UpdatePaymentForm) async throws {
        var request = try SdkRequest(method: "POST", path: ["payments", http.segment(paymentId)])
        try http.setFormBody(&request, body, contentType: "application/x-www-form-urlencoded")
        _ = try await http.execute(request)
    }

    /// delete a payment — declares only a documented error status
    /// - Throws: `SdkError` on 400
    public func deletePayment(paymentId: UUID) async throws {
        let request = try SdkRequest(method: "DELETE", path: ["payments", http.segment(paymentId)])
        _ = try await http.execute(request)
    }

    /// upload a receipt image
    public func uploadReceipt(paymentId: UUID, body: [MultipartPart]) async throws -> Payment {
        var request = try SdkRequest(method: "POST", path: ["payments", http.segment(paymentId), "receipt"])
        http.setMultipartBody(&request, body)
        let response = try await http.execute(request)
        return try http.decodeJSON(Payment.self, from: response)
    }

    /// look up a refund by its originating payment
    /// - Throws: `SdkError` on 404
    @available(*, deprecated, message: "Deprecated in the contract")
    public func getRefund(params: PaymentRef) async throws -> Payment {
        let request = try SdkRequest(method: "GET", path: ["refunds", http.segment(params.paymentId)])
        let response = try await http.execute(request)
        return try http.decodeJSON(Payment.self, from: response)
    }

    /// store a credential
    public func createCredential(body: AdminCredentialInput) async throws -> Credential {
        var request = SdkRequest(method: "POST", path: ["credentials"])
        try http.setJSONBody(&request, body, contentType: "application/json")
        let response = try await http.execute(request)
        return try http.decodeJSON(Credential.self, from: response)
    }

    /// open a session
    public func createSession(body: SessionInput) async throws -> Session {
        var request = SdkRequest(method: "POST", path: ["sessions"])
        try http.setJSONBody(&request, body, contentType: "application/json")
        let response = try await http.execute(request)
        return try http.decodeJSON(Session.self, from: response)
    }
}

/// Response headers declared on POST /payments.
public struct CreatePaymentHeaders: Equatable, Sendable {
    public let xRequestId: String
    public let xRatelimitRemaining: Int
    public let xCacheHit: Bool?
    public let xExpiresAfter: Date?

    public init(xRequestId: String, xRatelimitRemaining: Int, xCacheHit: Bool?, xExpiresAfter: Date?) {
        self.xRequestId = xRequestId
        self.xRatelimitRemaining = xRatelimitRemaining
        self.xCacheHit = xCacheHit
        self.xExpiresAfter = xExpiresAfter
    }
}

/// The body of POST /payments, with the response headers the contract declares.
public struct CreatePaymentResult: Equatable, Sendable {
    public let data: Payment
    public let headers: CreatePaymentHeaders

    public init(data: Payment, headers: CreatePaymentHeaders) {
        self.data = data
        self.headers = headers
    }
}

/// Query parameters for GET /payments.
public struct ListPaymentsQuery: Encodable, Equatable, Sendable {
    public var limit: Int?
    public var cursor: String
    public var status: JSONValue?

    public init(limit: Int? = nil, cursor: String, status: JSONValue? = nil) {
        self.limit = limit
        self.cursor = cursor
        self.status = status
    }

    private enum CodingKeys: String, CodingKey {
        case limit = "limit"
        case cursor = "cursor"
        case status = "status"
    }
}

/// Request headers for GET /payments.
public struct ListPaymentsHeaders: Encodable, Equatable, Sendable {
    public var apiKey: String?
    public var xTenant: String

    public init(apiKey: String? = nil, xTenant: String) {
        self.apiKey = apiKey
        self.xTenant = xTenant
    }

    private enum CodingKeys: String, CodingKey {
        case apiKey = "api-key"
        case xTenant = "x-tenant"
    }
}
