// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// Operations declared in `hyphenated.ck`.
public final class HyphenatedClient: Sendable {
    private let http: SdkHttp

    public init(http: SdkHttp) {
        self.http = http
    }

    /// fetch an invoice
    /// - Throws: `SdkError` on 404
    public func getInvoice(invoiceId: UUID) async throws -> Invoice {
        let request = try SdkRequest(method: "GET", path: ["invoices", http.segment(invoiceId)])
        let response = try await http.execute(request)
        return try http.decodeJSON(Invoice.self, from: response)
    }
}
