// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// Operations declared in `kitchen.ck`.
public final class KitchenClient: Sendable {
    private let http: SdkHttp

    public init(http: SdkHttp) {
        self.http = http
    }

    /// several statuses, and two content types on one of them
    public func getFolder(folderId: UUID, query: GetFolderQuery? = nil, customHeaders: GetFolderHeaders) async throws -> GetFolderResponse {
        var request = try SdkRequest(method: "GET", path: ["folders", http.segment(folderId)])
        try http.addQuery(&request, query)
        try http.addHeaders(&request, customHeaders)
        let response = try await http.execute(request, expectStatuses: [404])
        switch response.status {
        case 204:
            return .status204
        case 404:
            return .status404(try http.decodeJSON(Shared.self, from: response))
        default:
            let headers = try GetFolder200Headers(
                xCount: http.requireHeader(response, "x-count", as: Int.self),
                xWhen: http.optionalHeader(response, "x-when", as: Date.self)
            )
            switch response.contentType {
            case "text/plain":
                return .status200TextPlain(data: response.text, headers: headers)
            default:
                return .status200ApplicationJson(data: try http.decodeJSON(Folder.self, from: response), headers: headers)
            }
        }
    }

    /// a method name that is a keyword in the target languages
    public func `import`(folderId: UUID, body: SharedInput) async throws -> Instrument {
        var request = try SdkRequest(method: "PUT", path: ["folders", http.segment(folderId)])
        try http.setJSONBody(&request, body, contentType: "application/json")
        let response = try await http.execute(request)
        return try http.decodeJSON(Instrument.self, from: response)
    }

    public func stamp(body: Stamped) async throws -> Stamped {
        var request = SdkRequest(method: "POST", path: ["stamps"])
        try http.setJSONBody(&request, body, contentType: "application/json")
        let response = try await http.execute(request)
        return try http.decodeJSON(Stamped.self, from: response)
    }

    /// - Throws: `SdkError` on 400
    public func mint(body: Token) async throws -> Token {
        var request = SdkRequest(method: "POST", path: ["tokens"])
        try http.setJSONBody(&request, body, contentType: "application/json")
        let response = try await http.execute(request)
        return try http.decodeJSON(Token.self, from: response)
    }

    public func listTokens() async throws -> [Token] {
        let request = SdkRequest(method: "GET", path: ["tokens"])
        let response = try await http.execute(request)
        return try http.decodeJSON([Token].self, from: response)
    }
}

/// Query parameters for GET /folders/{folder-id}.
public struct GetFolderQuery: Encodable, Equatable, Sendable {
    public var depth: Int?
    public var tags: [String]?

    public init(depth: Int? = nil, tags: [String]? = nil) {
        self.depth = depth
        self.tags = tags
    }

    private enum CodingKeys: String, CodingKey {
        case depth = "depth"
        case tags = "tags"
    }
}

/// Request headers for GET /folders/{folder-id}.
public struct GetFolderHeaders: Encodable, Equatable, Sendable {
    public var xTrace: String
    public var xOpt: Int?

    public init(xTrace: String, xOpt: Int? = nil) {
        self.xTrace = xTrace
        self.xOpt = xOpt
    }

    private enum CodingKeys: String, CodingKey {
        case xTrace = "x-trace"
        case xOpt = "x-opt"
    }
}

/// Response headers declared on GET /folders/{folder-id}.
public struct GetFolder200Headers: Equatable, Sendable {
    public let xCount: Int
    public let xWhen: Date?

    public init(xCount: Int, xWhen: Date?) {
        self.xCount = xCount
        self.xWhen = xWhen
    }
}

/// What GET /folders/{folder-id} returned.
///
/// The operation declares several statuses the service produces, so the status is part of the value.
public enum GetFolderResponse: Equatable, Sendable {
    case status200ApplicationJson(data: Folder, headers: GetFolder200Headers)
    case status200TextPlain(data: String, headers: GetFolder200Headers)
    case status204
    case status404(Shared)
}
