// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// Operations declared in `reserved.ck`.
public final class ReservedClient: Sendable {
    private let http: SdkHttp

    public init(http: SdkHttp) {
        self.http = http
    }

    /// fetch one seat
    public func getSeat(`class`: String, query: GetSeatQuery? = nil, customHeaders: GetSeatHeaders? = nil) async throws -> GetSeatResult {
        var request = try SdkRequest(method: "GET", path: ["seats", http.segment(`class`)])
        try http.addQuery(&request, query)
        try http.addHeaders(&request, customHeaders)
        let response = try await http.execute(request)
        let headers = try GetSeatResponseHeaders(
            from: http.optionalHeader(response, "from", as: String.self)
        )
        return GetSeatResult(data: try http.decodeJSON(Seat.self, from: response), headers: headers)
    }

    /// fetch a row by its seat class
    public func getRow(params: SeatRef) async throws -> Seat {
        let request = try SdkRequest(method: "GET", path: ["rows", http.segment(params.`class`)])
        let response = try await http.execute(request)
        return try http.decodeJSON(Seat.self, from: response)
    }
}

/// Query parameters for GET /seats/{class}.
public struct GetSeatQuery: Encodable, Equatable, Sendable {
    public var from: LocalDate?
    public var `in`: String?
    public var pageSize: Int?

    public init(from: LocalDate? = nil, `in`: String? = nil, pageSize: Int? = nil) {
        self.from = from
        self.`in` = `in`
        self.pageSize = pageSize
    }

    private enum CodingKeys: String, CodingKey {
        case from = "from"
        case `in` = "in"
        case pageSize = "pageSize"
    }
}

/// Request headers for GET /seats/{class}.
public struct GetSeatHeaders: Encodable, Equatable, Sendable {
    public var from: String?

    public init(from: String? = nil) {
        self.from = from
    }

    private enum CodingKeys: String, CodingKey {
        case from = "from"
    }
}

/// Response headers declared on GET /seats/{class}.
public struct GetSeatResponseHeaders: Equatable, Sendable {
    public let from: String?

    public init(from: String?) {
        self.from = from
    }
}

/// The body of GET /seats/{class}, with the response headers the contract declares.
public struct GetSeatResult: Equatable, Sendable {
    public let data: Seat
    public let headers: GetSeatResponseHeaders

    public init(data: Seat, headers: GetSeatResponseHeaders) {
        self.data = data
        self.headers = headers
    }
}
