// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// Operations declared in `simple.ck`.
public final class SimpleClient: Sendable {
    private let http: SdkHttp

    public init(http: SdkHttp) {
        self.http = http
    }

    /// current service status
    public func getStatus() async throws -> Heartbeat {
        let request = SdkRequest(method: "GET", path: ["status"])
        let response = try await http.execute(request)
        return try http.decodeJSON(Heartbeat.self, from: response)
    }
}
