# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.
from ._base_client import BaseClient, SdkError
from ._client_billing import BillingClient
from ._client_hyphenated import HyphenatedClient
from ._client_simple import SimpleClient


class Sdk(BaseClient):
    def __init__(self, base_url: str, headers: dict[str, str] | None = None):
        super().__init__(base_url, headers)
        self.billing = BillingClient(base_url, headers)
        self.hyphenated = HyphenatedClient(base_url, headers)
        self.simple = SimpleClient(base_url, headers)

__all__ = ["BaseClient", "SdkError", "Sdk", "BillingClient", "HyphenatedClient", "SimpleClient"]
