# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.
from __future__ import annotations

from urllib.parse import quote
from typing import NotRequired, TypedDict
from ._base_client import BaseClient, SdkError  # noqa: F401
from ._models_reserved import Seat, SeatRef


class GetSeatHeaders(TypedDict, total=False):
    from_: str  # from (optional)


GetSeatQuery = TypedDict("GetSeatQuery", {
    "from": NotRequired[str],
    "pageSize": NotRequired[int],
})


class ReservedClient(BaseClient):

    async def get_seat(self, seat_id: str, query: GetSeatQuery | None = None) -> tuple[Seat, GetSeatHeaders]:
        """
        fetch one seat
        """
        result, _response_headers = await self._fetch_with_headers(f"/seats/{quote(str(seat_id), safe='')}", method="GET", params=query)
        headers: GetSeatHeaders = {}
        if "from" in _response_headers:
            headers["from_"] = _response_headers["from"]
        return Seat.model_validate(result), headers

    async def get_row(self, params: SeatRef) -> Seat:
        """
        fetch a row by its seat class
        """
        result = await self._fetch(f"/rows/{quote(str(params.model_dump(by_alias=True)['class']), safe='')}", method="GET")
        return Seat.model_validate(result)
