# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.
from __future__ import annotations

from datetime import date
from urllib.parse import quote
from typing import NotRequired, TypedDict
from ._base_client import BaseClient, SdkError  # noqa: F401
from ._models_reserved import Seat, SeatRef


class GetSeatResponseHeaders(TypedDict, total=False):
    from_: str  # from (optional)


class GetSeatQuery(TypedDict):
    from_: NotRequired[date]  # from
    in_: NotRequired[str]  # in
    page_size: NotRequired[int]  # pageSize


class GetSeatHeaders(TypedDict):
    from_: NotRequired[str]  # from


class ReservedClient(BaseClient):

    async def get_seat(self, class_: str, query: GetSeatQuery | None = None, custom_headers: GetSeatHeaders | None = None) -> tuple[Seat, GetSeatResponseHeaders]:
        """
        fetch one seat
        """
        result, _response_headers = await self._fetch_with_headers(f"/seats/{quote(str(class_), safe='')}", method="GET", params=query, extra_headers=custom_headers)
        headers: GetSeatResponseHeaders = {}
        if "from" in _response_headers:
            headers["from_"] = _response_headers["from"]
        return Seat.model_validate(result), headers

    async def get_row(self, params: SeatRef) -> Seat:
        """
        fetch a row by its seat class
        """
        result = await self._fetch(f"/rows/{quote(str(params.class_), safe='')}", method="GET")
        return Seat.model_validate(result)
