# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.
from __future__ import annotations

from uuid import UUID
from urllib.parse import quote
from ._base_client import BaseClient, SdkError  # noqa: F401
from ._models_hyphenated import Invoice, InvoiceInput


class HyphenatedClient(BaseClient):

    async def get_invoice(self, invoice_id: UUID) -> Invoice:
        """
        fetch an invoice
        """
        result = await self._fetch(f"/invoices/{quote(str(invoice_id), safe='')}", method="GET")
        return Invoice.model_validate(result)
