# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.
from __future__ import annotations

from ._base_client import BaseClient, SdkError  # noqa: F401
from ._models_simple import Heartbeat


class SimpleClient(BaseClient):

    async def get_status(self) -> Heartbeat:
        """
        current service status
        """
        result = await self._fetch("/status", method="GET")
        return Heartbeat.model_validate(result)
