# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.
from __future__ import annotations

from datetime import datetime
from uuid import UUID
from urllib.parse import quote
from typing import Any, Literal, NotRequired, TypedDict
from pydantic import TypeAdapter
from ._base_client import BaseClient, SdkError  # noqa: F401
from ._models_billing import AdminCredentialInput, Credential, CredentialInput, Payment, PaymentFilter, PaymentInput, PaymentRef, SavedSearch, ScopedFilter, Session, SessionInput, SnakeFilter, SnakeHeaders, TenantHeaders, UpdatePaymentForm, UploadReceiptForm


class CreatePaymentHeaders(TypedDict, total=False):
    x_request_id: str  # x-request-id (required)
    x_ratelimit_remaining: int  # x-ratelimit-remaining (required)
    x_cache_hit: bool  # x-cache-hit (optional)
    x_expires_after: datetime  # x-expires-after (optional)


ListPaymentsQuery = TypedDict("ListPaymentsQuery", {
    "limit": NotRequired[int],
    "cursor": str,
    "status": NotRequired[Literal["pending", "completed", "failed"]],
})


ListPaymentsHeaders = TypedDict("ListPaymentsHeaders", {
    "api-key": NotRequired[str],
    "x-tenant": str,
})


_LIST_PAYMENTS_RESPONSE: TypeAdapter[list[Payment]] = TypeAdapter(list[Payment])
_SEARCH_PAYMENTS_RESPONSE: TypeAdapter[list[Payment]] = TypeAdapter(list[Payment])
_CREATE_PAYMENTS_BODY: TypeAdapter[list[PaymentInput]] = TypeAdapter(list[PaymentInput])
_CREATE_PAYMENTS_RESPONSE: TypeAdapter[list[Payment]] = TypeAdapter(list[Payment])
_SEARCH_PAYMENTS_SCOPED_RESPONSE: TypeAdapter[dict[str, Any]] = TypeAdapter(dict[str, Any])
_SAVE_SCOPED_SEARCH_BODY: TypeAdapter[dict[str, Any]] = TypeAdapter(dict[str, Any])


class BillingClient(BaseClient):

    async def create_payment(self, body: PaymentInput) -> tuple[Payment, CreatePaymentHeaders]:
        """
        create a payment
        """
        result, _response_headers = await self._fetch_with_headers("/payments", method="POST", body=body.model_dump(mode="json", by_alias=True, exclude_unset=True))
        headers: CreatePaymentHeaders = {}
        if "x-request-id" in _response_headers:
            headers["x_request_id"] = _response_headers["x-request-id"]
        if "x-ratelimit-remaining" in _response_headers:
            headers["x_ratelimit_remaining"] = int(_response_headers["x-ratelimit-remaining"])
        if "x-cache-hit" in _response_headers:
            headers["x_cache_hit"] = _response_headers["x-cache-hit"] == "true"
        if "x-expires-after" in _response_headers:
            headers["x_expires_after"] = datetime.fromisoformat(_response_headers["x-expires-after"])
        return Payment.model_validate(result), headers

    async def list_payments(self, query: ListPaymentsQuery, custom_headers: ListPaymentsHeaders) -> list[Payment]:
        """
        list payments
        """
        result = await self._fetch("/payments", method="GET", params=query, extra_headers=custom_headers)
        return _LIST_PAYMENTS_RESPONSE.validate_python(result)

    async def search_payments(self, query: PaymentFilter | None = None, custom_headers: TenantHeaders | None = None) -> list[Payment]:
        """
        search payments with a filter model
        """
        result = await self._fetch("/payments/search", method="GET", params=query, extra_headers=custom_headers)
        return _SEARCH_PAYMENTS_RESPONSE.validate_python(result)

    async def create_payments(self, body: list[PaymentInput]) -> list[Payment]:
        """
        create several payments at once
        """
        result = await self._fetch("/payments/batch", method="POST", body=_CREATE_PAYMENTS_BODY.dump_python(body, mode="json", by_alias=True, exclude_unset=True))
        return _CREATE_PAYMENTS_RESPONSE.validate_python(result)

    async def get_payment(self, payment_id: UUID) -> Payment:
        """
        fetch one payment
        """
        result = await self._fetch(f"/payments/{quote(str(payment_id), safe='')}", method="GET")
        return Payment.model_validate(result)

    async def update_payment_with_form(self, payment_id: UUID, body: UpdatePaymentForm) -> None:
        """
        update a payment with form data
        """
        result = await self._fetch(f"/payments/{quote(str(payment_id), safe='')}", method="POST", body=body.model_dump(mode="json", by_alias=True, exclude_unset=True), content_type="application/x-www-form-urlencoded", body_kind="form")
        return None

    async def delete_payment(self, payment_id: UUID) -> None:
        """
        delete a payment — declares only a documented error status
        """
        result = await self._fetch(f"/payments/{quote(str(payment_id), safe='')}", method="DELETE")
        return None

    async def upload_receipt(self, payment_id: UUID, body: dict[str, Any]) -> Payment:
        """
        upload a receipt image
        """
        result = await self._fetch(f"/payments/{quote(str(payment_id), safe='')}/receipt", method="POST", body=body, content_type="multipart/form-data", body_kind="multipart")
        return Payment.model_validate(result)

    # @deprecated
    async def get_refund(self, params: PaymentRef) -> Payment:
        """
        look up a refund by its originating payment
        """
        result = await self._fetch(f"/refunds/{quote(str(params.model_dump(by_alias=True)['paymentId']), safe='')}", method="GET")
        return Payment.model_validate(result)

    async def create_credential(self, body: AdminCredentialInput) -> Credential:
        """
        store a credential
        """
        result = await self._fetch("/credentials", method="POST", body=body.model_dump(mode="json", by_alias=True, exclude_unset=True))
        return Credential.model_validate(result)

    async def create_session(self, body: SessionInput) -> Session:
        """
        open a session
        """
        result = await self._fetch("/sessions", method="POST", body=body.model_dump(mode="json", by_alias=True, exclude_unset=True))
        return Session.model_validate(result)

    async def search_payments_by_date(self, query: SnakeFilter | None = None, custom_headers: SnakeHeaders | None = None) -> None:
        """
        search payments with snake_case filter and header models
        """
        result = await self._fetch("/payments/by-date", method="GET", params=query, extra_headers=custom_headers)
        return None

    async def search_payments_scoped(self, query: dict[str, Any] | None = None, custom_headers: dict[str, Any] | None = None) -> dict[str, Any]:
        """
        search payments with a snake_case filter extended inline
        """
        result = await self._fetch("/payments/by-date/scoped", method="GET", params=query, extra_headers=custom_headers)
        return _SEARCH_PAYMENTS_SCOPED_RESPONSE.validate_python(result)

    async def save_scoped_search(self, body: dict[str, Any], query: ScopedFilter | None = None) -> SavedSearch:
        """
        save a scoped search
        """
        result = await self._fetch("/payments/by-date/scoped", method="POST", body=_SAVE_SCOPED_SEARCH_BODY.dump_python(body, mode="json", by_alias=True, exclude_unset=True), params=query)
        return SavedSearch.model_validate(result)
