# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.
from __future__ import annotations

from datetime import date
from urllib.parse import quote
from typing import NotRequired, TypedDict
from ._base_client import BaseClient, SdkError  # noqa: F401
from ._models_reserved import Note, Seat, SeatRef


class GetSeatResponseHeaders(TypedDict, total=False):
    from_: str  # from (optional)


GetSeatQuery = TypedDict("GetSeatQuery", {
    "from": NotRequired[date],
    "in": NotRequired[str],
    "pageSize": NotRequired[int],
})


GetSeatHeaders = TypedDict("GetSeatHeaders", {
    "from": NotRequired[str],
})


class ReservedClient(BaseClient):

    async def get_seat(self, class_: str, query: GetSeatQuery | None = None, custom_headers: GetSeatHeaders | None = None) -> tuple[Seat, GetSeatResponseHeaders]:
        """
        fetch one seat
        """
        result, _response_headers = await self._fetch_with_headers(f"/seats/{quote(str(class_), safe='')}", method="GET", params=query, extra_headers=custom_headers)
        headers: GetSeatResponseHeaders = {}
        if "from" in _response_headers:
            headers["from_"] = _response_headers["from"]
        return Seat.model_validate(result), headers

    async def get_row(self, params: SeatRef) -> Seat:
        """
        fetch a row by its seat class
        """
        result = await self._fetch(f"/rows/{quote(str(params.model_dump(by_alias=True)['class']), safe='')}", method="GET")
        return Seat.model_validate(result)

    async def put_note(self, body_: str, body: Note) -> Note:
        """
        replace a note
        """
        result = await self._fetch(f"/notes/{quote(str(body_), safe='')}", method="PUT", body=body.model_dump(mode="json", by_alias=True, exclude_unset=True))
        return Note.model_validate(result)
