# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.
from __future__ import annotations

from datetime import datetime
from uuid import UUID
from urllib.parse import quote
from typing import Literal, NotRequired, TypedDict
from ._base_client import BaseClient, SdkError  # noqa: F401
from ._models_kitchen import Folder, Instrument, Ledger, LedgerInput, Shared, SharedInput, Stamped, Token


class GetFolder200Headers(TypedDict, total=False):
    x_count: int  # x-count (required)
    x_when: datetime  # x-when (optional)


class GetFolderQuery(TypedDict):
    depth: NotRequired[int]  # depth
    tags: NotRequired[list[str]]  # tags


class GetFolderHeaders(TypedDict):
    x_trace: str  # x-trace
    x_opt: NotRequired[int]  # x-opt


class GetFolder200Response(TypedDict):
    status: Literal[200]
    content_type: Literal["application/json", "text/plain"]
    data: Folder | str
    headers: GetFolder200Headers


class GetFolder204Response(TypedDict):
    status: Literal[204]


class GetFolder404Response(TypedDict):
    status: Literal[404]
    content_type: Literal["application/json"]
    data: Shared


class KitchenClient(BaseClient):

    async def get_folder(self, folder_id: UUID, query: GetFolderQuery, custom_headers: GetFolderHeaders) -> GetFolder200Response | GetFolder204Response | GetFolder404Response:
        """
        several statuses, and two content types on one of them
        """
        _status, _content_type, result, _response_headers = await self._fetch_full(f"/folders/{quote(str(folder_id), safe='')}", method="GET", response_kind="auto", expect_statuses=(404,), params=query, extra_headers=custom_headers)
        if _status == 204:
            return { "status": 204 }
        if _status == 404:
            return { "status": 404, "content_type": "application/json", "data": Shared.model_validate(result) }
        headers_200: GetFolder200Headers = {}
        if "x-count" in _response_headers:
            headers_200["x_count"] = int(_response_headers["x-count"])
        if "x-when" in _response_headers:
            headers_200["x_when"] = datetime.fromisoformat(_response_headers["x-when"])
        if _content_type == "text/plain":
            return { "status": 200, "content_type": "text/plain", "data": result, "headers": headers_200 }
        return { "status": 200, "content_type": "application/json", "data": Folder.model_validate(result), "headers": headers_200 }

    async def import_(self, folder_id: UUID, body: SharedInput) -> Instrument:
        """
        a method name that is a keyword in the target languages
        """
        result = await self._fetch(f"/folders/{quote(str(folder_id), safe='')}", method="PUT", body=body.model_dump(mode="json"))
        return Instrument.model_validate(result)

    async def post_ledger(self, body: LedgerInput) -> Ledger:
        result = await self._fetch("/ledgers", method="POST", body=body.model_dump(mode="json"))
        return Ledger.model_validate(result)

    async def stamp(self, body: Stamped) -> Stamped:
        result = await self._fetch("/stamps", method="POST", body=body.model_dump(mode="json"))
        return Stamped.model_validate(result)

    async def mint(self, body: Token) -> Token:
        result = await self._fetch("/tokens", method="POST", body=body.model_dump(mode="json"))
        return Token.model_validate(result)

    async def list_tokens(self) -> list[Token]:
        result = await self._fetch("/tokens", method="GET")
        return [Token.model_validate(item) for item in result]
