# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.
from __future__ import annotations

from uuid import UUID
from urllib.parse import quote
from typing import NotRequired, TypedDict
from ._base_client import BaseClient, SdkError  # noqa: F401
from ._models_billing import AdminCredentialInput, Credential, CredentialInput, Payment, PaymentInput, PaymentRef, Session, SessionInput, UpdatePaymentForm, UploadReceiptForm


class CreatePaymentHeaders(TypedDict, total=False):
    x_request_id: str  # x-request-id (required)
    x_ratelimit_remaining: int  # x-ratelimit-remaining (required)
    x_cache_hit: bool  # x-cache-hit (optional)


class ListPaymentsQuery(TypedDict):
    limit: NotRequired[int]  # limit
    cursor: str  # cursor


class ListPaymentsHeaders(TypedDict):
    api_key: NotRequired[str]  # api-key
    x_tenant: str  # x-tenant


class BillingClient(BaseClient):

    async def create_payment(self, body: PaymentInput) -> tuple[Payment, CreatePaymentHeaders]:
        """
        create a payment
        """
        result, _response_headers = await self._fetch_with_headers("/payments", method="POST", body=body.model_dump(mode="json"))
        headers: CreatePaymentHeaders = {}
        if "x-request-id" in _response_headers:
            headers["x_request_id"] = _response_headers["x-request-id"]
        if "x-ratelimit-remaining" in _response_headers:
            headers["x_ratelimit_remaining"] = int(_response_headers["x-ratelimit-remaining"])
        if "x-cache-hit" in _response_headers:
            headers["x_cache_hit"] = _response_headers["x-cache-hit"] == "true"
        return Payment.model_validate(result), headers

    async def list_payments(self, query: ListPaymentsQuery, custom_headers: ListPaymentsHeaders) -> list[Payment]:
        """
        list payments
        """
        result = await self._fetch("/payments", method="GET", params=query, extra_headers=custom_headers)
        return [Payment.model_validate(item) for item in result]

    async def get_payment(self, payment_id: UUID) -> Payment:
        """
        fetch one payment
        """
        result = await self._fetch(f"/payments/{quote(str(payment_id), safe='')}", method="GET")
        return Payment.model_validate(result)

    async def update_payment_with_form(self, payment_id: UUID, body: UpdatePaymentForm) -> None:
        """
        update a payment with form data
        """
        result = await self._fetch(f"/payments/{quote(str(payment_id), safe='')}", method="POST", body=body.model_dump(mode="json"), content_type="application/x-www-form-urlencoded", body_kind="form")
        return None

    async def delete_payment(self, payment_id: UUID) -> None:
        """
        delete a payment — declares only a documented error status
        """
        result = await self._fetch(f"/payments/{quote(str(payment_id), safe='')}", method="DELETE")
        return None

    async def upload_receipt(self, payment_id: UUID, body: dict) -> Payment:
        """
        upload a receipt image
        """
        result = await self._fetch(f"/payments/{quote(str(payment_id), safe='')}/receipt", method="POST", body=body, content_type="multipart/form-data", body_kind="multipart")
        return Payment.model_validate(result)

    # @deprecated
    async def get_refund(self, params: PaymentRef) -> Payment:
        """
        look up a refund by its originating payment
        """
        result = await self._fetch(f"/refunds/{quote(str(params.payment_id), safe='')}", method="GET")
        return Payment.model_validate(result)

    async def create_credential(self, body: AdminCredentialInput) -> Credential:
        """
        store a credential
        """
        result = await self._fetch("/credentials", method="POST", body=body.model_dump(mode="json"))
        return Credential.model_validate(result)

    async def create_session(self, body: SessionInput) -> Session:
        """
        open a session
        """
        result = await self._fetch("/sessions", method="POST", body=body.model_dump(mode="json"))
        return Session.model_validate(result)
