# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.
from __future__ import annotations

from uuid import UUID
from pydantic import BaseModel
from decimal import Decimal

class Invoice(BaseModel):
    id: UUID
    total: Decimal

class InvoiceInput(BaseModel):
    total: Decimal
