# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.
from __future__ import annotations

from datetime import date
from pydantic import BaseModel, ConfigDict, Field

# A seat, whose field names are all reserved somewhere
class Seat(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    class_: str = Field(alias="class")
    from_: date | None = Field(alias="from")
    in_: str | None = Field(alias="in")
    is_: bool | None = Field(alias="is")
    object: str | None = None
    default: str | None = None

# Path params declared as a model whose field is a keyword, referenced via `params: SeatRef`
class SeatRef(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    class_: str = Field(alias="class")
