# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.
from __future__ import annotations

from datetime import date, datetime, time, timedelta
from uuid import UUID
from typing import Annotated, Any, Literal
from pydantic import BaseModel, ConfigDict, Field
from decimal import Decimal

# A named enum, so a field default has to resolve to a member rather than its wire spelling
Rating = Literal["good", "neutral", "bad"]

class Card(BaseModel):
    kind: "card"
    last4: str

class Bank(BaseModel):
    kind: "bank"
    iban: str

# Decodes snake_case keys and encodes PascalCase ones
class Token(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    access_token: str = Field(alias="accessToken")
    expires_in: int | None = Field(alias="expiresIn", default=3600)

class Owned(BaseModel):
    id: UUID

class OwnedInput(BaseModel):
    secret: str

class Named(BaseModel):
    name: str

class Stamp(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    stamped_by: str = Field(alias="stampedBy")
    stamped_at: datetime = Field(alias="stampedAt")

Instrument = Annotated[Card | Bank, Field(discriminator="kind")]

# A plain base under format(), which the schema inlines rather than extends
class Stamped(Stamp):
    model_config = ConfigDict(populate_by_name=True)

    stamp_note: str | None = Field(alias="stampNote")

# Two flattened bases, split into a read and an input shape
class Shared(Owned, Named):
    label: str | None = Field(default="x")
    instrument: Instrument | None = None

class SharedInput(OwnedInput, Named):
    label: str | None = Field(default="x")
    instrument: Instrument | None = None

# Self recursion through lazy(), mutual recursion through Doc, every container, both union
# forms, every scalar, and field names that are keywords in the target languages
class Folder(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: UUID
    class_: str = Field(alias="class")
    default: str | None = None
    rating: Rating | None = Field(default="neutral")
    parent: Folder | None = None
    readme: Doc | None = None
    children: list[Folder]
    by_name: dict[str, Folder] | None = Field(alias="byName")
    span: tuple[int, int] | None = None
    stamped: tuple[UUID, datetime, bool] | None = None
    label: str | int
    pinned: Doc | Folder | None
    instrument: Card | Bank | None = None
    origin: dict[str, Any] | None = None
    size: int
    price: Decimal
    day: date | None = None
    at: time | None = None
    ttl: timedelta | None = None
    blob: bytes | None = None
    extra: Any | None = None
    raw: Any | None = None

class Doc(BaseModel):
    id: UUID
    folder: Folder | None = None
