# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.
from __future__ import annotations

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field

# A service heartbeat — deliberately no bigint field and no `area` key
class Heartbeat(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    status: str
    checked_at: datetime = Field(alias="checkedAt")
