# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.
from __future__ import annotations

from datetime import date, datetime, timedelta
from uuid import UUID
from typing import Literal
from pydantic import BaseModel, ConfigDict, Field
from decimal import Decimal
from ._scalars import BigInt

# A customer payment
class Payment(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: UUID
    amount: float
    unit_price: Decimal = Field(alias="unitPrice")
    quantity: BigInt
    created_at: datetime = Field(alias="createdAt")
    processing_time: timedelta | None = Field(alias="processingTime", default=None)
    status: Literal["pending", "completed", "failed"] | None = Field(default="pending")

class PaymentInput(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    amount: float
    unit_price: Decimal = Field(alias="unitPrice")
    quantity: BigInt
    created_at: datetime = Field(alias="createdAt")
    processing_time: timedelta | None = Field(alias="processingTime", default=None)
    status: Literal["pending", "completed", "failed"] | None = Field(default="pending")

# A stored credential — has a writeonly child, so its Base schema is read
class Credential(BaseModel):
    id: UUID

class CredentialInput(BaseModel):
    secret: str

# A writeonly model nothing extends — its Base schema has no reader
class Session(BaseModel):
    id: str

class SessionInput(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    refresh_token: str = Field(alias="refreshToken")

# Path params declared as a model, referenced via `params: PaymentRef`
class PaymentRef(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    payment_id: UUID = Field(alias="paymentId")

class UpdatePaymentForm(BaseModel):
    note: str | None = None

class UploadReceiptForm(BaseModel):
    caption: str | None = None
    file: bytes | None = None

# Query params declared as a model, referenced via `query: PaymentFilter`
class PaymentFilter(BaseModel):
    status: Literal["pending", "completed", "failed"] | None = None
    since: datetime | None = None
    ids: list[UUID] | None = None

# Request headers declared as a model. Header names are case-insensitive, so any casing of `xCorrelationId` matches.
class TenantHeaders(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    x_tenant: str = Field(alias="x-tenant")
    x_correlation_id: str | None = Field(alias="xCorrelationId", default=None)

# Query params and headers declared as format() models. Each schema is a pipe with no `.strict()` of
# its own, so the router applies the block's object mode to the object inside it.
class SnakeFilter(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    from_date: date | None = Field(alias="fromDate", default=None)

class SnakeHeaders(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    tenant_id: str | None = Field(alias="tenantId", default=None)

# Extends a writeonly base and is itself writeonly
class AdminCredential(Credential):
    scope: str

class AdminCredentialInput(CredentialInput):
    scope: str
    token: str
