# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.
from __future__ import annotations

from uuid import UUID
from pydantic import BaseModel
from ._scalars import ExactDecimal

class Invoice(BaseModel):
    id: UUID
    total: ExactDecimal

class InvoiceInput(BaseModel):
    total: ExactDecimal
