// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using Example.Sdk.Clients;
using Example.Sdk.Runtime;

namespace Example.Sdk;

/// <summary>
/// Entry point to the generated SDK.
///
/// Holds one SdkHttp, shared by every client, so the SDK keeps a single connection pool.
/// Disposing it disposes the underlying HttpClient, unless you supplied your own.
/// </summary>
public sealed class KitchenSink : IDisposable
{
    public KitchenSink(SdkOptions options)
    {
        Http = new SdkHttp(options);
        Billing = new BillingClient(Http);
        Hyphenated = new HyphenatedClient(Http);
        Reserved = new ReservedClient(Http);
        Simple = new SimpleClient(Http);
    }

    public SdkHttp Http { get; }

    public BillingClient Billing { get; }

    public HyphenatedClient Hyphenated { get; }

    public ReservedClient Reserved { get; }

    public SimpleClient Simple { get; }

    public void Dispose()
    {
        Http.Dispose();
    }
}
