// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// Entry point to the generated SDK.
///
/// Holds one `SdkHttp`, shared by every client, so the SDK keeps a single configuration and transport.
public final class KitchenSink: Sendable {
    public let http: SdkHttp
    public let billing: BillingClient
    public let hyphenated: HyphenatedClient
    public let simple: SimpleClient

    public init(config: SdkConfig) {
        let http = SdkHttp(config: config)
        self.http = http
        self.billing = BillingClient(http: http)
        self.hyphenated = HyphenatedClient(http: http)
        self.simple = SimpleClient(http: http)
    }

    /// The SDK against `baseURL`, with `headers` added to every request.
    public convenience init(baseURL: URL, headers: @escaping @Sendable () async throws -> [String: String] = { [:] }) {
        self.init(config: SdkConfig(baseURL: baseURL, headers: headers))
    }
}
