import { describe, expect, it } from 'vitest';
import { buildModelIndex } from '@contractkit/core';
import { generateKotlinModels, resolveModelsWithInput } from '../src/codegen-models.js';
import { collectHoistedTypes } from '../src/hoist.js';
import {
    arrayType,
    contractRoot,
    enumType,
    field,
    inlineObjectType,
    literalType,
    model,
    recordType,
    refType,
    scalarType,
    tupleType,
    unionType,
} from './helpers.js';

const PKG = 'com.example.sdk';

/**
 * Run the same two passes the plugin runs: name the anonymous types, then render the file.
 * Tests that skip hoisting would assert a fallback nothing in the real pipeline produces.
 */
function gen(models: Parameters<typeof contractRoot>[0], opts: Partial<Parameters<typeof generateKotlinModels>[1]> = {}): string {
    const root = contractRoot(models);
    const modelIndex = buildModelIndex(models);
    const modelsWithInput = resolveModelsWithInput(models, opts.modelsWithInput);
    const hoisted = collectHoistedTypes([root], { modelIndex, modelsWithInput, warn: opts.warn ? m => opts.warn!(m) : undefined });
    return generateKotlinModels(root, { packageName: PKG, modelIndex, hoisted, ...opts });
}

// ─── Scalars ───────────────────────────────────────────────────────────────

describe('scalar mapping', () => {
    const cases: [Parameters<typeof scalarType>[0], string][] = [
        ['string', 'String'],
        ['email', 'String'],
        ['url', 'String'],
        ['interval', 'String'],
        ['number', 'Double'],
        ['int', 'Long'],
        ['bigint', 'BigInt'],
        ['decimal', 'Decimal'],
        ['boolean', 'Boolean'],
        ['date', 'LocalDate'],
        ['time', 'LocalTime'],
        ['datetime', 'Instant'],
        ['duration', 'Duration'],
        ['uuid', 'Uuid'],
        ['binary', 'ByteArray'],
        ['unknown', 'JsonElement'],
        ['json', 'JsonElement'],
        ['object', 'JsonElement'],
    ];

    for (const [scalar, kotlin] of cases) {
        it(`maps ${scalar} to ${kotlin}`, () => {
            const out = gen([model('M', [field('v', scalarType(scalar))])]);
            expect(out).toContain(`val v: ${kotlin},`);
        });
    }

    it('maps null to the type of the null literal', () => {
        const out = gen([model('M', [field('v', scalarType('null'))])]);
        expect(out).toContain('val v: Nothing?,');
    });

    it('throws on an unmapped scalar rather than emitting Kotlin that will not compile', () => {
        expect(() => gen([model('M', [field('v', { kind: 'scalar', name: 'quaternion' } as never)])])).toThrow(/unmapped scalar 'quaternion'/);
    });
});

// ─── Imports and file header ───────────────────────────────────────────────

describe('file header', () => {
    it('declares the models package and the generated-file banner', () => {
        const out = gen([model('M', [field('v', scalarType('string'))])]);
        expect(out).toContain('// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.');
        expect(out).toContain('package com.example.sdk.models');
    });

    it('adds the Uuid opt-in above the package declaration, and only when Uuid is used', () => {
        const withUuid = gen([model('M', [field('id', scalarType('uuid'))])]);
        expect(withUuid).toContain('@file:OptIn(ExperimentalUuidApi::class)');
        expect(withUuid).toContain('import kotlin.uuid.ExperimentalUuidApi');
        expect(withUuid.indexOf('@file:OptIn')).toBeLessThan(withUuid.indexOf('package '));

        const withoutUuid = gen([model('M', [field('v', scalarType('string'))])]);
        expect(withoutUuid).not.toContain('@file:OptIn');
    });

    it('imports the runtime value classes only for the scalars that need them', () => {
        const out = gen([model('M', [field('a', scalarType('decimal')), field('b', scalarType('bigint'))])]);
        expect(out).toContain('import com.example.sdk.runtime.Decimal');
        expect(out).toContain('import com.example.sdk.runtime.BigInt');

        const plain = gen([model('M', [field('v', scalarType('string'))])]);
        expect(plain).not.toContain('com.example.sdk.runtime');
    });

    it('sorts imports so output is stable across runs', () => {
        const out = gen([model('M', [field('a', scalarType('uuid')), field('b', scalarType('datetime')), field('c', scalarType('date'))])]);
        const imports = out.split('\n').filter(l => l.startsWith('import '));
        expect(imports).toEqual([...imports].sort());
    });
});

// ─── Composite types ───────────────────────────────────────────────────────

describe('composite types', () => {
    it('maps array and record', () => {
        const out = gen([
            model('M', [field('items', arrayType(refType('Payment'))), field('meta', recordType(scalarType('string'), scalarType('string')))]),
            model('Payment', [field('id', scalarType('string'))]),
        ]);
        expect(out).toContain('val items: List<Payment>,');
        expect(out).toContain('val meta: Map<String, String>,');
    });

    it('warns and falls back to a string key for a non-string record key', () => {
        const warnings: string[] = [];
        gen([model('M', [field('meta', recordType(scalarType('int'), scalarType('string')))])], { packageName: PKG, warn: m => warnings.push(m) });
        expect(warnings.join('\n')).toMatch(/record key of type 'Long'/);
    });

    it('maps a 2- and 3-tuple onto Pair and Triple with the array serializer', () => {
        const out = gen([
            model('M', [
                field('range', tupleType(scalarType('int'), scalarType('int'))),
                field('point', tupleType(scalarType('number'), scalarType('number'), scalarType('number'))),
            ]),
        ]);
        expect(out).toContain('@Serializable(with = PairAsArraySerializer::class) val range: Pair<Long, Long>,');
        expect(out).toContain('@Serializable(with = TripleAsArraySerializer::class) val point: Triple<Double, Double, Double>,');
        expect(out).toContain('import com.example.sdk.runtime.PairAsArraySerializer');
    });

    it('renders a model ref by name, since every model shares one package', () => {
        const out = gen([model('M', [field('p', refType('Payment'))]), model('Payment', [field('id', scalarType('string'))])]);
        expect(out).toContain('val p: Payment,');
    });
});

// ─── Fields ────────────────────────────────────────────────────────────────

describe('fields', () => {
    it('makes an optional field nullable with a null default', () => {
        const out = gen([model('M', [field('bio', scalarType('string'), { optional: true })])]);
        expect(out).toContain('val bio: String? = null,');
    });

    it('makes a required nullable field nullable with no initializer, so the caller must pass it', () => {
        const out = gen([model('M', [field('note', scalarType('string'), { nullable: true })])]);
        expect(out).toContain('val note: String?,');
    });

    it('renders defaults in the field type', () => {
        const out = gen([
            model('M', [
                field('limit', scalarType('int'), { default: 20 }),
                field('ratio', scalarType('number'), { default: 1 }),
                field('label', scalarType('string'), { default: 'hi' }),
                field('on', scalarType('boolean'), { default: true }),
            ]),
        ]);
        expect(out).toContain('val limit: Long? = 20L,');
        expect(out).toContain('val ratio: Double? = 1.0,');
        expect(out).toContain('val label: String? = "hi",');
        expect(out).toContain('val on: Boolean? = true,');
    });

    it('escapes a dollar sign in a string default, which would otherwise start a template', () => {
        const out = gen([model('M', [field('label', scalarType('string'), { default: 'cost: $5' })])]);
        expect(out).toContain('"cost: \\$5"');
    });

    it('adds @SerialName only when the Kotlin name differs from the wire name', () => {
        const out = gen([model('M', [field('x-request-id', scalarType('string')), field('amount', scalarType('number'))])]);
        expect(out).toContain('@SerialName("x-request-id") val xRequestId: String,');
        expect(out).toContain('val amount: Double,');
        expect(out).not.toContain('@SerialName("amount")');
    });

    it('gives a literal field its value as a default so callers never restate it', () => {
        const out = gen([model('M', [field('kind', literalType('card'))])]);
        expect(out).toContain('val kind: String = "card",');
    });

    it('documents a field description and deprecation in KDoc', () => {
        const out = gen([model('M', [field('amount', scalarType('number'), { description: 'In cents.', deprecated: true })])]);
        expect(out).toContain('     * In cents.');
        expect(out).toContain('     * @deprecated');
    });
});

// ─── Classes, enums, aliases ───────────────────────────────────────────────

describe('declarations', () => {
    it('emits a serializable data class', () => {
        const out = gen([model('Payment', [field('id', scalarType('uuid'))], { description: 'A payment' })]);
        expect(out).toContain('/** A payment */');
        expect(out).toContain('@Serializable');
        expect(out).toContain('data class Payment(');
    });

    it('emits a plain class for a contract with no fields, since a data class needs one', () => {
        const out = gen([model('Empty', [])]);
        expect(out).toContain('@Serializable\nclass Empty');
        expect(out).not.toContain('data class Empty');
    });

    it('emits an enum class with a SerialName per value', () => {
        const out = gen([model('Status', [], { type: enumType('pending', 'in-progress') })]);
        expect(out).toContain('enum class Status {');
        expect(out).toContain('    @SerialName("pending")');
        expect(out).toContain('    PENDING,');
        expect(out).toContain('    @SerialName("in-progress")');
        expect(out).toContain('    IN_PROGRESS,');
    });

    it('emits a typealias for a scalar alias', () => {
        const out = gen([model('UserId', [], { type: scalarType('uuid') })]);
        expect(out).toContain('typealias UserId = Uuid');
    });

    it('emits a data class for an intersection alias rather than an opaque JSON object', () => {
        const out = gen([
            model('A', [field('a', scalarType('string'))]),
            model('B', [field('b', scalarType('int'))]),
            model('AB', [], { type: { kind: 'intersection', members: [refType('A'), refType('B')] } }),
        ]);
        expect(out).toContain('data class AB(');
        const section = out.slice(out.indexOf('data class AB('));
        expect(section).toContain('val a: String,');
        expect(section).toContain('val b: Long,');
    });
});

// ─── Inheritance ───────────────────────────────────────────────────────────

describe('inheritance', () => {
    it('flattens a single base into the subclass, since a data class cannot extend one', () => {
        const out = gen([
            model('BaseEntity', [field('id', scalarType('uuid'))]),
            model('Payment', [field('amount', scalarType('number'))], { bases: ['BaseEntity'] }),
        ]);
        const section = out.slice(out.indexOf('data class Payment('));
        expect(section).toContain('val id: Uuid,');
        expect(section).toContain('val amount: Double,');
        // No Kotlin inheritance: the base is copied in, not extended.
        expect(out).not.toContain(': BaseEntity');
    });

    it('flattens multiple bases in declaration order with the subclass last', () => {
        const out = gen([
            model('A', [field('a', scalarType('string'))]),
            model('B', [field('b', scalarType('int'))]),
            model('C', [field('c', scalarType('boolean'))], { bases: ['A', 'B'] }),
        ]);
        const section = out.slice(out.indexOf('data class C('));
        const order = ['val a:', 'val b:', 'val c:'].map(s => section.indexOf(s));
        expect(order).toEqual([...order].sort((x, y) => x - y));
        expect(order.every(i => i > -1)).toBe(true);
    });

    it('warns when a base is not defined anywhere in the project', () => {
        const warnings: string[] = [];
        const models = [model('Payment', [field('amount', scalarType('number'))], { bases: ['Missing'] })];
        generateKotlinModels(contractRoot(models), { packageName: PKG, modelIndex: buildModelIndex(models), warn: m => warnings.push(m) });
        expect(warnings.join('\n')).toMatch(/extends 'Missing', which is not defined/);
    });
});

// ─── Read / Input split ────────────────────────────────────────────────────

describe('read and input variants', () => {
    it('omits readonly fields from the Input class', () => {
        const out = gen([model('Payment', [field('id', scalarType('uuid'), { visibility: 'readonly' }), field('amount', scalarType('number'))])]);
        expect(out).toContain('data class Payment(');
        expect(out).toContain('data class PaymentInput(');
        const input = out.slice(out.indexOf('data class PaymentInput('));
        expect(input).not.toContain('val id:');
        expect(input).toContain('val amount: Double,');
    });

    it('omits writeonly fields from the Read class', () => {
        const out = gen([
            model('Session', [field('id', scalarType('string')), field('refreshToken', scalarType('string'), { visibility: 'writeonly' })]),
        ]);
        const read = out.slice(out.indexOf('data class Session('), out.indexOf('data class SessionInput('));
        expect(read).not.toContain('refreshToken');
        expect(out.slice(out.indexOf('data class SessionInput('))).toContain('val refreshToken: String,');
    });

    it('points an Input class at the Input variant of a referenced model', () => {
        const models = [
            model('Credential', [field('secret', scalarType('string'), { visibility: 'writeonly' })]),
            model('Wrapper', [field('credential', refType('Credential'))]),
        ];
        const out = generateKotlinModels(contractRoot(models), { packageName: PKG, modelIndex: buildModelIndex(models) });
        const input = out.slice(out.indexOf('data class WrapperInput('));
        expect(input).toContain('val credential: CredentialInput,');
        const read = out.slice(out.indexOf('data class Wrapper('), out.indexOf('data class WrapperInput('));
        expect(read).toContain('val credential: Credential,');
    });

    it('splits a model listed in modelsWithInput even when its own fields carry no visibility', () => {
        const models = [model('Plain', [field('a', scalarType('string'))])];
        const out = generateKotlinModels(contractRoot(models), {
            packageName: PKG,
            modelIndex: buildModelIndex(models),
            modelsWithInput: new Set(['Plain']),
        });
        expect(out).toContain('data class PlainInput(');
    });
});

// ─── Unions ────────────────────────────────────────────────────────────────

describe('plain unions', () => {
    it('emits a sealed interface with one wrapper case per member', () => {
        const out = gen([model('M', [field('v', unionType(refType('A'), scalarType('string')))]), model('A', [field('a', scalarType('string'))])]);
        expect(out).toContain('sealed interface MV {');
        expect(out).toContain('    data class OfA(val value: A) : MV');
        expect(out).toContain('    data class OfString(val value: String) : MV');
        expect(out).toContain('val v: MV,');
    });

    it('decodes members in declaration order, matching how the server union parses', () => {
        const out = gen([
            model('M', [field('v', unionType(refType('A'), refType('B')))]),
            model('A', [field('a', scalarType('string'))]),
            model('B', [field('b', scalarType('string'))]),
        ]);
        const body = out.slice(out.indexOf('override fun deserialize'));
        expect(body.indexOf('MV.OfA(')).toBeLessThan(body.indexOf('MV.OfB('));
        expect(body).toContain('throw SerializationException("No MV member matched the payload")');
    });

    it('collapses a union of one member and null to Kotlin’s own nullable type', () => {
        const out = gen([model('M', [field('v', unionType(scalarType('string'), scalarType('null')))])]);
        expect(out).toContain('val v: String?,');
        expect(out).not.toContain('sealed interface');
    });

    it('renders a union of string literals as an enum class', () => {
        const out = gen([model('M', [field('kind', unionType(literalType('card'), literalType('bank')))])]);
        expect(out).toContain('enum class MKind {');
        expect(out).toContain('    @SerialName("card")');
        expect(out).toContain('    CARD,');
        expect(out).toContain('val kind: MKind,');
    });

    it('marks the reference nullable when the union carries a null member alongside others', () => {
        const out = gen([model('M', [field('v', unionType(refType('A'), refType('B'), scalarType('null')))]), model('A', []), model('B', [])]);
        expect(out).toContain('val v: MV?,');
    });
});

describe('discriminated unions', () => {
    const members = () => [
        model('Card', [field('kind', literalType('card')), field('last4', scalarType('string'))]),
        model('Bank', [field('kind', literalType('bank')), field('accountId', scalarType('string'))]),
    ];

    it('emits a sealed interface the member classes implement', () => {
        const out = gen([
            ...members(),
            model('PaymentMethod', [], { type: { kind: 'discriminatedUnion', discriminator: 'kind', members: [refType('Card'), refType('Bank')] } }),
        ]);
        expect(out).toContain('sealed interface PaymentMethod');
        expect(out).toContain('data class Card(');
        expect(out).toContain(') : PaymentMethod');
        expect(out).not.toContain('typealias PaymentMethod');
    });

    it('keeps the discriminator as a real field defaulted to its literal, so a member posts standalone', () => {
        const out = gen([
            ...members(),
            model('PaymentMethod', [], { type: { kind: 'discriminatedUnion', discriminator: 'kind', members: [refType('Card'), refType('Bank')] } }),
        ]);
        expect(out).toContain('val kind: String = "card",');
    });

    it('dispatches on the tag when decoding and writes an explicit branch when encoding', () => {
        const out = gen([
            ...members(),
            model('PaymentMethod', [], { type: { kind: 'discriminatedUnion', discriminator: 'kind', members: [refType('Card'), refType('Bank')] } }),
        ]);
        expect(out).toContain('return when (val tag = element.jsonObject["kind"]?.jsonPrimitive?.contentOrNull) {');
        expect(out).toContain('            "card" -> input.json.decodeFromJsonElement(Card.serializer(), element)');
        expect(out).toContain('            is Card -> output.json.encodeToJsonElement(Card.serializer(), value)');
    });

    it('falls back to a raw JSON value when a member tag is an enum rather than a literal', () => {
        const warnings: string[] = [];
        const out = gen(
            [
                model('Card', [field('kind', enumType('card')), field('last4', scalarType('string'))]),
                model('Bank', [field('kind', enumType('bank'))]),
                model('PaymentMethod', [], {
                    type: { kind: 'discriminatedUnion', discriminator: 'kind', members: [refType('Card'), refType('Bank')] },
                }),
            ],
            { warn: m => warnings.push(m) },
        );
        expect(warnings.join('\n')).toMatch(/not a literal, so its tag is not known at build time/);
        expect(out).toContain('typealias PaymentMethod = JsonElement');
    });
});

// ─── Hoisted anonymous shapes ──────────────────────────────────────────────

describe('hoisted shapes', () => {
    it('names an inline object after the model and field that hold it', () => {
        const out = gen([model('M', [field('address', inlineObjectType([field('city', scalarType('string'))]))])]);
        expect(out).toContain('data class MAddress(');
        expect(out).toContain('    val city: String,');
        expect(out).toContain('val address: MAddress,');
    });

    it('names an inline object inside an array after the field, not the element', () => {
        const out = gen([model('M', [field('lines', arrayType(inlineObjectType([field('sku', scalarType('string'))])))])]);
        expect(out).toContain('data class MLines(');
        expect(out).toContain('val lines: List<MLines>,');
    });

    it('hoists a field-level enum into a real enum class', () => {
        const out = gen([model('M', [field('status', enumType('pending', 'done'))])]);
        expect(out).toContain('enum class MStatus {');
        expect(out).toContain('val status: MStatus,');
    });

    it('resolves an enum default to the generated entry rather than a bare string', () => {
        const out = gen([model('M', [field('status', enumType('pending', 'done'), { default: 'pending' })])]);
        expect(out).toContain('val status: MStatus? = MStatus.PENDING,');
    });

    it('flattens a field-level intersection into a data class', () => {
        const out = gen([
            model('A', [field('a', scalarType('string'))]),
            model('B', [field('b', scalarType('int'))]),
            model('M', [field('both', { kind: 'intersection', members: [refType('A'), refType('B')] })]),
        ]);
        expect(out).toContain('data class MBoth(');
        const section = out.slice(out.indexOf('data class MBoth('));
        expect(section).toContain('val a: String,');
        expect(section).toContain('val b: Long,');
    });

    it('gives a tuple Kotlin has no type for its own class and array serializer', () => {
        const out = gen([model('M', [field('quad', tupleType(scalarType('int'), scalarType('int'), scalarType('int'), scalarType('int')))])]);
        expect(out).toContain('data class MQuad(');
        expect(out).toContain('    val item0: Long,');
        expect(out).toContain('    val item3: Long,');
        expect(out).toContain('object MQuadSerializer : KSerializer<MQuad> {');
        expect(out).toContain('if (array.size != 4)');
    });

    it('suffixes a hoisted name that would collide with a real contract', () => {
        const out = gen([model('MStatus', [field('x', scalarType('string'))]), model('M', [field('status', enumType('a', 'b'))])]);
        expect(out).toContain('enum class MStatus2 {');
        expect(out).toContain('val status: MStatus2,');
    });

    it('gives a hoisted shape an Input twin only when its rendering differs', () => {
        const out = gen([
            model('Credential', [field('secret', scalarType('string'), { visibility: 'writeonly' })]),
            model('M', [field('wrapper', inlineObjectType([field('credential', refType('Credential'))])), field('tag', enumType('a', 'b'))]),
        ]);
        expect(out).toContain('data class MWrapperInput(');
        expect(out.slice(out.indexOf('data class MWrapperInput('))).toContain('val credential: CredentialInput,');
        expect(out).not.toContain('enum class MTagInput');
    });
});
