import { describe, expect, it } from 'vitest';
import { buildModelIndex } from '@contractkit/core';
import { generateKotlinModels } from '../src/codegen-models.js';
import {
    arrayType,
    contractRoot,
    enumType,
    field,
    inlineObjectType,
    literalType,
    model,
    recordType,
    refType,
    scalarType,
    tupleType,
    unionType,
} from './helpers.js';

const PKG = 'com.example.sdk';

function gen(models: Parameters<typeof contractRoot>[0], opts: Parameters<typeof generateKotlinModels>[1] | undefined = undefined): string {
    const root = contractRoot(models);
    return generateKotlinModels(root, { packageName: PKG, modelIndex: buildModelIndex(models), ...opts });
}

// ─── Scalars ───────────────────────────────────────────────────────────────

describe('scalar mapping', () => {
    const cases: [Parameters<typeof scalarType>[0], string][] = [
        ['string', 'String'],
        ['email', 'String'],
        ['url', 'String'],
        ['interval', 'String'],
        ['number', 'Double'],
        ['int', 'Long'],
        ['bigint', 'BigInt'],
        ['decimal', 'Decimal'],
        ['boolean', 'Boolean'],
        ['date', 'LocalDate'],
        ['time', 'LocalTime'],
        ['datetime', 'Instant'],
        ['duration', 'Duration'],
        ['uuid', 'Uuid'],
        ['binary', 'ByteArray'],
        ['unknown', 'JsonElement'],
        ['json', 'JsonElement'],
        ['object', 'JsonElement'],
    ];

    for (const [scalar, kotlin] of cases) {
        it(`maps ${scalar} to ${kotlin}`, () => {
            const out = gen([model('M', [field('v', scalarType(scalar))])]);
            expect(out).toContain(`val v: ${kotlin},`);
        });
    }

    it('maps null to the type of the null literal', () => {
        const out = gen([model('M', [field('v', scalarType('null'))])]);
        expect(out).toContain('val v: Nothing?,');
    });

    it('throws on an unmapped scalar rather than emitting Kotlin that will not compile', () => {
        expect(() => gen([model('M', [field('v', { kind: 'scalar', name: 'quaternion' } as never)])])).toThrow(/unmapped scalar 'quaternion'/);
    });
});

// ─── Imports and file header ───────────────────────────────────────────────

describe('file header', () => {
    it('declares the models package and the generated-file banner', () => {
        const out = gen([model('M', [field('v', scalarType('string'))])]);
        expect(out).toContain('// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.');
        expect(out).toContain('package com.example.sdk.models');
    });

    it('adds the Uuid opt-in above the package declaration, and only when Uuid is used', () => {
        const withUuid = gen([model('M', [field('id', scalarType('uuid'))])]);
        expect(withUuid).toContain('@file:OptIn(ExperimentalUuidApi::class)');
        expect(withUuid).toContain('import kotlin.uuid.ExperimentalUuidApi');
        expect(withUuid.indexOf('@file:OptIn')).toBeLessThan(withUuid.indexOf('package '));

        const withoutUuid = gen([model('M', [field('v', scalarType('string'))])]);
        expect(withoutUuid).not.toContain('@file:OptIn');
    });

    it('imports the runtime value classes only for the scalars that need them', () => {
        const out = gen([model('M', [field('a', scalarType('decimal')), field('b', scalarType('bigint'))])]);
        expect(out).toContain('import com.example.sdk.runtime.Decimal');
        expect(out).toContain('import com.example.sdk.runtime.BigInt');

        const plain = gen([model('M', [field('v', scalarType('string'))])]);
        expect(plain).not.toContain('com.example.sdk.runtime');
    });

    it('sorts imports so output is stable across runs', () => {
        const out = gen([model('M', [field('a', scalarType('uuid')), field('b', scalarType('datetime')), field('c', scalarType('date'))])]);
        const imports = out.split('\n').filter(l => l.startsWith('import '));
        expect(imports).toEqual([...imports].sort());
    });
});

// ─── Composite types ───────────────────────────────────────────────────────

describe('composite types', () => {
    it('maps array and record', () => {
        const out = gen([
            model('M', [field('items', arrayType(refType('Payment'))), field('meta', recordType(scalarType('string'), scalarType('string')))]),
            model('Payment', [field('id', scalarType('string'))]),
        ]);
        expect(out).toContain('val items: List<Payment>,');
        expect(out).toContain('val meta: Map<String, String>,');
    });

    it('warns and falls back to a string key for a non-string record key', () => {
        const warnings: string[] = [];
        gen([model('M', [field('meta', recordType(scalarType('int'), scalarType('string')))])], { packageName: PKG, warn: m => warnings.push(m) });
        expect(warnings.join('\n')).toMatch(/record key of type 'Long'/);
    });

    it('maps a 2- and 3-tuple onto Pair and Triple with the array serializer', () => {
        const out = gen([
            model('M', [
                field('range', tupleType(scalarType('int'), scalarType('int'))),
                field('point', tupleType(scalarType('number'), scalarType('number'), scalarType('number'))),
            ]),
        ]);
        expect(out).toContain('@Serializable(with = PairAsArraySerializer::class) val range: Pair<Long, Long>,');
        expect(out).toContain('@Serializable(with = TripleAsArraySerializer::class) val point: Triple<Double, Double, Double>,');
        expect(out).toContain('import com.example.sdk.runtime.PairAsArraySerializer');
    });

    it('falls back to JsonArray for a tuple arity Kotlin has no type for', () => {
        const out = gen([model('M', [field('quad', tupleType(scalarType('int'), scalarType('int'), scalarType('int'), scalarType('int')))])]);
        expect(out).toContain('val quad: JsonArray,');
    });

    it('renders a model ref by name, since every model shares one package', () => {
        const out = gen([model('M', [field('p', refType('Payment'))]), model('Payment', [field('id', scalarType('string'))])]);
        expect(out).toContain('val p: Payment,');
    });
});

// ─── Fields ────────────────────────────────────────────────────────────────

describe('fields', () => {
    it('makes an optional field nullable with a null default', () => {
        const out = gen([model('M', [field('bio', scalarType('string'), { optional: true })])]);
        expect(out).toContain('val bio: String? = null,');
    });

    it('makes a required nullable field nullable with no initializer, so the caller must pass it', () => {
        const out = gen([model('M', [field('note', scalarType('string'), { nullable: true })])]);
        expect(out).toContain('val note: String?,');
    });

    it('renders defaults in the field type', () => {
        const out = gen([
            model('M', [
                field('limit', scalarType('int'), { default: 20 }),
                field('ratio', scalarType('number'), { default: 1 }),
                field('label', scalarType('string'), { default: 'hi' }),
                field('on', scalarType('boolean'), { default: true }),
            ]),
        ]);
        expect(out).toContain('val limit: Long? = 20L,');
        expect(out).toContain('val ratio: Double? = 1.0,');
        expect(out).toContain('val label: String? = "hi",');
        expect(out).toContain('val on: Boolean? = true,');
    });

    it('escapes a dollar sign in a string default, which would otherwise start a template', () => {
        const out = gen([model('M', [field('label', scalarType('string'), { default: 'cost: $5' })])]);
        expect(out).toContain('"cost: \\$5"');
    });

    it('adds @SerialName only when the Kotlin name differs from the wire name', () => {
        const out = gen([model('M', [field('x-request-id', scalarType('string')), field('amount', scalarType('number'))])]);
        expect(out).toContain('@SerialName("x-request-id") val xRequestId: String,');
        expect(out).toContain('val amount: Double,');
        expect(out).not.toContain('@SerialName("amount")');
    });

    it('gives a literal field its value as a default so callers never restate it', () => {
        const out = gen([model('M', [field('kind', literalType('card'))])]);
        expect(out).toContain('val kind: String = "card",');
    });

    it('documents a field description and deprecation in KDoc', () => {
        const out = gen([model('M', [field('amount', scalarType('number'), { description: 'In cents.', deprecated: true })])]);
        expect(out).toContain('     * In cents.');
        expect(out).toContain('     * @deprecated');
    });
});

// ─── Classes, enums, aliases ───────────────────────────────────────────────

describe('declarations', () => {
    it('emits a serializable data class', () => {
        const out = gen([model('Payment', [field('id', scalarType('uuid'))], { description: 'A payment' })]);
        expect(out).toContain('/** A payment */');
        expect(out).toContain('@Serializable');
        expect(out).toContain('data class Payment(');
    });

    it('emits a plain class for a contract with no fields, since a data class needs one', () => {
        const out = gen([model('Empty', [])]);
        expect(out).toContain('@Serializable\nclass Empty');
        expect(out).not.toContain('data class Empty');
    });

    it('emits an enum class with a SerialName per value', () => {
        const out = gen([model('Status', [], { type: enumType('pending', 'in-progress') })]);
        expect(out).toContain('enum class Status {');
        expect(out).toContain('    @SerialName("pending")');
        expect(out).toContain('    PENDING,');
        expect(out).toContain('    @SerialName("in-progress")');
        expect(out).toContain('    IN_PROGRESS,');
    });

    it('emits a typealias for a scalar alias', () => {
        const out = gen([model('UserId', [], { type: scalarType('uuid') })]);
        expect(out).toContain('typealias UserId = Uuid');
    });

    it('emits a data class for an intersection alias rather than an opaque JSON object', () => {
        const out = gen([
            model('A', [field('a', scalarType('string'))]),
            model('B', [field('b', scalarType('int'))]),
            model('AB', [], { type: { kind: 'intersection', members: [refType('A'), refType('B')] } }),
        ]);
        expect(out).toContain('data class AB(');
        const section = out.slice(out.indexOf('data class AB('));
        expect(section).toContain('val a: String,');
        expect(section).toContain('val b: Long,');
    });
});

// ─── Inheritance ───────────────────────────────────────────────────────────

describe('inheritance', () => {
    it('flattens a single base into the subclass, since a data class cannot extend one', () => {
        const out = gen([
            model('BaseEntity', [field('id', scalarType('uuid'))]),
            model('Payment', [field('amount', scalarType('number'))], { bases: ['BaseEntity'] }),
        ]);
        const section = out.slice(out.indexOf('data class Payment('));
        expect(section).toContain('val id: Uuid,');
        expect(section).toContain('val amount: Double,');
        // No Kotlin inheritance: the base is copied in, not extended.
        expect(out).not.toContain(': BaseEntity');
    });

    it('flattens multiple bases in declaration order with the subclass last', () => {
        const out = gen([
            model('A', [field('a', scalarType('string'))]),
            model('B', [field('b', scalarType('int'))]),
            model('C', [field('c', scalarType('boolean'))], { bases: ['A', 'B'] }),
        ]);
        const section = out.slice(out.indexOf('data class C('));
        const order = ['val a:', 'val b:', 'val c:'].map(s => section.indexOf(s));
        expect(order).toEqual([...order].sort((x, y) => x - y));
        expect(order.every(i => i > -1)).toBe(true);
    });

    it('warns when a base is not defined anywhere in the project', () => {
        const warnings: string[] = [];
        const models = [model('Payment', [field('amount', scalarType('number'))], { bases: ['Missing'] })];
        generateKotlinModels(contractRoot(models), { packageName: PKG, modelIndex: buildModelIndex(models), warn: m => warnings.push(m) });
        expect(warnings.join('\n')).toMatch(/extends 'Missing', which is not defined/);
    });
});

// ─── Read / Input split ────────────────────────────────────────────────────

describe('read and input variants', () => {
    it('omits readonly fields from the Input class', () => {
        const out = gen([model('Payment', [field('id', scalarType('uuid'), { visibility: 'readonly' }), field('amount', scalarType('number'))])]);
        expect(out).toContain('data class Payment(');
        expect(out).toContain('data class PaymentInput(');
        const input = out.slice(out.indexOf('data class PaymentInput('));
        expect(input).not.toContain('val id:');
        expect(input).toContain('val amount: Double,');
    });

    it('omits writeonly fields from the Read class', () => {
        const out = gen([
            model('Session', [field('id', scalarType('string')), field('refreshToken', scalarType('string'), { visibility: 'writeonly' })]),
        ]);
        const read = out.slice(out.indexOf('data class Session('), out.indexOf('data class SessionInput('));
        expect(read).not.toContain('refreshToken');
        expect(out.slice(out.indexOf('data class SessionInput('))).toContain('val refreshToken: String,');
    });

    it('points an Input class at the Input variant of a referenced model', () => {
        const models = [
            model('Credential', [field('secret', scalarType('string'), { visibility: 'writeonly' })]),
            model('Wrapper', [field('credential', refType('Credential'))]),
        ];
        const out = generateKotlinModels(contractRoot(models), { packageName: PKG, modelIndex: buildModelIndex(models) });
        const input = out.slice(out.indexOf('data class WrapperInput('));
        expect(input).toContain('val credential: CredentialInput,');
        const read = out.slice(out.indexOf('data class Wrapper('), out.indexOf('data class WrapperInput('));
        expect(read).toContain('val credential: Credential,');
    });

    it('splits a model listed in modelsWithInput even when its own fields carry no visibility', () => {
        const models = [model('Plain', [field('a', scalarType('string'))])];
        const out = generateKotlinModels(contractRoot(models), {
            packageName: PKG,
            modelIndex: buildModelIndex(models),
            modelsWithInput: new Set(['Plain']),
        });
        expect(out).toContain('data class PlainInput(');
    });
});

// ─── Phase 1 fallbacks ─────────────────────────────────────────────────────

describe('types without a named Kotlin form yet', () => {
    it('renders a union as JsonElement', () => {
        const out = gen([model('M', [field('v', unionType(scalarType('string'), scalarType('int')))])]);
        expect(out).toContain('val v: JsonElement,');
    });

    it('renders an inline object as JsonObject', () => {
        const out = gen([model('M', [field('v', inlineObjectType([field('a', scalarType('string'))]))])]);
        expect(out).toContain('val v: JsonObject,');
    });
});
