// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
@file:OptIn(ExperimentalUuidApi::class)

package com.example.sdk.clients

import com.example.sdk.models.AdminCredentialInput
import com.example.sdk.models.Credential
import com.example.sdk.models.Payment
import com.example.sdk.models.PaymentInput
import com.example.sdk.models.PaymentRef
import com.example.sdk.models.Session
import com.example.sdk.models.SessionInput
import com.example.sdk.models.UpdatePaymentForm
import com.example.sdk.runtime.SdkHttp
import io.ktor.http.HttpMethod
import io.ktor.http.content.PartData
import kotlin.time.Instant
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Operations declared in `billing.ck`. */
class BillingClient(private val http: SdkHttp) {
    /**
     * create a payment
     * @throws SdkError on 400
     */
    suspend fun createPayment(body: PaymentInput): CreatePaymentResult {
        val response = http.execute(HttpMethod.Post) {
            path("payments")
            jsonBody(body, "application/json")
        }
        val headers = CreatePaymentHeaders(
            http.requireHeader(response, "x-request-id"),
            http.requireHeader(response, "x-ratelimit-remaining").toLong(),
            response.headers["x-cache-hit"]?.let { it == "true" },
            response.headers["x-expires-after"]?.let { Instant.parse(it) },
        )
        return CreatePaymentResult(http.decodeJson(response), headers)
    }

    /** list payments */
    suspend fun listPayments(query: ListPaymentsQuery, customHeaders: ListPaymentsHeaders): List<Payment> {
        val response = http.execute(HttpMethod.Get) {
            path("payments")
            params(query)
            headers(customHeaders)
        }
        return http.decodeJson(response)
    }

    /**
     * fetch one payment
     * @throws SdkError on 404
     */
    suspend fun getPayment(paymentId: Uuid): Payment {
        val response = http.execute(HttpMethod.Get) {
            path("payments", segment(paymentId))
        }
        return http.decodeJson(response)
    }

    /** update a payment with form data */
    suspend fun updatePaymentWithForm(paymentId: Uuid, body: UpdatePaymentForm) {
        http.execute(HttpMethod.Post) {
            path("payments", segment(paymentId))
            formBody(body)
        }
    }

    /**
     * delete a payment — declares only a documented error status
     * @throws SdkError on 400
     */
    suspend fun deletePayment(paymentId: Uuid) {
        http.execute(HttpMethod.Delete) {
            path("payments", segment(paymentId))
        }
    }

    /** upload a receipt image */
    suspend fun uploadReceipt(paymentId: Uuid, body: List<PartData>): Payment {
        val response = http.execute(HttpMethod.Post) {
            path("payments", segment(paymentId), "receipt")
            multipartBody(body)
        }
        return http.decodeJson(response)
    }

    /**
     * look up a refund by its originating payment
     * @throws SdkError on 404
     */
    @Deprecated("Deprecated in the contract")
    suspend fun getRefund(params: PaymentRef): Payment {
        val response = http.execute(HttpMethod.Get) {
            path("refunds", segment(params.paymentId))
        }
        return http.decodeJson(response)
    }

    /** store a credential */
    suspend fun createCredential(body: AdminCredentialInput): Credential {
        val response = http.execute(HttpMethod.Post) {
            path("credentials")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /** open a session */
    suspend fun createSession(body: SessionInput): Session {
        val response = http.execute(HttpMethod.Post) {
            path("sessions")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }
}

/** Response headers declared on POST /payments. */
data class CreatePaymentHeaders(
    val xRequestId: String,
    val xRatelimitRemaining: Long,
    val xCacheHit: Boolean?,
    val xExpiresAfter: Instant?,
)

/** The body of POST /payments, with the response headers the contract declares. */
data class CreatePaymentResult(
    val data: Payment,
    val headers: CreatePaymentHeaders,
)

@Serializable
data class ListPaymentsQuery(
    val limit: Long? = null,
    val cursor: String,
)

@Serializable
data class ListPaymentsHeaders(
    @SerialName("api-key") val apiKey: String? = null,
    @SerialName("x-tenant") val xTenant: String,
)
