// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
@file:OptIn(ExperimentalUuidApi::class)

package com.example.sdk.clients

import com.example.sdk.models.Invoice
import com.example.sdk.runtime.SdkHttp
import io.ktor.http.HttpMethod
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid

/** Operations declared in `hyphenated.ck`. */
class HyphenatedClient(private val http: SdkHttp) {
    /**
     * fetch an invoice
     * @throws SdkError on 404
     */
    suspend fun getInvoice(invoiceId: Uuid): Invoice {
        val response = http.execute(HttpMethod.Get) {
            path("invoices", segment(invoiceId))
        }
        return http.decodeJson(response)
    }
}
