// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
@file:OptIn(ExperimentalUuidApi::class)

package com.example.sdk.clients

import com.example.sdk.models.Folder
import com.example.sdk.models.Instrument
import com.example.sdk.models.Shared
import com.example.sdk.models.SharedInput
import com.example.sdk.models.Stamped
import com.example.sdk.models.Token
import com.example.sdk.runtime.SdkHttp
import io.ktor.http.HttpMethod
import kotlin.time.Instant
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Operations declared in `kitchen.ck`. */
class KitchenClient(private val http: SdkHttp) {
    /** several statuses, and two content types on one of them */
    suspend fun getFolder(folderId: Uuid, query: GetFolderQuery? = null, customHeaders: GetFolderHeaders): GetFolderResponse {
        val response = http.execute(HttpMethod.Get, expectStatuses = setOf(404)) {
            path("folders", segment(folderId))
            params(query)
            headers(customHeaders)
        }
        return when (response.status.value) {
            204 -> {
                GetFolderResponse.Status204
            }
            404 -> {
                GetFolderResponse.Status404(http.decodeJson(response))
            }
            else -> {
                val headers = GetFolder200Headers(
                    http.requireHeader(response, "x-count").toLong(),
                    response.headers["x-when"]?.let { Instant.parse(it) },
                )
                when (response.contentType) {
                    "text/plain" -> GetFolderResponse.Status200TextPlain(response.text, headers)
                    else -> GetFolderResponse.Status200ApplicationJson(http.decodeJson(response), headers)
                }
            }
        }
    }

    /** a method name that is a keyword in the target languages */
    suspend fun import(folderId: Uuid, body: SharedInput): Instrument {
        val response = http.execute(HttpMethod.Put) {
            path("folders", segment(folderId))
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    suspend fun stamp(body: Stamped): Stamped {
        val response = http.execute(HttpMethod.Post) {
            path("stamps")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    /** @throws SdkError on 400 */
    suspend fun mint(body: Token): Token {
        val response = http.execute(HttpMethod.Post) {
            path("tokens")
            jsonBody(body, "application/json")
        }
        return http.decodeJson(response)
    }

    suspend fun listTokens(): List<Token> {
        val response = http.execute(HttpMethod.Get) {
            path("tokens")
        }
        return http.decodeJson(response)
    }
}

@Serializable
data class GetFolderQuery(
    val depth: Long? = null,
    val tags: List<String>? = null,
)

@Serializable
data class GetFolderHeaders(
    @SerialName("x-trace") val xTrace: String,
    @SerialName("x-opt") val xOpt: Long? = null,
)

/** Response headers declared on GET /folders/{folder-id}. */
data class GetFolder200Headers(
    val xCount: Long,
    val xWhen: Instant?,
)

/**
 * What GET /folders/{folder-id} returned.
 *
 * The operation declares several statuses the service produces, so the status is part of the value.
 */
sealed interface GetFolderResponse {
    data class Status200ApplicationJson(
        val data: Folder,
    val headers: GetFolder200Headers,
    ) : GetFolderResponse
    data class Status200TextPlain(
        val data: String,
    val headers: GetFolder200Headers,
    ) : GetFolderResponse
    data object Status204 : GetFolderResponse
    data class Status404(
        val data: Shared,
    ) : GetFolderResponse
}
