// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
package com.example.sdk.clients

import com.example.sdk.models.Seat
import com.example.sdk.models.SeatRef
import com.example.sdk.runtime.SdkHttp
import io.ktor.http.HttpMethod
import kotlinx.datetime.LocalDate
import kotlinx.serialization.Serializable

/** Operations declared in `reserved.ck`. */
class ReservedClient(private val http: SdkHttp) {
    /** fetch one seat */
    suspend fun getSeat(`class`: String, query: GetSeatQuery? = null, customHeaders: GetSeatHeaders? = null): GetSeatResult {
        val response = http.execute(HttpMethod.Get) {
            path("seats", segment(`class`))
            params(query)
            headers(customHeaders)
        }
        val headers = GetSeatResponseHeaders(
            response.headers["from"]?.let { it },
        )
        return GetSeatResult(http.decodeJson(response), headers)
    }

    /** fetch a row by its seat class */
    suspend fun getRow(params: SeatRef): Seat {
        val response = http.execute(HttpMethod.Get) {
            path("rows", segment(params.`class`))
        }
        return http.decodeJson(response)
    }
}

@Serializable
data class GetSeatQuery(
    val from: LocalDate? = null,
    val `in`: String? = null,
    val pageSize: Long? = null,
)

@Serializable
data class GetSeatHeaders(
    val from: String? = null,
)

/** Response headers declared on GET /seats/{class}. */
data class GetSeatResponseHeaders(
    val from: String?,
)

/** The body of GET /seats/{class}, with the response headers the contract declares. */
data class GetSeatResult(
    val data: Seat,
    val headers: GetSeatResponseHeaders,
)
