// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
@file:OptIn(ExperimentalUuidApi::class)

package com.example.sdk.models

import com.example.sdk.runtime.BigInt
import com.example.sdk.runtime.Decimal
import kotlin.time.Duration
import kotlin.time.Instant
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid
import kotlinx.datetime.LocalDate
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** A customer payment */
@Serializable
data class Payment(
    val id: Uuid,
    val amount: Double,
    val unitPrice: Decimal,
    val quantity: BigInt,
    val createdAt: Instant,
    val processingTime: Duration? = null,
    val status: PaymentStatus? = PaymentStatus.PENDING,
)

/** A customer payment */
@Serializable
data class PaymentInput(
    val amount: Double,
    val unitPrice: Decimal,
    val quantity: BigInt,
    val createdAt: Instant,
    val processingTime: Duration? = null,
    val status: PaymentStatus? = PaymentStatus.PENDING,
)

/** A stored credential — has a writeonly child, so its Base schema is read */
@Serializable
data class Credential(
    val id: Uuid,
)

/** A stored credential — has a writeonly child, so its Base schema is read */
@Serializable
data class CredentialInput(
    val secret: String,
)

/** A writeonly model nothing extends — its Base schema has no reader */
@Serializable
data class Session(
    val id: String,
)

/** A writeonly model nothing extends — its Base schema has no reader */
@Serializable
data class SessionInput(
    val id: String,
    val refreshToken: String,
)

/** Path params declared as a model, referenced via `params: PaymentRef` */
@Serializable
data class PaymentRef(
    val paymentId: Uuid,
)

@Serializable
data class UpdatePaymentForm(
    val note: String? = null,
)

@Serializable
data class UploadReceiptForm(
    val caption: String? = null,
    val file: ByteArray? = null,
)

/** Query params declared as a model, referenced via `query: PaymentFilter` */
@Serializable
data class PaymentFilter(
    val status: PaymentFilterStatus? = null,
    val since: Instant? = null,
    val ids: List<Uuid>? = null,
)

/** Request headers declared as a model. Header names are case-insensitive, so any casing of `xCorrelationId` matches. */
@Serializable
data class TenantHeaders(
    @SerialName("x-tenant") val xTenant: String,
    val xCorrelationId: String? = null,
)

/**
 * Query params and headers declared as format() models. Each schema is a pipe with no `.strict()` of
 * its own, so the router applies the block's object mode to the object inside it.
 */
@Serializable
data class SnakeFilter(
    @SerialName("from_date") val fromDate: LocalDate? = null,
)

@Serializable
data class SnakeHeaders(
    @SerialName("tenant_id") val tenantId: String? = null,
)

/** Extends a writeonly base and is itself writeonly */
@Serializable
data class AdminCredential(
    val id: Uuid,
    val scope: String,
)

/** Extends a writeonly base and is itself writeonly */
@Serializable
data class AdminCredentialInput(
    val secret: String,
    val scope: String,
    val token: String,
)

@Serializable
enum class PaymentStatus {
    @SerialName("pending")
    PENDING,
    @SerialName("completed")
    COMPLETED,
    @SerialName("failed")
    FAILED,
}

@Serializable
enum class PaymentFilterStatus {
    @SerialName("pending")
    PENDING,
    @SerialName("completed")
    COMPLETED,
    @SerialName("failed")
    FAILED,
}
