// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
@file:OptIn(ExperimentalUuidApi::class)

package com.example.sdk.models

import com.example.sdk.runtime.Decimal
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid
import kotlinx.serialization.Serializable

@Serializable
data class Invoice(
    val id: Uuid,
    val total: Decimal,
)

@Serializable
data class InvoiceInput(
    val total: Decimal,
)
