// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
package com.example.sdk.models

import kotlinx.datetime.LocalDate
import kotlinx.serialization.Serializable

/** A seat, whose field names are all reserved somewhere */
@Serializable
data class Seat(
    val `class`: String,
    val from: LocalDate? = null,
    val `in`: String? = null,
    val `is`: Boolean? = null,
    val `object`: String? = null,
    val default: String? = null,
)

/** Path params declared as a model whose field is a keyword, referenced via `params: SeatRef` */
@Serializable
data class SeatRef(
    val `class`: String,
)
