import type { ContractRootNode, ModelNode, FieldNode, ContractTypeNode, ScalarTypeNode } from '@contractkit/core';
import { computeModelsWithInput, topoSortModels, collectExternalRefs, collectExternalInputRefs } from '@contractkit/core';

// ─── Public entry point ────────────────────────────────────────────────────

export interface ModelCodegenOptions {
    /** Map from model name → output module name (for cross-file imports) */
    modelModulePaths?: Map<string, string>;
    /** Current output module name (used to skip self-imports) */
    currentModule?: string;
    /** Set of model names that have Input variants (cross-file) */
    modelsWithInput?: Set<string>;
}

/**
 * Generate Pydantic v2 model classes from a ContractRootNode.
 */
export function generatePydanticModels(root: ContractRootNode, opts: ModelCodegenOptions = {}): string {
    const externalRefs = collectExternalRefs(root);
    const externalModelsWithInput = opts.modelsWithInput ?? new Set<string>();
    const localModelsWithInput = computeModelsWithInput(root.models, externalModelsWithInput);
    const allModelsWithInput = new Set([...localModelsWithInput, ...externalModelsWithInput]);

    const externalInputRefs = allModelsWithInput.size > 0 ? collectExternalInputRefs(root, allModelsWithInput) : [];
    const allExternalRefs = [...new Set([...externalRefs, ...externalInputRefs])].sort();

    // Track needed imports
    const imports = new ImportTracker();
    imports.add('pydantic', 'BaseModel');

    // Pre-scan all models to determine what imports will be needed
    for (const model of root.models) {
        if (model.type) {
            scanTypeImports(model.type, imports);
        } else {
            for (const f of model.fields) {
                scanTypeImports(f.type, imports);
            }
        }
    }

    const lines: string[] = [];
    lines.push('# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.');
    lines.push('from __future__ import annotations');

    // Cross-file imports for external model refs
    const crossFileImports: string[] = [];
    for (const ref of allExternalRefs) {
        const modulePath = opts.modelModulePaths?.get(ref);
        if (modulePath && modulePath !== opts.currentModule) {
            crossFileImports.push(`from ${modulePath} import ${ref}`);
        }
    }

    // We'll prepend stdlib/typing imports after, once we know what's needed
    // Build model output first
    const modelLines: string[] = [];
    for (const model of topoSortModels(root.models)) {
        modelLines.push('');
        modelLines.push(...generateModel(model, allModelsWithInput, imports));
    }

    // Now emit stdlib imports
    const stdlibLines = imports.render();
    lines.push(...stdlibLines);
    if (crossFileImports.length > 0) {
        lines.push('');
        lines.push(...crossFileImports);
    }
    lines.push(...modelLines);
    lines.push('');

    return lines.join('\n');
}

// ─── Shared scalar types ──────────────────────────────────────────────────

/** The generated module holding scalar types shared by every models and client module. */
export const SCALARS_MODULE = '._scalars';

/**
 * `_scalars.py`: contract scalars whose JSON form differs from their Python type.
 *
 * `bigint` is an `int` in Python, but a JSON number loses precision past 2**53, so no ContractKit
 * client sends one: the TypeScript SDK writes `"123n"`, the Kotlin, Swift and C# SDKs write `"123"`,
 * and the server's schema accepts either string and rejects a number. Mapping it to a bare `int`
 * put a number on the wire for every request, and failed to read a `"123n"` back. `BigInt` writes
 * the plain digit string the other typed SDKs do, and reads all three forms.
 */
export const SCALARS_PY = `# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.
"""Contract scalars whose JSON form differs from their Python type."""
from __future__ import annotations

from typing import Annotated, Any

from pydantic import BeforeValidator, PlainSerializer


def _parse_bigint(value: Any) -> Any:
    # "123n" is the TypeScript SDK's form, "123" the other SDKs', and a number whatever else a
    # server might send.
    if isinstance(value, str):
        text = value.strip()
        return int(text[:-1] if text.endswith("n") else text)
    return value


# A contract bigint: an int in Python, and a digit string in JSON, which keeps its precision past
# 2**53 and is what a ContractKit server accepts.
BigInt = Annotated[int, BeforeValidator(_parse_bigint), PlainSerializer(str, return_type=str, when_used="json")]
`;

// ─── Import tracking ──────────────────────────────────────────────────────

class ImportTracker {
    private groups: Map<string, Set<string>> = new Map();

    add(module: string, name: string): void {
        let s = this.groups.get(module);
        if (!s) {
            s = new Set();
            this.groups.set(module, s);
        }
        s.add(name);
    }

    has(module: string, name: string): boolean {
        return this.groups.get(module)?.has(name) ?? false;
    }

    render(): string[] {
        // Order: stdlib → typing → pydantic
        const ORDER = ['__future__', 'datetime', 'uuid', 'typing', 'pydantic'];
        const lines: string[] = [];
        lines.push('');
        for (const mod of ORDER) {
            const names = this.groups.get(mod);
            if (!names || names.size === 0) continue;
            const sorted = [...names].sort().join(', ');
            lines.push(`from ${mod} import ${sorted}`);
        }
        // Any remaining, with the SDK's own relative modules last
        const remaining = [...this.groups].filter(([mod]) => !ORDER.includes(mod));
        for (const [mod, names] of [...remaining.filter(([m]) => !m.startsWith('.')), ...remaining.filter(([m]) => m.startsWith('.'))]) {
            const sorted = [...names].sort().join(', ');
            lines.push(`from ${mod} import ${sorted}`);
        }
        return lines;
    }
}

function scanTypeImports(type: ContractTypeNode, imports: ImportTracker): void {
    switch (type.kind) {
        case 'scalar':
            switch (type.name) {
                case 'date':
                    imports.add('datetime', 'date');
                    break;
                case 'time':
                    imports.add('datetime', 'time');
                    break;
                case 'datetime':
                    imports.add('datetime', 'datetime');
                    break;
                case 'duration':
                    imports.add('datetime', 'timedelta');
                    break;
                case 'decimal':
                    imports.add('decimal', 'Decimal');
                    break;
                case 'bigint':
                    imports.add(SCALARS_MODULE, 'BigInt');
                    break;
                case 'uuid':
                    imports.add('uuid', 'UUID');
                    break;
                case 'unknown':
                case 'json':
                case 'object':
                    imports.add('typing', 'Any');
                    break;
            }
            break;
        case 'enum':
        case 'literal':
            imports.add('typing', 'Literal');
            break;
        case 'union':
            type.members.forEach(m => scanTypeImports(m, imports));
            break;
        case 'discriminatedUnion':
            imports.add('typing', 'Annotated');
            imports.add('pydantic', 'Field');
            type.members.forEach(m => scanTypeImports(m, imports));
            break;
        case 'intersection':
            imports.add('typing', 'Any');
            break;
        case 'array':
            scanTypeImports(type.item, imports);
            break;
        case 'tuple':
            type.items.forEach(t => scanTypeImports(t, imports));
            break;
        case 'record':
            scanTypeImports(type.key, imports);
            scanTypeImports(type.value, imports);
            break;
        case 'lazy':
            scanTypeImports(type.inner, imports);
            break;
        case 'inlineObject':
            imports.add('typing', 'Any');
            break;
    }
}

// ─── Type rendering ───────────────────────────────────────────────────────

/**
 * Render a ContractKit type node as its Python type annotation (Pydantic v2 conventions).
 *
 * @param modelsWithInput - Model names that have a distinct `Input` variant; a `ref` to one of
 *   these renders as `<Name>Input` when `forInput` is set.
 * @param forInput - When true, request-side refs use their `Input` variant.
 * @throws {Error} Via the scalar renderer, if a scalar name has no Python mapping (guards against
 *   a scalar being added to core without updating this plugin).
 */
export function renderPyType(type: ContractTypeNode, modelsWithInput?: Set<string>, forInput = false): string {
    switch (type.kind) {
        case 'scalar':
            return renderScalar(type.name);
        case 'enum':
            return `Literal[${type.values.map(v => JSON.stringify(v)).join(', ')}]`;
        case 'literal': {
            // A bare `"card"` annotation is a forward reference to a type named `card`, and `true`
            // is not Python at all, so a discriminated union's members could never be built.
            if (typeof type.value === 'boolean') return `Literal[${type.value ? 'True' : 'False'}]`;
            return `Literal[${typeof type.value === 'string' ? JSON.stringify(type.value) : String(type.value)}]`;
        }
        case 'array':
            return `list[${renderPyType(type.item, modelsWithInput, forInput)}]`;
        case 'tuple':
            if (type.items.length === 0) return 'tuple[()]';
            return `tuple[${type.items.map(t => renderPyType(t, modelsWithInput, forInput)).join(', ')}]`;
        case 'record':
            return `dict[${renderPyType(type.key, modelsWithInput, forInput)}, ${renderPyType(type.value, modelsWithInput, forInput)}]`;
        case 'union':
            return type.members.map(m => renderPyType(m, modelsWithInput, forInput)).join(' | ');
        case 'discriminatedUnion': {
            const inner = type.members.map(m => renderPyType(m, modelsWithInput, forInput)).join(' | ');
            return `Annotated[${inner}, Field(discriminator=${JSON.stringify(type.discriminator)})]`;
        }
        case 'intersection':
            return 'dict[str, Any]';
        case 'ref': {
            if (forInput && modelsWithInput?.has(type.name)) {
                return `${type.name}Input`;
            }
            return type.name;
        }
        case 'inlineObject':
            return 'dict[str, Any]';
        case 'lazy':
            return renderPyType(type.inner, modelsWithInput, forInput);
    }
}

function renderScalar(name: ScalarTypeNode['name']): string {
    switch (name) {
        case 'string':
        case 'email':
        case 'url':
            return 'str';
        case 'number':
            return 'float';
        case 'int':
            return 'int';
        case 'bigint':
            // An `int` that travels as a digit string; see SCALARS_PY.
            return 'BigInt';
        case 'decimal':
            return 'Decimal';
        case 'boolean':
            return 'bool';
        case 'date':
            return 'date';
        case 'time':
            return 'time';
        case 'datetime':
            return 'datetime';
        case 'duration':
            return 'timedelta';
        case 'interval':
            return 'str';
        case 'uuid':
            return 'UUID';
        case 'null':
            return 'None';
        case 'binary':
            return 'bytes';
        case 'unknown':
        case 'json':
        case 'object':
            return 'Any';
        default: {
            const _exhaustive: never = name;
            throw new Error(`plugin-python: unmapped scalar '${String(_exhaustive)}' — add a case`);
        }
    }
}

// ─── Field name conversion ────────────────────────────────────────────────

/**
 * Python's hard keywords, lowercase only: a snake_cased name can never spell `True`, `False` or
 * `None`. Soft keywords (`match`, `case`, `type`, `_`) are valid identifiers and are left alone.
 */
const PYTHON_KEYWORDS: ReadonlySet<string> = new Set([
    'and',
    'as',
    'assert',
    'async',
    'await',
    'break',
    'class',
    'continue',
    'def',
    'del',
    'elif',
    'else',
    'except',
    'finally',
    'for',
    'from',
    'global',
    'if',
    'import',
    'in',
    'is',
    'lambda',
    'nonlocal',
    'not',
    'or',
    'pass',
    'raise',
    'return',
    'try',
    'while',
    'with',
    'yield',
]);

/**
 * Append an underscore to a name that is a Python keyword, the PEP 8 convention (`class_`). Every
 * name the generator emits as an identifier goes through here: `class: str` as a model field and
 * `async def import(...)` as a method are both syntax errors that fail the whole module on import.
 */
export function escapePythonKeyword(name: string): string {
    return PYTHON_KEYWORDS.has(name) ? `${name}_` : name;
}

/**
 * Convert a field name to a valid Python identifier in snake_case. A keyword gains a trailing
 * underscore; the field then differs from its wire name, so it is aliased like any other rename.
 */
export function toPythonFieldName(name: string): string {
    // Replace hyphens and non-alphanumeric chars (except underscore) with underscore
    let result = name.replace(/[^a-zA-Z0-9_]/g, '_');
    // camelCase → snake_case
    result = result.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
    // Collapse multiple underscores
    result = result.replace(/_+/g, '_').replace(/^_|_$/g, '');
    // Prefix if starts with digit
    if (/^\d/.test(result)) result = 'f_' + result;
    return escapePythonKeyword(result);
}

// ─── Comment emission ─────────────────────────────────────────────────────

/**
 * Render `text` as one `#`-prefixed Python comment line per source line.
 * Descriptions come from `#` doc comments and may contain embedded newlines;
 * emitting them verbatim would leave every line after the first uncommented
 * (a SyntaxError in the generated module). `indent` is the whitespace prefix
 * that precedes `# ` at the call site.
 */
function commentLines(text: string, indent: string): string[] {
    return text.split('\n').map(line => `${indent}# ${line}`);
}

// ─── Model generation ─────────────────────────────────────────────────────

function generateModel(model: ModelNode, allModelsWithInput: Set<string>, imports: ImportTracker): string[] {
    if (model.type) {
        return generateTypeAlias(model, allModelsWithInput, imports);
    }

    const needsInputSplit = model.fields.some(f => f.visibility !== 'normal') || allModelsWithInput.has(model.name);

    if (needsInputSplit) {
        return generateSplitModel(model, allModelsWithInput, imports);
    }
    return generateSimpleModel(model, allModelsWithInput, imports);
}

/**
 * Contracts that `generateTypeAlias` emits as something other than a Pydantic class: `Tier =
 * Literal[...]`, `Method = Annotated[Card | Bank, ...]`, `Ids = list[str]`. A contract that only
 * renames a model (`B = A`, directly or through `lazy`) is still a class, and is left out.
 *
 * The client uses this to tell which refs have `model_validate` and `model_dump`. A capitalised
 * name does not say, and calling either on one of these is an `AttributeError`.
 */
export function computeTypeAliases(models: Iterable<ModelNode>): Set<string> {
    const byName = new Map([...models].map(m => [m.name, m]));
    const isClass = (name: string, seen: Set<string>): boolean => {
        const model = byName.get(name);
        if (!model?.type) return true;
        let type = model.type;
        while (type.kind === 'lazy') type = type.inner;
        if (type.kind !== 'ref' || seen.has(type.name)) return false;
        return isClass(type.name, new Set([...seen, name]));
    };
    return new Set([...byName.keys()].filter(name => !isClass(name, new Set())));
}

function generateTypeAlias(model: ModelNode, allModelsWithInput: Set<string>, _: ImportTracker): string[] {
    const lines: string[] = [];
    if (model.description) lines.push(...commentLines(model.description, ''));
    if (model.deprecated) lines.push('# @deprecated');
    lines.push(`${model.name} = ${renderPyType(model.type!, allModelsWithInput)}`);
    if (allModelsWithInput.has(model.name)) {
        lines.push(`${model.name}Input = ${renderPyType(model.type!, allModelsWithInput, true)}`);
    }
    return lines;
}

function generateSimpleModel(model: ModelNode, allModelsWithInput: Set<string>, imports: ImportTracker): string[] {
    const lines: string[] = [];
    if (model.description) lines.push(...commentLines(model.description, ''));
    if (model.deprecated) lines.push('# @deprecated');

    const baseList = model.bases && model.bases.length > 0 ? model.bases.join(', ') : 'BaseModel';
    lines.push(`class ${model.name}(${baseList}):`);
    lines.push(...renderClassBody(model.fields, modelFieldNames(model, allModelsWithInput), allModelsWithInput, imports, false));

    return lines;
}

function generateSplitModel(model: ModelNode, allModelsWithInput: Set<string>, imports: ImportTracker): string[] {
    const lines: string[] = [];
    // One set of names for both classes, so `Payment` and `PaymentInput` agree on every field.
    const names = modelFieldNames(model, allModelsWithInput);

    // Read model — omit writeonly fields
    const readFields = model.fields.filter(f => f.visibility !== 'writeonly');
    if (model.description) lines.push(...commentLines(model.description, ''));
    if (model.deprecated) lines.push('# @deprecated');

    const readBaseList = model.bases && model.bases.length > 0 ? model.bases.join(', ') : 'BaseModel';
    lines.push(`class ${model.name}(${readBaseList}):`);
    lines.push(...renderClassBody(readFields, names, allModelsWithInput, imports, false));

    lines.push('');

    // Input model — omit readonly fields
    const writeFields = model.fields.filter(f => f.visibility !== 'readonly');
    const inputBaseList =
        model.bases && model.bases.length > 0 ? model.bases.map(b => (allModelsWithInput.has(b) ? `${b}Input` : b)).join(', ') : 'BaseModel';
    lines.push(`class ${model.name}Input(${inputBaseList}):`);
    lines.push(...renderClassBody(writeFields, names, allModelsWithInput, imports, true));

    return lines;
}

/**
 * Public attributes of Pydantic's `BaseModel` (as of 2.13). A field named after one either fails
 * class creation (`model_config`, and the `model_dump` and `model_validate` families, which are
 * protected namespaces) or shadows the method with a `UserWarning` at import, which a test suite
 * running with `-W error` turns into a failure. The client also calls `model_dump` and
 * `model_validate` on these models itself.
 */
const BASE_MODEL_ATTRIBUTES: ReadonlySet<string> = new Set(
    (
        'construct copy dict from_orm json model_computed_fields model_config model_construct model_copy model_dump ' +
        'model_dump_json model_extra model_fields model_fields_set model_json_schema model_parametrized_name ' +
        'model_post_init model_rebuild model_validate model_validate_json model_validate_strings parse_file ' +
        'parse_obj parse_raw schema schema_json update_forward_refs validate'
    ).split(' '),
);

/**
 * The Python attribute name of each of a model's fields.
 *
 * On top of `toPythonFieldName`, a name gets a trailing underscore when it is one of
 * `BASE_MODEL_ATTRIBUTES`, or when it would shadow a type its own class annotates with. The second
 * case is narrower than it sounds, and deliberately so. Pydantic evaluates the deferred annotations
 * against the class namespace, so a field that puts a value there (`date: str | None = None`)
 * replaces the imported `date` for every annotation in the class: the module fails to import, or
 * a sibling `when: date` silently validates as `None`. A field with no right-hand side puts nothing
 * in the namespace, so `date: date` works as it is and keeps its name.
 */
function modelFieldNames(model: ModelNode, allModelsWithInput: Set<string>): Map<FieldNode, string> {
    // Every identifier either class's annotations read. Quoted literals are dropped first, since
    // `Literal["date"]` names no type.
    const annotationNames = new Set<string>();
    for (const f of model.fields) {
        for (const forInput of [false, true]) {
            const rendered = renderPyType(f.type, allModelsWithInput, forInput).replace(/"(?:[^"\\]|\\.)*"/g, '');
            for (const id of rendered.match(/[A-Za-z_]\w*/g) ?? []) annotationNames.add(id);
        }
    }

    const names = new Map<FieldNode, string>();
    for (const f of model.fields) {
        let pyName = toPythonFieldName(f.name);
        const hasRightHandSide = f.optional || f.default !== undefined || pyName !== f.name;
        if (BASE_MODEL_ATTRIBUTES.has(pyName) || (hasRightHandSide && annotationNames.has(pyName))) pyName += '_';
        names.set(f, pyName);
    }
    return names;
}

/** A class's `model_config`, if it needs one, then its fields, or `pass` when it has none. */
function renderClassBody(
    fields: FieldNode[],
    names: Map<FieldNode, string>,
    allModelsWithInput: Set<string>,
    imports: ImportTracker,
    forInput: boolean,
): string[] {
    const settings: string[] = [];
    // Any field whose name differs from the contract's is aliased, and without this the model
    // could only be built from the alias: `Seat(class_=...)` would be rejected.
    if (fields.some(f => names.get(f) !== f.name)) settings.push('populate_by_name=True');
    // Pydantic reserves `model_` names for its own methods: 2.10 and later warn on the
    // `model_dump` and `model_validate` prefixes, earlier releases on any `model_` name. The
    // names that actually collide are escaped by `modelFieldNames`, so `model_name` is safe.
    if (fields.some(f => names.get(f)!.startsWith('model_'))) settings.push('protected_namespaces=()');

    const lines: string[] = [];
    if (settings.length > 0) {
        imports.add('pydantic', 'ConfigDict');
        lines.push(`    model_config = ConfigDict(${settings.join(', ')})`, '');
    }
    const fieldLines = fields.flatMap(f => renderField(f, names.get(f)!, allModelsWithInput, imports, forInput));
    lines.push(...(fieldLines.length > 0 ? fieldLines : ['    pass']));
    return lines;
}

function renderField(field: FieldNode, pyName: string, allModelsWithInput: Set<string>, imports: ImportTracker, forInput: boolean): string[] {
    const lines: string[] = [];
    const needsAlias = pyName !== field.name;

    let typeStr = renderPyType(field.type, allModelsWithInput, forInput);
    if (field.nullable) typeStr = `${typeStr} | None`;

    const isOptional = field.optional || field.default !== undefined;

    const fieldAnnotations: string[] = [];
    if (needsAlias) {
        imports.add('pydantic', 'Field');
        fieldAnnotations.push(`alias=${JSON.stringify(field.name)}`);
    }
    if (field.default !== undefined) {
        const def = typeof field.default === 'string' ? JSON.stringify(field.default) : String(field.default);
        fieldAnnotations.push(`default=${def}`);
    } else if (field.optional && needsAlias) {
        // The alias moves the right-hand side into `Field(...)`, so the bare `= None` an optional
        // field gets below never applies, and to Pydantic a `Field` without a default is required.
        fieldAnnotations.push('default=None');
    }

    if (field.deprecated) lines.push(`    # @deprecated`);
    if (field.description) lines.push(...commentLines(field.description, '    '));

    let rhs: string;
    if (fieldAnnotations.length > 0) {
        imports.add('pydantic', 'Field');
        rhs = `Field(${fieldAnnotations.join(', ')})`;
    } else if (isOptional) {
        rhs = 'None';
    } else {
        rhs = '';
    }

    const optSuffix = isOptional && !field.nullable ? ` | None` : '';
    const fullType = typeStr + optSuffix;

    if (rhs) {
        lines.push(`    ${pyName}: ${fullType} = ${rhs}`);
    } else {
        lines.push(`    ${pyName}: ${fullType}`);
    }

    return lines;
}

// ─── Module name helpers ──────────────────────────────────────────────────

/** Derive a Python module name from a .ck file path, e.g. "ledger.categories.ck" → "_models_ledger_categories" */
export function deriveModelsModuleName(file: string): string {
    const base =
        file
            .split('/')
            .pop()
            ?.replace(/\.(op\.)?ck$/, '') ?? 'models';
    const clean = base.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase();
    return `_models_${clean}`;
}
