import type {
    OpRootNode,
    OpRouteNode,
    OpOperationNode,
    OpResponseNode,
    OpResponseBodyNode,
    OpResponseHeaderNode,
    ContractTypeNode,
    ParamSource,
} from '@contractkit/core';
import { resolveModifiers, classifyContentType, observableResponses } from '@contractkit/core';
import { renderPyType, toPythonFieldName } from './codegen-models.js';

// ─── Response shape ────────────────────────────────────────────────────────

/**
 * How a method reports what came back, mirroring the TypeScript SDK.
 *
 * `simple` is the overwhelmingly common case and generates exactly what it always has: the body
 * itself, or a `(data, headers)` tuple. The other two exist because the caller cannot otherwise
 * know which status or which mime it received.
 */
type PyResponseShape =
    | { kind: 'simple'; resp?: OpResponseNode }
    | { kind: 'multiMime'; resp: OpResponseNode }
    | { kind: 'multiStatus'; responses: OpResponseNode[] };

function headersClassName(methodBase: string, statusCode?: number): string {
    return statusCode === undefined ? `${methodBase}Headers` : `${methodBase}${statusCode}Headers`;
}

function responseClassName(methodBase: string, statusCode?: number): string {
    return statusCode === undefined ? `${methodBase}Response` : `${methodBase}${statusCode}Response`;
}

/** The Python type of one response body — non-JSON mimes ignore the schema, as elsewhere. */
function pyBodyType(body: OpResponseBodyNode, modelsWithInput?: Set<string>): string {
    const category = classifyContentType(body.contentType);
    if (category === 'text') return 'str';
    if (category === 'binary') return 'bytes';
    return renderPyType(body.bodyType, modelsWithInput);
}

function pyDataAnnotation(bodies: OpResponseBodyNode[], modelsWithInput?: Set<string>): string {
    const types = [...new Set(bodies.map(b => pyBodyType(b, modelsWithInput)))];
    return types.join(' | ');
}

function pyContentTypeAnnotation(bodies: OpResponseBodyNode[]): string {
    return `Literal[${bodies.map(b => JSON.stringify(b.contentType)).join(', ')}]`;
}

function responseShape(op: OpOperationNode): PyResponseShape {
    const observable = observableResponses(op);
    if (observable.length > 1) return { kind: 'multiStatus', responses: observable };
    const resp = observable[0];
    if (resp && resp.bodies.length > 1) return { kind: 'multiMime', resp };
    return { kind: 'simple', resp };
}

// ─── Public entry point ────────────────────────────────────────────────────

export interface ClientCodegenOptions {
    /** Map from model name → Python module path (e.g. "._models_payments") */
    modelModulePaths?: Map<string, string>;
    /** Current client's module name (e.g. "_client_payments") — used to avoid self-imports */
    currentModule?: string;
    /** Set of model names that have Input variants */
    modelsWithInput?: Set<string>;
    /**
     * Whether to emit client methods for operations marked `internal`. Defaults to `false` —
     * internal ops are omitted so consumers don't pick them up. Set to `true` for an
     * internal-use SDK that should expose them.
     */
    includeInternal?: boolean;
}

/**
 * Returns true if the root contains at least one operation eligible for client emission.
 * With `includeInternal: false` (default) that means at least one non-internal op; with
 * `includeInternal: true` any op qualifies.
 */
export function hasPublicOperations(root: OpRootNode, includeInternal = false): boolean {
    for (const route of root.routes) {
        for (const op of route.operations) {
            if (includeInternal || !resolveModifiers(route, op).includes('internal')) return true;
        }
    }
    return false;
}

/**
 * Generate a Pydantic/httpx async Python client class from an OpRootNode.
 */
export function generatePythonClient(root: OpRootNode, opts: ClientCodegenOptions = {}): string {
    const clientClassName = deriveClientClassName(root.file);
    const { modelsWithInput } = opts;
    const includeInternal = opts.includeInternal ?? false;

    // Collect all model types referenced in public ops
    const referencedModels = collectReferencedModels(root, modelsWithInput, includeInternal);

    const lines: string[] = [];
    lines.push('# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.');
    lines.push('from __future__ import annotations');
    lines.push('');

    // Collect public ops once — used both for TypedDict emission and method generation.
    const publicOps: Array<{ route: OpRouteNode; op: OpOperationNode }> = [];
    for (const route of root.routes) {
        for (const op of route.operations) {
            if (!includeInternal && resolveModifiers(route, op).includes('internal')) continue;
            publicOps.push({ route, op });
        }
    }

    // stdlib imports
    const needsDatetime = referencedModels.has('__datetime__');
    const needsDate = referencedModels.has('__date__');
    const needsTime = referencedModels.has('__time__');
    const needsDecimal = referencedModels.has('__decimal__');
    const needsUUID = referencedModels.has('__uuid__');
    const needsAny = referencedModels.has('__any__');

    if (needsDatetime || needsDate || needsTime) {
        const dtParts: string[] = [];
        if (needsDate) dtParts.push('date');
        if (needsDatetime) dtParts.push('datetime');
        if (needsTime) dtParts.push('time');
        lines.push(`from datetime import ${dtParts.join(', ')}`);
    }
    if (needsDecimal) lines.push('from decimal import Decimal');
    if (needsUUID) lines.push('from uuid import UUID');
    // Path params are percent-encoded, so `quote` is needed wherever a route interpolates one.
    if (publicOps.some(({ route }) => /\{[a-zA-Z_$][a-zA-Z0-9_$.-]*\}/.test(route.path))) {
        lines.push('from urllib.parse import quote');
    }

    const opShapes = new Map<OpOperationNode, PyResponseShape>(publicOps.map(({ op }) => [op, responseShape(op)]));
    const opsWithRespHeaders = publicOps.filter(({ op }) => {
        const shape = opShapes.get(op)!;
        if (shape.kind === 'multiStatus') return shape.responses.some(r => (r.headers?.length ?? 0) > 0);
        return (shape.resp?.headers?.length ?? 0) > 0;
    });
    const opsWithResponseDict = publicOps.filter(({ op }) => opShapes.get(op)!.kind !== 'simple');
    const needsTypedDict = opsWithRespHeaders.length > 0 || opsWithResponseDict.length > 0;
    const needsLiteral = opsWithResponseDict.length > 0;

    if (needsAny || needsTypedDict) {
        const typingImports: string[] = [];
        if (needsAny) typingImports.push('Any');
        if (needsLiteral) typingImports.push('Literal');
        if (needsTypedDict) typingImports.push('TypedDict');
        lines.push(`from typing import ${typingImports.join(', ')}`);
    }
    lines.push('from ._base_client import BaseClient, SdkError  # noqa: F401');

    // Model imports grouped by module
    const modelImportsByModule = new Map<string, Set<string>>();
    for (const name of referencedModels) {
        if (name.startsWith('__')) continue; // sentinel keys
        const modulePath = opts.modelModulePaths?.get(name);
        if (modulePath) {
            let s = modelImportsByModule.get(modulePath);
            if (!s) {
                s = new Set();
                modelImportsByModule.set(modulePath, s);
            }
            s.add(name);
        }
    }
    for (const [mod, names] of [...modelImportsByModule].sort((a, b) => a[0].localeCompare(b[0]))) {
        const sorted = [...names].sort().join(', ');
        lines.push(`from ${mod} import ${sorted}`);
    }

    // Per-method response-header TypedDicts. Multi-status methods get one per status, since
    // each status declares its own headers.
    for (const { route, op } of opsWithRespHeaders) {
        const shape = opShapes.get(op)!;
        const base = snakeToPascal(deriveMethodName(op, route));
        const targets =
            shape.kind === 'multiStatus'
                ? shape.responses.filter(r => (r.headers?.length ?? 0) > 0).map(r => ({ name: headersClassName(base, r.statusCode), resp: r }))
                : [{ name: headersClassName(base), resp: shape.resp! }];
        for (const { name, resp } of targets) {
            lines.push('');
            lines.push('');
            lines.push(`class ${name}(TypedDict, total=False):`);
            for (const h of resp.headers!) {
                const pyName = toPythonFieldName(h.name);
                const tag = h.optional ? 'optional' : 'required';
                lines.push(`    ${pyName}: str  # ${h.name} (${tag})`);
            }
        }
    }

    // Per-method response TypedDicts for the shapes that have to report status or mime.
    for (const { route, op } of opsWithResponseDict) {
        const shape = opShapes.get(op)!;
        const base = snakeToPascal(deriveMethodName(op, route));
        const targets: OpResponseNode[] = shape.kind === 'multiStatus' ? shape.responses : shape.kind === 'multiMime' ? [shape.resp] : [];
        for (const resp of targets) {
            lines.push('');
            lines.push('');
            lines.push(`class ${responseClassName(base, shape.kind === 'multiStatus' ? resp.statusCode : undefined)}(TypedDict):`);
            if (shape.kind === 'multiStatus') lines.push(`    status: Literal[${resp.statusCode}]`);
            const bodies = resp.bodies;
            if (bodies.length > 0) {
                lines.push(`    content_type: ${pyContentTypeAnnotation(bodies)}`);
                lines.push(`    data: ${pyDataAnnotation(bodies, opts.modelsWithInput)}`);
            }
            if ((resp.headers?.length ?? 0) > 0) {
                lines.push(`    headers: ${headersClassName(base, shape.kind === 'multiStatus' ? resp.statusCode : undefined)}`);
            }
            if (shape.kind !== 'multiStatus' && bodies.length === 0 && (resp.headers?.length ?? 0) === 0) {
                lines.push('    pass');
            }
        }
    }

    lines.push('');
    lines.push('');
    lines.push(`class ${clientClassName}(BaseClient):`);

    let hasAnyMethod = false;
    for (const route of root.routes) {
        for (const op of route.operations) {
            const mods = resolveModifiers(route, op);
            if (!includeInternal && mods.includes('internal')) continue;
            hasAnyMethod = true;
            lines.push('');
            if (mods.includes('deprecated')) lines.push('    # @deprecated');
            lines.push(...generateMethod(route, op, opts));
        }
    }

    if (!hasAnyMethod) {
        lines.push('    pass');
    }

    lines.push('');

    return lines.join('\n');
}

// ─── Method generation ────────────────────────────────────────────────────

interface MethodParam {
    name: string;
    type: string;
    optional: boolean;
    isModel: boolean; // Pydantic BaseModel → use .model_dump(mode="json")
}

function generateMethod(route: OpRouteNode, op: OpOperationNode, opts: ClientCodegenOptions): string[] {
    const lines: string[] = [];
    const { modelsWithInput } = opts;
    const methodName = deriveMethodName(op, route);
    const httpMethod = op.method.toUpperCase();

    const params = buildMethodParams(route, op, modelsWithInput);
    const selfParam = 'self';
    const allParams = params.map(p => {
        if (p.optional) return `${p.name}: ${p.type} | None = None`;
        return `${p.name}: ${p.type}`;
    });
    const paramStr = allParams.length > 0 ? `, ${allParams.join(', ')}` : '';

    // Return type — non-JSON responses ignore the schema and return raw bytes/str.
    //
    // `observableResponses` is shared with the Koa router and the TypeScript SDK, so all three
    // agree on which statuses are values and which are errors.
    const shape = responseShape(op);
    const methodBase = snakeToPascal(methodName);
    const primaryResponse = shape.kind === 'multiStatus' ? undefined : shape.resp;
    const primaryBodies = primaryResponse ? primaryResponse.bodies : [];
    const isVoid = primaryBodies.length === 0;
    const respCategory = primaryBodies[0] ? classifyContentType(primaryBodies[0].contentType) : 'json';
    const dataType = isVoid ? 'None' : pyBodyType(primaryBodies[0]!, modelsWithInput);
    const isModelReturn = !isVoid && respCategory === 'json' && isModelRef(primaryBodies[0]!.bodyType, modelsWithInput);
    const isListModelReturn = !isVoid && respCategory === 'json' && isListModelRef(primaryBodies[0]!.bodyType, modelsWithInput);
    const respHeaders = primaryResponse?.headers ?? [];
    const hasRespHeaders = respHeaders.length > 0;
    const headersTypeName = hasRespHeaders ? headersClassName(methodBase) : '';
    const returnType =
        shape.kind === 'multiStatus'
            ? shape.responses.map(r => responseClassName(methodBase, r.statusCode)).join(' | ')
            : shape.kind === 'multiMime'
              ? responseClassName(methodBase)
              : hasRespHeaders
                ? isVoid
                    ? headersTypeName
                    : `tuple[${dataType}, ${headersTypeName}]`
                : dataType;

    // Description
    const desc = op.description ?? route.description;
    if (op.name || desc) {
        lines.push(`    async def ${methodName}(${selfParam}${paramStr}) -> ${returnType}:`);
        lines.push(`        """`);
        if (op.name) lines.push(...docstringLines(op.name, '        '));
        if (desc) lines.push(...docstringLines(desc, '        '));
        lines.push(`        """`);
    } else {
        lines.push(`    async def ${methodName}(${selfParam}${paramStr}) -> ${returnType}:`);
    }

    // Build URL
    const urlExpr = buildUrlExpression(route.path, route.params);

    // Query params
    const hasQuery = !!op.query;
    const primaryBody = op.request?.bodies[0];
    const hasBody = !!primaryBody;
    const isMultipart = primaryBody?.contentType === 'multipart/form-data';
    const hasCustomHeaders = !!op.headers;

    // Build kwargs for _fetch
    const fetchKwargs: string[] = [];
    fetchKwargs.push(`method="${httpMethod}"`);

    const reqCategory = primaryBody?.contentType ? classifyContentType(primaryBody.contentType) : 'json';
    if (hasBody) {
        const bodyParam = params.find(p => p.name === 'body');
        if (isMultipart) {
            fetchKwargs.push('body=body');
        } else if (reqCategory === 'text' || reqCategory === 'binary') {
            // Pass-through: caller supplies a str / bytes payload that goes on the wire as-is.
            fetchKwargs.push('body=body');
        } else if (bodyParam?.isModel) {
            fetchKwargs.push('body=body.model_dump(mode="json")');
        } else {
            fetchKwargs.push('body=body');
        }
        // Forward the declared content-type so `_fetch` sets the correct Content-Type header
        // (vendor JSON types like `application/vnd.api+json` still serialize as JSON but need
        // their literal mime on the wire).
        if (primaryBody.contentType !== 'application/json') {
            fetchKwargs.push(`content_type=${JSON.stringify(primaryBody.contentType)}`);
        }
        // Without this, urlencoded and multipart fell through to the `"json"` default and httpx
        // sent them via `json=` — a JSON document under a form Content-Type, which no server
        // parses, and a TypeError outright when the body is bytes.
        if (reqCategory !== 'json') {
            fetchKwargs.push(`body_kind="${reqCategory === 'urlencoded' ? 'form' : reqCategory}"`);
        }
    }
    if (shape.kind !== 'simple') {
        // Several mimes or statuses in play — only the response knows how to read itself.
        fetchKwargs.push(`response_kind="auto"`);
    } else if (respCategory === 'text' || respCategory === 'binary') {
        fetchKwargs.push(`response_kind="${respCategory}"`);
    }

    const observable = shape.kind === 'multiStatus' ? shape.responses : shape.resp ? [shape.resp] : [];
    const expectStatuses = observable.filter(r => r.statusCode < 200 || r.statusCode >= 300).map(r => r.statusCode);
    if (expectStatuses.length > 0) {
        // A single-element tuple needs the trailing comma or Python reads it as parentheses.
        const tuple = expectStatuses.length === 1 ? `(${expectStatuses[0]},)` : `(${expectStatuses.join(', ')})`;
        fetchKwargs.push(`expect_statuses=${tuple}`);
    }

    if (hasQuery) {
        fetchKwargs.push('params=query');
    }

    if (hasCustomHeaders) {
        fetchKwargs.push('extra_headers=custom_headers');
    }

    const kwargsStr = fetchKwargs.length > 1 ? fetchKwargs.join(', ') : (fetchKwargs[0] ?? '');

    if (shape.kind !== 'simple') {
        lines.push(`        _status, _content_type, result, _response_headers = await self._fetch_full(${urlExpr}, ${kwargsStr})`);
        lines.push(...buildMultiReturnLines(shape, methodBase, modelsWithInput));
        return lines;
    }

    if (hasRespHeaders) {
        lines.push(`        result, _response_headers = await self._fetch_with_headers(${urlExpr}, ${kwargsStr})`);
        lines.push(...buildHeadersDictLines(respHeaders, headersTypeName));
    } else {
        lines.push(`        result = await self._fetch(${urlExpr}, ${kwargsStr})`);
    }

    if (isVoid) {
        if (hasRespHeaders) {
            lines.push(`        return headers`);
        } else {
            lines.push(`        return None`);
        }
    } else {
        let dataExpr: string;
        if (isListModelReturn) {
            const innerType = getListItemType(primaryBodies[0]!.bodyType, modelsWithInput);
            dataExpr = `[${innerType}.model_validate(item) for item in result]`;
        } else if (isModelReturn) {
            dataExpr = `${dataType}.model_validate(result)`;
        } else {
            dataExpr = 'result';
        }
        if (hasRespHeaders) {
            lines.push(`        return ${dataExpr}, headers`);
        } else {
            lines.push(`        return ${dataExpr}`);
        }
    }

    return lines;
}

/** The expression that turns a decoded body into the declared type, validating models. */
function pyDataExpr(body: OpResponseBodyNode, modelsWithInput?: Set<string>): string {
    if (classifyContentType(body.contentType) !== 'json') return 'result';
    if (isListModelRef(body.bodyType, modelsWithInput)) {
        return `[${getListItemType(body.bodyType, modelsWithInput)}.model_validate(item) for item in result]`;
    }
    if (isModelRef(body.bodyType, modelsWithInput)) {
        return `${renderPyType(body.bodyType, modelsWithInput)}.model_validate(result)`;
    }
    return 'result';
}

/**
 * Return statements for a method that reports its status or mime.
 *
 * Dispatch is a chain of `if`s on the runtime status (or content type), with the first declared
 * alternative as the fall-through so the function always returns.
 */
function buildMultiReturnLines(
    shape: Extract<PyResponseShape, { kind: 'multiMime' | 'multiStatus' }>,
    methodBase: string,
    modelsWithInput?: Set<string>,
): string[] {
    const lines: string[] = [];

    const returnFor = (resp: OpResponseNode, body: OpResponseBodyNode | undefined, indent: string, includeStatus: boolean, headersVar?: string): string[] => {
        const entries: string[] = [];
        if (includeStatus) entries.push(`"status": ${resp.statusCode}`);
        if (body) {
            entries.push(`"content_type": ${JSON.stringify(body.contentType)}`);
            entries.push(`"data": ${pyDataExpr(body, modelsWithInput)}`);
        }
        if (headersVar) entries.push(`"headers": ${headersVar}`);
        return [`${indent}return {${entries.length > 0 ? ` ${entries.join(', ')} ` : ''}}`];
    };

    /** One status, dispatching over its mimes when they do not all decode the same way. */
    const emitStatus = (resp: OpResponseNode, indent: string, includeStatus: boolean): string[] => {
        const out: string[] = [];
        // Built once per status, under a name of its own: two statuses in the same method can
        // declare different headers, and Python has no block scope to keep them apart.
        let headersVar: string | undefined;
        if ((resp.headers?.length ?? 0) > 0) {
            headersVar = includeStatus ? `headers_${resp.statusCode}` : 'headers';
            const typeName = headersClassName(methodBase, includeStatus ? resp.statusCode : undefined);
            out.push(...buildHeadersDictLines(resp.headers!, typeName, indent, headersVar));
        }

        const bodies = resp.bodies;
        if (bodies.length <= 1) {
            out.push(...returnFor(resp, bodies[0], indent, includeStatus, headersVar));
            return out;
        }
        for (const body of bodies.slice(1)) {
            out.push(`${indent}if _content_type == ${JSON.stringify(body.contentType)}:`);
            out.push(...returnFor(resp, body, `${indent}    `, includeStatus, headersVar));
        }
        out.push(...returnFor(resp, bodies[0], indent, includeStatus, headersVar));
        return out;
    };

    if (shape.kind === 'multiMime') {
        lines.push(...emitStatus(shape.resp, '        ', false));
        return lines;
    }

    const [fallback, ...rest] = shape.responses;
    for (const resp of rest) {
        lines.push(`        if _status == ${resp.statusCode}:`);
        lines.push(...emitStatus(resp, '            ', true));
    }
    lines.push(...emitStatus(fallback!, '        ', true));
    return lines;
}

/** Build the lines that construct a TypedDict literal of declared response headers. */
function buildHeadersDictLines(headers: OpResponseHeaderNode[], typeName: string, indent = '        ', varName = 'headers'): string[] {
    const lines: string[] = [];
    lines.push(`${indent}${varName}: ${typeName} = {}`);
    for (const h of headers) {
        const pyName = toPythonFieldName(h.name);
        lines.push(`${indent}if ${JSON.stringify(h.name.toLowerCase())} in _response_headers:`);
        lines.push(`${indent}    ${varName}[${JSON.stringify(pyName)}] = _response_headers[${JSON.stringify(h.name.toLowerCase())}]`);
    }
    return lines;
}

/**
 * Render `text` as indented docstring body lines, neutralizing anything that
 * could terminate the enclosing `"""` docstring early. `op.name` / descriptions
 * come from user `.ck` source and may contain `"""` runs or embedded newlines.
 * Each `"` is escaped to `\"` (inside a Python string `\"` cannot close a `"""`),
 * and a trailing backslash is guarded with a space so it can't escape the delimiter.
 */
function docstringLines(text: string, indent: string): string[] {
    return text.split('\n').map(line => {
        let safe = line.replace(/"/g, '\\"');
        if (/\\$/.test(safe)) safe += ' ';
        return `${indent}${safe}`;
    });
}

/** snake_case → PascalCase. */
function snakeToPascal(s: string): string {
    return s
        .split('_')
        .filter(Boolean)
        .map(p => p.charAt(0).toUpperCase() + p.slice(1))
        .join('');
}

// ─── URL building ─────────────────────────────────────────────────────────

/**
 * Placeholder names as the `.ck` grammar allows them: `identStart identPart*`, where `identPart`
 * admits `-` and `.` alongside the usual identifier characters. Matching only `[a-zA-Z_]\w*` left
 * `{payment-id}` untouched, so the braces travelled to the server verbatim.
 */
const PATH_PLACEHOLDER = /\{([a-zA-Z_$][a-zA-Z0-9_$.-]*)\}/g;

/**
 * Render a route path as the Python expression that produces the request URL.
 *
 * The placeholder in the path carries the name as written in the contract, while the method
 * signature carries its snake_cased form — so interpolating the raw name emits an f-string
 * referring to something nothing binds, and the method raises `NameError` when called. `params`
 * says where the value lives: spread across the signature, or behind a single `params` argument
 * when the route declares its params as a model.
 *
 * Values are percent-encoded, which the TypeScript SDK has always done via `encodeURIComponent`
 * and Python did not do at all. `safe=''` because a path segment must escape `/` too.
 */
function buildUrlExpression(path: string, params?: ParamSource): string {
    if (!PATH_PLACEHOLDER.test(path)) return `"${path}"`;
    PATH_PLACEHOLDER.lastIndex = 0;

    const interpolated = path.replace(PATH_PLACEHOLDER, (_m, name: string) => {
        const field = toPythonFieldName(name);
        const expr = params && params.kind !== 'params' ? `params.${field}` : field;
        return `{quote(str(${expr}), safe='')}`;
    });
    return `f"${interpolated}"`;
}

// ─── Parameter building ───────────────────────────────────────────────────

function buildMethodParams(route: OpRouteNode, op: OpOperationNode, modelsWithInput?: Set<string>): MethodParam[] {
    const params: MethodParam[] = [];

    // Path params
    if (route.params) {
        if (route.params.kind === 'params') {
            for (const p of route.params.nodes) {
                params.push({
                    name: toPythonFieldName(p.name),
                    type: renderPyType(p.type, modelsWithInput),
                    optional: false,
                    isModel: false,
                });
            }
        } else if (route.params.kind === 'ref') {
            const typeName = modelsWithInput?.has(route.params.name) ? `${route.params.name}Input` : route.params.name;
            params.push({ name: 'params', type: typeName, optional: false, isModel: true });
        } else {
            params.push({ name: 'params', type: renderPyType(route.params.node, modelsWithInput), optional: false, isModel: false });
        }
    }

    // Body — use the first declared MIME's body type as the parameter type.
    // Multi-MIME support in Python collapses to a single signature using the primary body.
    const primaryBody = op.request?.bodies[0];
    if (primaryBody) {
        const cat = classifyContentType(primaryBody.contentType);
        if (cat === 'multipart') {
            // httpx's `files=` takes a mapping of part name to content, and generates the
            // boundary from it. `bytes` could never have worked: it is the whole payload with no
            // boundary, and there is no way for the client to supply one.
            params.push({ name: 'body', type: 'dict', optional: false, isModel: false });
        } else if (cat === 'binary') {
            params.push({ name: 'body', type: 'bytes', optional: false, isModel: false });
        } else if (cat === 'text') {
            params.push({ name: 'body', type: 'str', optional: false, isModel: false });
        } else {
            const bodyType = renderInputPyType(primaryBody.bodyType, modelsWithInput);
            const isModel = isModelRef(primaryBody.bodyType, modelsWithInput);
            params.push({ name: 'body', type: bodyType, optional: false, isModel });
        }
    }

    // Query
    if (op.query) {
        const queryType = renderParamSourceType(op.query, modelsWithInput, true);
        params.push({ name: 'query', type: queryType, optional: true, isModel: false });
    }

    // Headers
    if (op.headers) {
        const headersType = renderParamSourceType(op.headers, modelsWithInput, true);
        params.push({ name: 'custom_headers', type: headersType, optional: true, isModel: false });
    }

    return params;
}

function renderParamSourceType(source: ParamSource, modelsWithInput?: Set<string>, forInput = false): string {
    if (source.kind === 'ref') {
        const typeName = forInput && modelsWithInput?.has(source.name) ? `${source.name}Input` : source.name;
        return typeName;
    }
    if (source.kind === 'params') {
        // const fields = source.nodes.map(p => {
        //     const pyName = toPythonFieldName(p.name);
        //     return `"${pyName}": ${renderPyType(p.type, modelsWithInput, forInput)}`;
        // });
        return `dict`; // simplified — inline dicts are hard to type concisely in Python signatures
    }
    return renderPyType(source.node, modelsWithInput, forInput);
}

function renderInputPyType(type: ContractTypeNode, modelsWithInput?: Set<string>): string {
    return renderPyType(type, modelsWithInput, true);
}

// ─── Model reference detection ────────────────────────────────────────────

function isModelRef(type: ContractTypeNode, modelsWithInput?: Set<string>): boolean {
    if (type.kind === 'ref') return /^[A-Z]/.test(type.name);
    if (type.kind === 'lazy') return isModelRef(type.inner, modelsWithInput);
    return false;
}

function isListModelRef(type: ContractTypeNode, modelsWithInput?: Set<string>): boolean {
    if (type.kind === 'array') return isModelRef(type.item, modelsWithInput);
    if (type.kind === 'lazy') return isListModelRef(type.inner, modelsWithInput);
    return false;
}

function getListItemType(type: ContractTypeNode, modelsWithInput?: Set<string>): string {
    if (type.kind === 'array') return renderPyType(type.item, modelsWithInput);
    return 'dict';
}

// ─── Referenced model collection ─────────────────────────────────────────

/**
 * Collect all model names and scalar sentinels referenced in public operations.
 * Sentinels: __datetime__, __date__, __time__, __decimal__, __uuid__, __any__
 */
function collectReferencedModels(root: OpRootNode, modelsWithInput?: Set<string>, includeInternal = false): Set<string> {
    const refs = new Set<string>();

    for (const route of root.routes) {
        for (const op of route.operations) {
            if (!includeInternal && resolveModifiers(route, op).includes('internal')) continue;

            if (route.params) collectParamSourceRefs(route.params, refs, modelsWithInput);
            if (op.request) {
                for (const body of op.request.bodies) collectTypeRefs(body.bodyType, refs, modelsWithInput, true);
            }
            for (const resp of op.responses) {
                for (const body of resp.bodies) collectTypeRefs(body.bodyType, refs, modelsWithInput, false);
            }
            if (op.query) collectParamSourceRefs(op.query, refs, modelsWithInput);
            if (op.headers) collectParamSourceRefs(op.headers, refs, modelsWithInput);
        }
    }

    return refs;
}

function collectParamSourceRefs(source: ParamSource, out: Set<string>, modelsWithInput?: Set<string>): void {
    if (source.kind === 'ref') {
        addModelRef(source.name, out, modelsWithInput);
    } else if (source.kind === 'params') {
        for (const p of source.nodes) collectTypeRefs(p.type, out, modelsWithInput);
    } else {
        collectTypeRefs(source.node, out, modelsWithInput);
    }
}

function addModelRef(name: string, out: Set<string>, modelsWithInput?: Set<string>): void {
    if (/^[A-Z]/.test(name)) {
        out.add(name);
        if (modelsWithInput?.has(name)) out.add(`${name}Input`);
    }
}

function collectTypeRefs(type: ContractTypeNode, out: Set<string>, modelsWithInput?: Set<string>, forInput = false): void {
    switch (type.kind) {
        case 'scalar':
            switch (type.name) {
                case 'date':
                    out.add('__date__');
                    break;
                case 'time':
                    out.add('__time__');
                    break;
                case 'datetime':
                    out.add('__datetime__');
                    break;
                case 'decimal':
                    out.add('__decimal__');
                    break;
                case 'uuid':
                    out.add('__uuid__');
                    break;
                case 'unknown':
                case 'json':
                case 'object':
                    out.add('__any__');
                    break;
            }
            break;
        case 'ref':
            if (forInput && modelsWithInput?.has(type.name)) {
                out.add(`${type.name}Input`);
            } else {
                addModelRef(type.name, out, modelsWithInput);
            }
            break;
        case 'array':
            collectTypeRefs(type.item, out, modelsWithInput, forInput);
            break;
        case 'tuple':
            type.items.forEach(t => collectTypeRefs(t, out, modelsWithInput, forInput));
            break;
        case 'record':
            collectTypeRefs(type.key, out, modelsWithInput, forInput);
            collectTypeRefs(type.value, out, modelsWithInput, forInput);
            break;
        case 'union':
            type.members.forEach(m => collectTypeRefs(m, out, modelsWithInput, forInput));
            break;
        case 'discriminatedUnion':
            type.members.forEach(m => collectTypeRefs(m, out, modelsWithInput, forInput));
            break;
        case 'intersection':
            out.add('__any__');
            break;
        case 'lazy':
            collectTypeRefs(type.inner, out, modelsWithInput, forInput);
            break;
        case 'inlineObject':
            out.add('__any__');
            break;
    }
}

// ─── Naming helpers ───────────────────────────────────────────────────────

function deriveBaseName(file: string): string {
    const base =
        file
            .split('/')
            .pop()
            ?.replace(/\.(op\.)?ck$/, '') ?? 'Resource';
    return base
        .split('.')
        .map(s => s.charAt(0).toUpperCase() + s.slice(1))
        .join('');
}

export function deriveClientClassName(file: string): string {
    return `${deriveBaseName(file)}Client`;
}

export function deriveClientModuleName(file: string): string {
    const base =
        file
            .split('/')
            .pop()
            ?.replace(/\.(op\.)?ck$/, '') ?? 'client';
    const clean = base.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase();
    return `_client_${clean}`;
}

export function deriveClientPropertyName(file: string): string {
    const base = deriveBaseName(file);
    return base.charAt(0).toLowerCase() + base.slice(1);
}

function deriveMethodName(op: OpOperationNode, route: OpRouteNode): string {
    if (op.sdk) return toSnakeCase(op.sdk);
    if (op.name) return toSnakeCase(op.name);
    return inferMethodName(op.method, route.path);
}

function inferMethodName(method: string, path: string): string {
    const segments = path.split('/').filter(s => s.length > 0);
    const parts: string[] = [method.toLowerCase()];

    for (const seg of segments) {
        if (seg.startsWith('{')) {
            const paramName = seg.slice(1, -1);
            parts.push('by_' + toSnakeCase(paramName));
        } else {
            parts.push(toSnakeCase(seg.replace(/[.-]/g, '_')));
        }
    }

    return parts.join('_').replace(/_+/g, '_');
}

function toSnakeCase(s: string): string {
    return s
        .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
        .replace(/[^a-zA-Z0-9]/g, '_')
        .toLowerCase()
        .replace(/_+/g, '_')
        .replace(/^_|_$/g, '');
}

// ─── Shared base client content ───────────────────────────────────────────

export const BASE_CLIENT_PY = `# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.
from __future__ import annotations

import httpx
from typing import Any


class SdkError(Exception):
    def __init__(self, status: int, status_text: str, body: Any):
        super().__init__(f"{status} {status_text}")
        self.status = status
        self.status_text = status_text
        self.body = body


class BaseClient:
    def __init__(self, base_url: str, headers: dict[str, str] | None = None):
        self._base_url = base_url.rstrip("/")
        self._headers = headers or {}
        self._http = httpx.AsyncClient()
        self._last_status = 0
        self._last_content_type = ""

    async def _fetch(
        self,
        path: str,
        *,
        method: str,
        body: Any = None,
        params: dict | None = None,
        extra_headers: dict | None = None,
        content_type: str | None = None,
        body_kind: str = "json",
        response_kind: str = "json",
        expect_statuses: tuple[int, ...] = (),
    ) -> Any:
        result, _ = await self._fetch_with_headers(
            path,
            method=method,
            body=body,
            params=params,
            extra_headers=extra_headers,
            content_type=content_type,
            body_kind=body_kind,
            response_kind=response_kind,
            expect_statuses=expect_statuses,
        )
        return result

    async def _fetch_full(
        self,
        path: str,
        *,
        method: str,
        body: Any = None,
        params: dict | None = None,
        extra_headers: dict | None = None,
        content_type: str | None = None,
        body_kind: str = "json",
        response_kind: str = "json",
        expect_statuses: tuple[int, ...] = (),
    ) -> tuple[int, str, Any, dict[str, str]]:
        """Like _fetch_with_headers, but also reports the status and content type.

        Used by operations that declare more than one status, or more than one mime for a
        status, where the caller cannot know which it got without being told.
        """
        result, headers = await self._fetch_with_headers(
            path,
            method=method,
            body=body,
            params=params,
            extra_headers=extra_headers,
            content_type=content_type,
            body_kind=body_kind,
            response_kind=response_kind,
            expect_statuses=expect_statuses,
        )
        return self._last_status, self._last_content_type, result, headers

    async def _fetch_with_headers(
        self,
        path: str,
        *,
        method: str,
        body: Any = None,
        params: dict | None = None,
        extra_headers: dict | None = None,
        content_type: str | None = None,
        body_kind: str = "json",
        response_kind: str = "json",
        expect_statuses: tuple[int, ...] = (),
    ) -> tuple[Any, dict[str, str]]:
        headers = {**self._headers, **(extra_headers or {})}
        # multipart is the exception: httpx has to generate the boundary itself, and it can only
        # do that if it owns the Content-Type header. Setting it here would produce a header with
        # no boundary parameter, which no server can parse.
        if body is not None and body_kind != "multipart":
            headers["Content-Type"] = content_type or "application/json"
        # body_kind controls how httpx serializes the request body:
        #   "json"      — a JSON-serializable object, sent via httpx's json= kwarg
        #   "form"      — a mapping sent as application/x-www-form-urlencoded via data=
        #   "multipart" — a mapping of file parts sent via files=, boundary generated by httpx
        #   "text"/"binary" — a raw str/bytes payload, sent via content= unchanged
        request_kwargs: dict[str, Any] = {"method": method, "url": f"{self._base_url}{path}", "params": params, "headers": headers}
        if body is not None:
            if body_kind == "json":
                request_kwargs["json"] = body
            elif body_kind == "form":
                request_kwargs["data"] = body
            elif body_kind == "multipart":
                request_kwargs["files"] = body
            else:
                request_kwargs["content"] = body
        response = await self._http.request(**request_kwargs)
        # expect_statuses carries the codes this operation declares as values rather than
        # errors — a 304 from conditional-GET middleware, or an error status the service
        # returns deliberately. Anything else outside 2xx still raises.
        if not response.is_success and response.status_code not in expect_statuses:
            try:
                error_body = response.json()
            except Exception:
                error_body = response.text
            raise SdkError(response.status_code, response.reason_phrase, error_body)
        # HTTP headers are case-insensitive — normalize to lowercase keys for stable lookup.
        response_headers = {k.lower(): v for k, v in response.headers.items()}
        self._last_status = response.status_code
        self._last_content_type = response.headers.get("content-type", "").split(";")[0].strip()
        if response.status_code == 204 or not response.content:
            return None, response_headers
        # "auto" is for a status declaring several mimes that do not read the same way: the
        # response itself is the only thing that knows which one came back.
        kind = response_kind
        if kind == "auto":
            ct = self._last_content_type
            if ct.startswith("text/"):
                kind = "text"
            elif ct == "application/json" or ct.endswith("+json"):
                kind = "json"
            else:
                kind = "binary"
        if kind == "text":
            return response.text, response_headers
        if kind == "binary":
            return response.content, response_headers
        return response.json(), response_headers
`;
