// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.
package com.example.sdk

import com.example.sdk.clients.BillingClient
import com.example.sdk.clients.HyphenatedClient
import com.example.sdk.clients.SimpleClient
import com.example.sdk.runtime.SdkConfig
import com.example.sdk.runtime.SdkHttp

/**
 * Entry point to the generated SDK.
 *
 * Holds one [SdkHttp], shared by every client, so the SDK keeps a single connection pool.
 * Closing it closes the underlying Ktor client, unless you supplied your own.
 */
class KitchenSink(config: SdkConfig) : AutoCloseable {
    val http: SdkHttp = SdkHttp(config)
    val billing: BillingClient = BillingClient(http)
    val hyphenated: HyphenatedClient = HyphenatedClient(http)
    val simple: SimpleClient = SimpleClient(http)

    override fun close() {
        http.close()
    }
}
