import { describe, expect, it } from 'vitest';
import { buildModelIndex } from '@contractkit/core';
import { generateSwiftModels, resolveModelsWithInput } from '../src/codegen-models.js';
import { collectHoistedTypes } from '../src/hoist.js';
import { collectBoxedFields } from '../src/recursion.js';
import {
    arrayType,
    contractRoot,
    enumType,
    field,
    inlineObjectType,
    lazyType,
    literalType,
    model,
    recordType,
    refType,
    scalarType,
    tupleType,
    unionType,
} from './helpers.js';

/**
 * Run the same passes the plugin runs: name the anonymous types, find the fields that have to be
 * boxed, then render. Tests that skip them would assert a fallback nothing in the real pipeline
 * produces.
 */
function gen(models: Parameters<typeof contractRoot>[0], opts: Partial<Parameters<typeof generateSwiftModels>[1]> = {}): string {
    const root = contractRoot(models);
    const modelIndex = buildModelIndex(models);
    const modelsWithInput = resolveModelsWithInput(models, opts.modelsWithInput);
    const hoisted = collectHoistedTypes([root], { modelIndex, modelsWithInput, warn: opts.warn ? m => opts.warn!(m) : undefined });
    const boxed = collectBoxedFields([root], { modelIndex, hoisted });
    return generateSwiftModels(root, { modelIndex, hoisted, boxed, ...opts, modelsWithInput });
}

// ─── Scalars ───────────────────────────────────────────────────────────────

describe('scalar mapping', () => {
    const cases: [Parameters<typeof scalarType>[0], string][] = [
        ['string', 'String'],
        ['email', 'String'],
        ['url', 'String'],
        ['interval', 'String'],
        ['number', 'Double'],
        ['int', 'Int'],
        ['bigint', 'BigIntValue'],
        ['decimal', 'DecimalValue'],
        ['boolean', 'Bool'],
        ['date', 'LocalDate'],
        ['time', 'LocalTime'],
        ['datetime', 'Date'],
        ['duration', 'IsoDuration'],
        ['uuid', 'UUID'],
        ['binary', 'Data'],
        ['unknown', 'JSONValue'],
        ['json', 'JSONValue'],
        ['object', 'JSONValue'],
        ['null', 'JSONValue'],
    ];

    for (const [scalar, swift] of cases) {
        it(`maps ${scalar} to ${swift}`, () => {
            expect(gen([model('M', [field('v', scalarType(scalar))])])).toContain(`public var v: ${swift}`);
        });
    }

    it('throws on an unmapped scalar rather than emitting Swift that will not compile', () => {
        expect(() => gen([model('M', [field('v', { kind: 'scalar', name: 'quaternion' } as never)])])).toThrow(/unmapped scalar 'quaternion'/);
    });
});

describe('file header', () => {
    it('carries the generated-file banner and imports Foundation', () => {
        const out = gen([model('M', [field('v', scalarType('string'))])]);
        expect(out.startsWith('// Auto-generated by @contractkit/plugin-swift. Do not edit manually.\nimport Foundation\n')).toBe(true);
    });

    it('imports nothing else: one module means a cross-file reference resolves by name', () => {
        expect(gen([model('M', [field('v', refType('Payment'))])]).match(/^import /gm)).toEqual(['import ']);
    });
});

// ─── Composite types ───────────────────────────────────────────────────────

describe('composite types', () => {
    it('maps array and record', () => {
        const out = gen([
            model('M', [field('items', arrayType(refType('Payment'))), field('meta', recordType(scalarType('string'), scalarType('string')))]),
            model('Payment', [field('id', scalarType('string'))]),
        ]);
        expect(out).toContain('public var items: [Payment]');
        expect(out).toContain('public var meta: [String: String]');
    });

    it('warns and falls back to a string key for a non-string record key', () => {
        const warnings: string[] = [];
        gen([model('M', [field('meta', recordType(scalarType('int'), scalarType('string')))])], { warn: m => warnings.push(m) });
        expect(warnings.join('\n')).toMatch(/record key of type 'Int'/);
    });

    it('renders a tuple as a struct that travels as a JSON array', () => {
        const out = gen([model('M', [field('range', tupleType(scalarType('int'), scalarType('string')))])]);
        expect(out).toContain('public struct MRange: Codable, Equatable, Sendable {');
        expect(out).toContain('public var _0: Int');
        expect(out).toContain('public var _1: String');
        expect(out).toContain('var container = try decoder.unkeyedContainer()');
        expect(out).toContain('if let count = container.count, count != 2 {');
    });

    it('renders a model ref by name, and follows lazy() through to it', () => {
        const out = gen([
            model('M', [field('a', refType('P')), field('b', lazyType(refType('P')))]),
            model('P', [field('id', scalarType('string'))]),
        ]);
        expect(out).toContain('public var a: P');
        expect(out).toContain('public var b: P');
    });
});

// ─── Struct shape ──────────────────────────────────────────────────────────

describe('struct shape', () => {
    const out = gen([model('M', [field('id', scalarType('uuid'))])]);

    it('is a public Codable value type with a public memberwise init', () => {
        expect(out).toContain('public struct M: Codable, Equatable, Sendable {');
        // The synthesized memberwise init is internal, so it is spelled out.
        expect(out).toContain('public init(id: UUID) {');
    });

    it('spells out CodingKeys, so a re-cased or escaped property never drifts from the wire', () => {
        expect(out).toContain('private enum CodingKeys: String, CodingKey {');
        expect(out).toContain('case id = "id"');
    });

    it('spells out both coding halves rather than relying on the synthesized ones', () => {
        expect(out).toContain('public init(from decoder: Decoder) throws {');
        expect(out).toContain('public func encode(to encoder: Encoder) throws {');
    });

    it('gives a fieldless contract a type that still decodes', () => {
        const empty = gen([model('Empty', [])]);
        expect(empty).toContain('public struct Empty: Codable, Equatable, Sendable {');
        expect(empty).toContain('public init() {}');
        expect(empty).toContain('_ = try decoder.container(keyedBy: DynamicCodingKey.self)');
    });

    it('escapes a property that lands on a reserved word, keeping the wire name intact', () => {
        const out = gen([model('M', [field('class', scalarType('string'))])]);
        expect(out).toContain('public var `class`: String');
        expect(out).toContain('case `class` = "class"');
    });
});

describe('field shapes', () => {
    it('omits an optional field, on the way in and on the way out', () => {
        const out = gen([model('M', [field('note', scalarType('string'), { optional: true })])]);
        expect(out).toContain('public var note: String?');
        expect(out).toContain('public init(note: String? = nil)');
        expect(out).toContain('try container.decodeIfPresent(String.self, forKey: .note)');
        expect(out).toContain('try container.encodeIfPresent(self.note, forKey: .note)');
    });

    it('writes a required nullable field as an explicit null, and requires the key on the way in', () => {
        const out = gen([model('M', [field('note', scalarType('string'), { nullable: true })])]);
        expect(out).toContain('public var note: String?');
        // No `= nil` default: the caller has to say which of the two it means.
        expect(out).toContain('public init(note: String?) {');
        expect(out).toContain('try container.decode(String?.self, forKey: .note)');
        expect(out).toContain('try container.encode(self.note, forKey: .note)');
    });

    it('fills a default in when the wire omits it, and always sends it', () => {
        const out = gen([model('M', [field('limit', scalarType('int'), { optional: true, default: 20 })])]);
        expect(out).toContain('public init(limit: Int = 20)');
        expect(out).toContain('try container.decodeIfPresent(Int.self, forKey: .limit) ?? 20');
        expect(out).toContain('try container.encode(self.limit, forKey: .limit)');
    });

    it('renders a default of each scalar shape in the field type, not as its wire spelling', () => {
        const out = gen([
            model('M', [
                field('a', scalarType('number'), { optional: true, default: 2 }),
                field('b', scalarType('decimal'), { optional: true, default: '1.5' }),
                field('c', scalarType('boolean'), { optional: true, default: true }),
                field('d', enumType('pending', 'done'), { optional: true, default: 'pending' }),
            ]),
        ]);
        expect(out).toContain('a: Double = 2.0');
        expect(out).toContain('b: DecimalValue = DecimalValue("1.5")');
        expect(out).toContain('c: Bool = true');
        expect(out).toContain('d: MD = .pending');
    });

    it('renders a default written against a named enum contract as the enum case', () => {
        const out = gen([
            model('Rating', [], { type: enumType('good', 'neutral') }),
            model('M', [field('r', refType('Rating'), { optional: true, default: 'neutral' })]),
        ]);
        expect(out).toContain('r: Rating = .neutral');
    });

    it('validates a literal field on the way in and sends it on the way out', () => {
        const out = gen([model('Card', [field('kind', literalType('card'))])]);
        expect(out).toContain('public init(kind: String = "card")');
        expect(out).toContain('guard self.kind == "card" else {');
        expect(out).toContain('throw DecodingError.dataCorruptedError(forKey: .kind, in: container, debugDescription: "Expected \\"card\\"")');
    });
});

/** The body of one generated declaration, so an assertion cannot run on into the next one. */
function structBody(source: string, name: string): string {
    const start = source.indexOf(`public struct ${name}: `);
    expect(start).toBeGreaterThanOrEqual(0);
    const end = source.indexOf('\n}\n', start);
    return source.slice(start, end === -1 ? undefined : end);
}

// ─── Inheritance and variants ──────────────────────────────────────────────

describe('inheritance', () => {
    it('flattens bases, since a Swift struct cannot extend another', () => {
        const out = gen([
            model('Base', [field('id', scalarType('uuid'))]),
            model('Child', [field('name', scalarType('string'))], { bases: ['Base'] }),
        ]);
        expect(out).toContain('public struct Child: Codable, Equatable, Sendable {');
        expect(out).toMatch(/struct Child[\s\S]*public var id: UUID/);
        expect(out).toMatch(/struct Child[\s\S]*public var name: String/);
    });

    it('warns when a base is missing rather than silently dropping its fields', () => {
        const warnings: string[] = [];
        gen([model('Child', [field('name', scalarType('string'))], { bases: ['Nope'] })], { warn: m => warnings.push(m) });
        expect(warnings.join('\n')).toMatch(/extends 'Nope', which is not defined/);
    });
});

describe('read and input variants', () => {
    it('splits a contract with visibility, dropping the field each direction must not carry', () => {
        const out = gen([
            model('Cred', [
                field('id', scalarType('uuid'), { visibility: 'readonly' }),
                field('secret', scalarType('string'), { visibility: 'writeonly' }),
            ]),
        ]);
        const read = structBody(out, 'Cred');
        const input = structBody(out, 'CredInput');
        // A response never carries the writeonly field, and a request never asks for the readonly one.
        expect(read).toContain('public var id: UUID');
        expect(read).not.toContain('secret');
        expect(input).toContain('public var secret: String');
        expect(input).not.toContain('id');
    });

    it('gives an enum an Input alias rather than a second declaration', () => {
        const out = gen([model('Status', [], { type: enumType('a', 'b') })], { modelsWithInput: new Set(['Status']) });
        expect(out).toContain('public typealias StatusInput = Status');
    });
});

// ─── Enums, aliases, unions ────────────────────────────────────────────────

describe('enums', () => {
    it('renders a String enum whose cases carry the wire values', () => {
        const out = gen([model('S', [], { type: enumType('pending', 'on hold') })]);
        expect(out).toContain('public enum S: String, Codable, CaseIterable, Sendable {');
        expect(out).toContain('case pending = "pending"');
        expect(out).toContain('case onHold = "on hold"');
    });

    it('suffixes cases that collide after camelCasing', () => {
        const out = gen([model('S', [], { type: enumType('a-b', 'aB') })]);
        expect(out).toContain('case aB = "a-b"');
        expect(out).toContain('case aB2 = "aB"');
    });

    it('escapes a case that lands on a reserved word', () => {
        expect(gen([model('S', [], { type: enumType('default') })])).toContain('case `default` = "default"');
    });
});

describe('aliases', () => {
    it('renders a scalar or collection alias as a typealias', () => {
        expect(gen([model('Ids', [], { type: arrayType(scalarType('uuid')) })])).toContain('public typealias Ids = [UUID]');
    });

    it('renders an inline object alias as a struct rather than an opaque JSON value', () => {
        const out = gen([model('Meta', [], { type: inlineObjectType([field('k', scalarType('string'))]) })]);
        expect(out).toContain('public struct Meta: Codable, Equatable, Sendable {');
        expect(out).toContain('public var k: String');
    });
});

describe('unions', () => {
    it('renders union(T, null) as an Optional, with no enum at all', () => {
        const out = gen([model('M', [field('v', unionType(refType('P'), scalarType('null')))]), model('P', [field('id', scalarType('string'))])]);
        expect(out).toContain('public var v: P?');
        expect(out).not.toContain('enum MV');
    });

    it('renders a plain union as an indirect enum that tries members in declaration order', () => {
        const out = gen([model('M', [field('v', unionType(refType('P'), scalarType('string')))]), model('P', [field('id', scalarType('string'))])]);
        expect(out).toContain('public indirect enum MV: Codable, Equatable, Sendable {');
        expect(out).toContain('case payment(P)'.replace('payment', 'p'));
        expect(out).toContain('case string(String)');
        const decodeOrder = out.indexOf('container.decode(P.self)') < out.indexOf('container.decode(String.self)');
        expect(decodeOrder).toBe(true);
        expect(out).toContain('No MV member matched the payload');
    });

    it('renders a discriminated union that dispatches on the tag and delegates to the member', () => {
        const out = gen([
            model('Card', [field('kind', literalType('card')), field('last4', scalarType('string'))]),
            model('Bank', [field('kind', literalType('bank'))]),
            model('PaymentMethod', [], { type: { kind: 'discriminatedUnion', discriminator: 'kind', members: [refType('Card'), refType('Bank')] } }),
        ]);
        expect(out).toContain('public indirect enum PaymentMethod: Codable, Equatable, Sendable {');
        expect(out).toContain('let container = try decoder.container(keyedBy: DynamicCodingKey.self)');
        expect(out).toContain('let tag = try container.decode(JSONValue.self, forKey: DynamicCodingKey(stringValue: "kind"))');
        expect(out).toContain('case .string("card"):');
        expect(out).toContain('self = .card(try Card(from: decoder))');
        // Encoding delegates, so the tag stays a real property and one contract can join several unions.
        expect(out).toContain('try value.encode(to: encoder)');
    });

    it('falls back to a JSON value when a discriminator is not a literal', () => {
        const warnings: string[] = [];
        const out = gen(
            [
                model('Card', [field('kind', enumType('card'))]),
                model('M', [field('pm', { kind: 'discriminatedUnion', discriminator: 'kind', members: [refType('Card')] })]),
            ],
            { warn: m => warnings.push(m) },
        );
        expect(out).toContain('public var pm: JSONValue');
        expect(warnings.join('\n')).toMatch(/not a literal/);
    });
});

// ─── Key casing ────────────────────────────────────────────────────────────

describe('wire key casing', () => {
    it('renames keys without renaming the properties', () => {
        const out = gen([model('Token', [field('accessToken', scalarType('string'))], { outputCase: 'snake' })]);
        expect(out).toContain('public var accessToken: String');
        expect(out).toContain('case accessToken = "access_token"');
    });

    it('gives each direction its own keys when a model carries both and is not split', () => {
        const out = gen([model('T', [field('accessToken', scalarType('string'))], { inputCase: 'pascal', outputCase: 'snake' })]);
        expect(out).toContain('private enum CodingKeys: String, CodingKey {');
        expect(out).toContain('case accessToken = "access_token"');
        expect(out).toContain('private enum EncodingKeys: String, CodingKey {');
        expect(out).toContain('case accessToken = "AccessToken"');
        expect(out).toContain('var container = encoder.container(keyedBy: EncodingKeys.self)');
    });

    it('gives a split model one casing each way', () => {
        const out = gen([
            model(
                'T',
                [
                    field('accessToken', scalarType('string'), { visibility: 'readonly' }),
                    field('secretKey', scalarType('string'), { visibility: 'writeonly' }),
                ],
                { inputCase: 'pascal', outputCase: 'snake' },
            ),
        ]);
        expect(out).toMatch(/struct T:[\s\S]*case accessToken = "access_token"/);
        expect(out).toMatch(/struct TInput[\s\S]*case secretKey = "SecretKey"/);
    });

    it('warns about an anonymous object under a renamed contract, whose keys it cannot reach', () => {
        const warnings: string[] = [];
        gen([model('T', [field('meta', inlineObjectType([field('someKey', scalarType('string'))]))], { outputCase: 'snake' })], {
            warn: m => warnings.push(m),
        });
        expect(warnings.join('\n')).toMatch(/holds an anonymous object/);
    });
});

// ─── Recursion ─────────────────────────────────────────────────────────────

describe('recursive models', () => {
    const out = gen([model('Node', [field('parent', lazyType(refType('Node')), { optional: true }), field('name', scalarType('string'))])]);

    it('stores a self-reference in a box, since a struct cannot contain itself', () => {
        expect(out).toContain('private var _parent: Indirect<Node>?');
    });

    it('keeps the public property spelled as the contract declares it', () => {
        expect(out).toContain('public var parent: Node? {');
        expect(out).toContain('get { _parent?.value }');
        expect(out).toContain('set { _parent = newValue.map { Indirect($0) } }');
    });

    it('takes and codes the unboxed value, so the box never reaches the caller or the wire', () => {
        expect(out).toContain('public init(parent: Node? = nil, name: String)');
        expect(out).toContain('self._parent = parent.map { Indirect($0) }');
        expect(out).toContain('case _parent = "parent"');
        expect(out).toContain('try container.decodeIfPresent(Indirect<Node>.self, forKey: ._parent)');
    });

    it('leaves a reference through an array alone, which is already heap-allocated', () => {
        const arrayOut = gen([model('Node', [field('children', arrayType(refType('Node')))])]);
        expect(arrayOut).toContain('public var children: [Node]');
        expect(arrayOut).not.toContain('Indirect');
    });
});
