// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Example.Sdk.Models;

/// <summary>A customer payment</summary>
public sealed record Payment
{
    [JsonPropertyName("id")]
    public required Guid Id { get; init; }

    [JsonPropertyName("amount")]
    public required double Amount { get; init; }

    [JsonPropertyName("unitPrice")]
    public required decimal UnitPrice { get; init; }

    [JsonPropertyName("quantity")]
    public required BigInteger Quantity { get; init; }

    [JsonPropertyName("createdAt")]
    public required DateTimeOffset CreatedAt { get; init; }

    [JsonPropertyName("processingTime")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public TimeSpan? ProcessingTime { get; init; }

    [JsonPropertyName("status")]
    public PaymentStatus Status { get; init; } = PaymentStatus.Pending;
}

/// <summary>A customer payment</summary>
public sealed record PaymentInput
{
    [JsonPropertyName("amount")]
    public required double Amount { get; init; }

    [JsonPropertyName("unitPrice")]
    public required decimal UnitPrice { get; init; }

    [JsonPropertyName("quantity")]
    public required BigInteger Quantity { get; init; }

    [JsonPropertyName("createdAt")]
    public required DateTimeOffset CreatedAt { get; init; }

    [JsonPropertyName("processingTime")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public TimeSpan? ProcessingTime { get; init; }

    [JsonPropertyName("status")]
    public PaymentStatus Status { get; init; } = PaymentStatus.Pending;
}

/// <summary>A stored credential — has a writeonly child, so its Base schema is read</summary>
public sealed record Credential
{
    [JsonPropertyName("id")]
    public required Guid Id { get; init; }
}

/// <summary>A stored credential — has a writeonly child, so its Base schema is read</summary>
public sealed record CredentialInput
{
    [JsonPropertyName("secret")]
    public required string Secret { get; init; }
}

/// <summary>A writeonly model nothing extends — its Base schema has no reader</summary>
public sealed record Session
{
    [JsonPropertyName("id")]
    public required string Id { get; init; }
}

/// <summary>A writeonly model nothing extends — its Base schema has no reader</summary>
public sealed record SessionInput
{
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    [JsonPropertyName("refreshToken")]
    public required string RefreshToken { get; init; }
}

/// <summary>Path params declared as a model, referenced via `params: PaymentRef`</summary>
public sealed record PaymentRef
{
    [JsonPropertyName("paymentId")]
    public required Guid PaymentId { get; init; }
}

public sealed record UpdatePaymentForm
{
    [JsonPropertyName("note")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Note { get; init; }
}

public sealed record UploadReceiptForm
{
    [JsonPropertyName("caption")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Caption { get; init; }

    [JsonPropertyName("file")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public byte[]? File { get; init; }
}

/// <summary>Query params declared as a model, referenced via `query: PaymentFilter`</summary>
public sealed record PaymentFilter
{
    [JsonPropertyName("status")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public PaymentFilterStatus? Status { get; init; }

    [JsonPropertyName("since")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateTimeOffset? Since { get; init; }

    [JsonPropertyName("ids")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<Guid>? Ids { get; init; }
}

/// <summary>Request headers declared as a model. Header names are case-insensitive, so any casing of `xCorrelationId` matches.</summary>
public sealed record TenantHeaders
{
    [JsonPropertyName("x-tenant")]
    public required string XTenant { get; init; }

    [JsonPropertyName("xCorrelationId")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? XCorrelationId { get; init; }
}

/// <summary>
/// Query params and headers declared as format() models. Each schema is a pipe with no `.strict()` of
/// its own, so the router applies the block's object mode to the object inside it. A query array is
/// split on commas there too, read off the object's shape under its snake_case key.
/// </summary>
public sealed record SnakeFilter
{
    [JsonPropertyName("from_date")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateOnly? FromDate { get; init; }

    [JsonPropertyName("tag_ids")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<Guid>? TagIds { get; init; }
}

public sealed record SnakeHeaders
{
    [JsonPropertyName("tenant_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? TenantId { get; init; }
}

/// <summary>
/// A format() member of an intersection has no `.extend()` or `.shape`, being a pipe. The router and the
/// schemas build the object from the member's own object (`SnakeFilter.in`) and end in one transform
/// that renames the member's keys through its `.out`, passing every other key through.
/// </summary>
public sealed record PaymentScope
{
    [JsonPropertyName("region")]
    public required string Region { get; init; }
}

/// <summary>Extends a writeonly base and is itself writeonly</summary>
public sealed record AdminCredential
{
    [JsonPropertyName("id")]
    public required Guid Id { get; init; }

    [JsonPropertyName("scope")]
    public required string Scope { get; init; }
}

/// <summary>Extends a writeonly base and is itself writeonly</summary>
public sealed record AdminCredentialInput
{
    [JsonPropertyName("secret")]
    public required string Secret { get; init; }

    [JsonPropertyName("scope")]
    public required string Scope { get; init; }

    [JsonPropertyName("token")]
    public required string Token { get; init; }
}

/// <summary>A field typed as one</summary>
public sealed record SavedSearch
{
    [JsonPropertyName("label")]
    public required string Label { get; init; }

    [JsonPropertyName("filter")]
    public required SavedSearchFilter Filter { get; init; }
}

/// <summary>An alias of such an intersection, which is a pipe itself</summary>
public sealed record ScopedFilter
{
    [JsonPropertyName("fromDate")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateOnly? FromDate { get; init; }

    [JsonPropertyName("tagIds")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<Guid>? TagIds { get; init; }

    [JsonPropertyName("region")]
    public required string Region { get; init; }
}

[JsonConverter(typeof(JsonStringEnumConverter<PaymentStatus>))]
public enum PaymentStatus
{
    [JsonStringEnumMemberName("pending")]
    Pending,

    [JsonStringEnumMemberName("completed")]
    Completed,

    [JsonStringEnumMemberName("failed")]
    Failed,
}

[JsonConverter(typeof(JsonStringEnumConverter<PaymentFilterStatus>))]
public enum PaymentFilterStatus
{
    [JsonStringEnumMemberName("pending")]
    Pending,

    [JsonStringEnumMemberName("completed")]
    Completed,

    [JsonStringEnumMemberName("failed")]
    Failed,
}

public sealed record SavedSearchFilter
{
    [JsonPropertyName("fromDate")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateOnly? FromDate { get; init; }

    [JsonPropertyName("tagIds")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<Guid>? TagIds { get; init; }

    [JsonPropertyName("q")]
    public required string Q { get; init; }
}
