// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Example.Sdk.Models;

/// <summary>A customer payment</summary>
public sealed record Payment
{
    [JsonPropertyName("id")]
    public required Guid Id { get; init; }

    [JsonPropertyName("amount")]
    public required double Amount { get; init; }

    [JsonPropertyName("unitPrice")]
    public required decimal UnitPrice { get; init; }

    [JsonPropertyName("quantity")]
    public required BigInteger Quantity { get; init; }

    [JsonPropertyName("createdAt")]
    public required DateTimeOffset CreatedAt { get; init; }

    [JsonPropertyName("processingTime")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public TimeSpan? ProcessingTime { get; init; }

    [JsonPropertyName("status")]
    public PaymentStatus Status { get; init; } = PaymentStatus.Pending;
}

/// <summary>A customer payment</summary>
public sealed record PaymentInput
{
    [JsonPropertyName("amount")]
    public required double Amount { get; init; }

    [JsonPropertyName("unitPrice")]
    public required decimal UnitPrice { get; init; }

    [JsonPropertyName("quantity")]
    public required BigInteger Quantity { get; init; }

    [JsonPropertyName("createdAt")]
    public required DateTimeOffset CreatedAt { get; init; }

    [JsonPropertyName("processingTime")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public TimeSpan? ProcessingTime { get; init; }

    [JsonPropertyName("status")]
    public PaymentStatus Status { get; init; } = PaymentStatus.Pending;
}

/// <summary>A stored credential — has a writeonly child, so its Base schema is read</summary>
public sealed record Credential
{
    [JsonPropertyName("id")]
    public required Guid Id { get; init; }
}

/// <summary>A stored credential — has a writeonly child, so its Base schema is read</summary>
public sealed record CredentialInput
{
    [JsonPropertyName("secret")]
    public required string Secret { get; init; }
}

/// <summary>A writeonly model nothing extends — its Base schema has no reader</summary>
public sealed record Session
{
    [JsonPropertyName("id")]
    public required string Id { get; init; }
}

/// <summary>A writeonly model nothing extends — its Base schema has no reader</summary>
public sealed record SessionInput
{
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    [JsonPropertyName("refreshToken")]
    public required string RefreshToken { get; init; }
}

/// <summary>Path params declared as a model, referenced via `params: PaymentRef`</summary>
public sealed record PaymentRef
{
    [JsonPropertyName("paymentId")]
    public required Guid PaymentId { get; init; }
}

public sealed record UpdatePaymentForm
{
    [JsonPropertyName("note")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Note { get; init; }
}

public sealed record UploadReceiptForm
{
    [JsonPropertyName("caption")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Caption { get; init; }

    [JsonPropertyName("file")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public byte[]? File { get; init; }
}

/// <summary>Extends a writeonly base and is itself writeonly</summary>
public sealed record AdminCredential
{
    [JsonPropertyName("id")]
    public required Guid Id { get; init; }

    [JsonPropertyName("scope")]
    public required string Scope { get; init; }
}

/// <summary>Extends a writeonly base and is itself writeonly</summary>
public sealed record AdminCredentialInput
{
    [JsonPropertyName("secret")]
    public required string Secret { get; init; }

    [JsonPropertyName("scope")]
    public required string Scope { get; init; }

    [JsonPropertyName("token")]
    public required string Token { get; init; }
}

[JsonConverter(typeof(JsonStringEnumConverter<PaymentStatus>))]
public enum PaymentStatus
{
    [JsonStringEnumMemberName("pending")]
    Pending,

    [JsonStringEnumMemberName("completed")]
    Completed,

    [JsonStringEnumMemberName("failed")]
    Failed,
}
