// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Example.Sdk.Models;

/// <summary>A named enum, so a field default has to resolve to a member rather than its wire spelling</summary>
[JsonConverter(typeof(JsonStringEnumConverter<Rating>))]
public enum Rating
{
    [JsonStringEnumMemberName("good")]
    Good,

    [JsonStringEnumMemberName("neutral")]
    Neutral,

    [JsonStringEnumMemberName("bad")]
    Bad,
}

public sealed record Card : Instrument
{
    [JsonPropertyName("kind")]
    public string Kind { get; init; } = "card";

    [JsonPropertyName("last4")]
    public required string Last4 { get; init; }
}

public sealed record Bank : Instrument
{
    [JsonPropertyName("kind")]
    public string Kind { get; init; } = "bank";

    [JsonPropertyName("iban")]
    public required string Iban { get; init; }
}

/// <summary>Decodes snake_case keys and encodes PascalCase ones</summary>
public sealed record Token
{
    [JsonPropertyName("access_token")]
    public required string AccessToken { get; init; }

    [JsonPropertyName("expires_in")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? ExpiresIn { get; init; } = 3600L;
}

public sealed record Owned
{
    [JsonPropertyName("id")]
    public required Guid Id { get; init; }
}

public sealed record OwnedInput
{
    [JsonPropertyName("secret")]
    public required string Secret { get; init; }
}

public sealed record Named
{
    [JsonPropertyName("name")]
    public required string Name { get; init; }
}

public sealed record Stamp
{
    [JsonPropertyName("stampedBy")]
    public required string StampedBy { get; init; }

    [JsonPropertyName("stampedAt")]
    public required DateTimeOffset StampedAt { get; init; }
}

/// <summary>format() on a contract split for readonly and writeonly fields, applied to both of its schemas</summary>
public sealed record Ledger
{
    [JsonPropertyName("Id")]
    public required Guid Id { get; init; }

    [JsonPropertyName("PostedAt")]
    public required DateTimeOffset PostedAt { get; init; }
}

/// <summary>format() on a contract split for readonly and writeonly fields, applied to both of its schemas</summary>
public sealed record LedgerInput
{
    [JsonPropertyName("entry_code")]
    public required string EntryCode { get; init; }

    [JsonPropertyName("posted_at")]
    public required DateTimeOffset PostedAt { get; init; }
}

/// <summary>A plain base under format(), which the schema inlines rather than extends</summary>
public sealed record Stamped
{
    [JsonPropertyName("StampedBy")]
    public required string StampedBy { get; init; }

    [JsonPropertyName("StampedAt")]
    public required DateTimeOffset StampedAt { get; init; }

    [JsonPropertyName("StampNote")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? StampNote { get; init; }
}

/// <summary>Two flattened bases, split into a read and an input shape</summary>
public sealed record Shared
{
    [JsonPropertyName("id")]
    public required Guid Id { get; init; }

    [JsonPropertyName("name")]
    public required string Name { get; init; }

    [JsonPropertyName("label")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Label { get; init; } = "x";

    [JsonPropertyName("instrument")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Instrument? Instrument { get; init; }
}

/// <summary>Two flattened bases, split into a read and an input shape</summary>
public sealed record SharedInput
{
    [JsonPropertyName("secret")]
    public required string Secret { get; init; }

    [JsonPropertyName("name")]
    public required string Name { get; init; }

    [JsonPropertyName("label")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Label { get; init; } = "x";

    [JsonPropertyName("instrument")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Instrument? Instrument { get; init; }
}

/// <summary>
/// Self recursion through lazy(), mutual recursion through Doc, every container, both union
/// forms, every scalar, and field names that are keywords in the target languages
/// </summary>
public sealed record Folder
{
    [JsonPropertyName("id")]
    public required Guid Id { get; init; }

    [JsonPropertyName("class")]
    public required string Class { get; init; }

    [JsonPropertyName("default")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Default { get; init; }

    [JsonPropertyName("rating")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Rating? Rating { get; init; } = global::Example.Sdk.Models.Rating.Neutral;

    [JsonPropertyName("parent")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Folder? Parent { get; init; }

    [JsonPropertyName("readme")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Doc? Readme { get; init; }

    [JsonPropertyName("children")]
    public required List<Folder> Children { get; init; }

    [JsonPropertyName("byName")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Dictionary<string, Folder>? ByName { get; init; }

    [JsonPropertyName("span")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public FolderSpan? Span { get; init; }

    [JsonPropertyName("stamped")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public FolderStamped? Stamped { get; init; }

    [JsonPropertyName("label")]
    public required FolderLabel Label { get; init; }

    [JsonPropertyName("pinned")]
    public required FolderPinned? Pinned { get; init; }

    [JsonPropertyName("instrument")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public FolderInstrument? Instrument { get; init; }

    [JsonPropertyName("origin")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public FolderOrigin? Origin { get; init; }

    [JsonPropertyName("size")]
    public required BigInteger Size { get; init; }

    [JsonPropertyName("price")]
    public required decimal Price { get; init; }

    [JsonPropertyName("day")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateOnly? Day { get; init; }

    [JsonPropertyName("at")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public TimeOnly? At { get; init; }

    [JsonPropertyName("ttl")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public TimeSpan? Ttl { get; init; }

    [JsonPropertyName("blob")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public byte[]? Blob { get; init; }

    [JsonPropertyName("extra")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public JsonElement? Extra { get; init; }

    [JsonPropertyName("raw")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public JsonElement? Raw { get; init; }
}

public sealed record Doc
{
    [JsonPropertyName("id")]
    public required Guid Id { get; init; }

    [JsonPropertyName("folder")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public Folder? Folder { get; init; }
}

[JsonConverter(typeof(FolderSpanConverter))]
public sealed record FolderSpan(long Item0, long Item1);

/// <summary>Reads and writes <see cref="FolderSpan"/> as a JSON array.</summary>
public sealed class FolderSpanConverter : JsonConverter<FolderSpan>
{
    public override FolderSpan Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var array = document.RootElement;
        if (array.ValueKind != JsonValueKind.Array || array.GetArrayLength() != 2)
        {
            throw new JsonException("Expected a JSON array of 2 elements for FolderSpan.");
        }

        return new FolderSpan(
            array[0].Deserialize<long>(options)!,
            array[1].Deserialize<long>(options)!
        );
    }

    public override void Write(Utf8JsonWriter writer, FolderSpan value, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, value.Item0, options);
        JsonSerializer.Serialize(writer, value.Item1, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FolderStampedConverter))]
public sealed record FolderStamped(Guid Item0, DateTimeOffset Item1, bool Item2);

/// <summary>Reads and writes <see cref="FolderStamped"/> as a JSON array.</summary>
public sealed class FolderStampedConverter : JsonConverter<FolderStamped>
{
    public override FolderStamped Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var array = document.RootElement;
        if (array.ValueKind != JsonValueKind.Array || array.GetArrayLength() != 3)
        {
            throw new JsonException("Expected a JSON array of 3 elements for FolderStamped.");
        }

        return new FolderStamped(
            array[0].Deserialize<Guid>(options)!,
            array[1].Deserialize<DateTimeOffset>(options)!,
            array[2].Deserialize<bool>(options)!
        );
    }

    public override void Write(Utf8JsonWriter writer, FolderStamped value, JsonSerializerOptions options)
    {
        writer.WriteStartArray();
        JsonSerializer.Serialize(writer, value.Item0, options);
        JsonSerializer.Serialize(writer, value.Item1, options);
        JsonSerializer.Serialize(writer, value.Item2, options);
        writer.WriteEndArray();
    }
}

[JsonConverter(typeof(FolderLabelConverter))]
public abstract record FolderLabel
{
    private FolderLabel() { }

    public sealed record OfString(string Value) : FolderLabel;

    public sealed record OfInt(long Value) : FolderLabel;
}

/// <summary>Reads <see cref="FolderLabel"/> by trying each member in declaration order.</summary>
public sealed class FolderLabelConverter : JsonConverter<FolderLabel>
{
    public override FolderLabel Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var element = document.RootElement;

        try
        {
            return new FolderLabel.OfString(element.Deserialize<string>(options)!);
        }
        catch (JsonException)
        {
            // Not this member; fall through to the next.
        }

        try
        {
            return new FolderLabel.OfInt(element.Deserialize<long>(options)!);
        }
        catch (JsonException)
        {
            // Not this member; fall through to the next.
        }

        throw new JsonException("No FolderLabel member matched the payload.");
    }

    public override void Write(Utf8JsonWriter writer, FolderLabel value, JsonSerializerOptions options)
    {
        switch (value)
        {
            case FolderLabel.OfString member:
                JsonSerializer.Serialize(writer, member.Value, options);
                break;
            case FolderLabel.OfInt member:
                JsonSerializer.Serialize(writer, member.Value, options);
                break;
            default:
                throw new JsonException($"Unknown FolderLabel member {value.GetType().Name}.");
        }
    }
}

[JsonConverter(typeof(FolderPinnedConverter))]
public abstract record FolderPinned
{
    private FolderPinned() { }

    public sealed record OfDoc(Doc Value) : FolderPinned;

    public sealed record OfFolder(Folder Value) : FolderPinned;
}

/// <summary>Reads <see cref="FolderPinned"/> by trying each member in declaration order.</summary>
public sealed class FolderPinnedConverter : JsonConverter<FolderPinned>
{
    public override FolderPinned Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var element = document.RootElement;

        try
        {
            return new FolderPinned.OfDoc(element.Deserialize<Doc>(options)!);
        }
        catch (JsonException)
        {
            // Not this member; fall through to the next.
        }

        try
        {
            return new FolderPinned.OfFolder(element.Deserialize<Folder>(options)!);
        }
        catch (JsonException)
        {
            // Not this member; fall through to the next.
        }

        throw new JsonException("No FolderPinned member matched the payload.");
    }

    public override void Write(Utf8JsonWriter writer, FolderPinned value, JsonSerializerOptions options)
    {
        switch (value)
        {
            case FolderPinned.OfDoc member:
                JsonSerializer.Serialize(writer, member.Value, options);
                break;
            case FolderPinned.OfFolder member:
                JsonSerializer.Serialize(writer, member.Value, options);
                break;
            default:
                throw new JsonException($"Unknown FolderPinned member {value.GetType().Name}.");
        }
    }
}

[JsonConverter(typeof(FolderInstrumentConverter))]
public abstract record FolderInstrument
{
    private FolderInstrument() { }

    public sealed record OfCard(Card Value) : FolderInstrument;

    public sealed record OfBank(Bank Value) : FolderInstrument;
}

/// <summary>Reads <see cref="FolderInstrument"/> by trying each member in declaration order.</summary>
public sealed class FolderInstrumentConverter : JsonConverter<FolderInstrument>
{
    public override FolderInstrument Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var element = document.RootElement;

        try
        {
            return new FolderInstrument.OfCard(element.Deserialize<Card>(options)!);
        }
        catch (JsonException)
        {
            // Not this member; fall through to the next.
        }

        try
        {
            return new FolderInstrument.OfBank(element.Deserialize<Bank>(options)!);
        }
        catch (JsonException)
        {
            // Not this member; fall through to the next.
        }

        throw new JsonException("No FolderInstrument member matched the payload.");
    }

    public override void Write(Utf8JsonWriter writer, FolderInstrument value, JsonSerializerOptions options)
    {
        switch (value)
        {
            case FolderInstrument.OfCard member:
                JsonSerializer.Serialize(writer, member.Value, options);
                break;
            case FolderInstrument.OfBank member:
                JsonSerializer.Serialize(writer, member.Value, options);
                break;
            default:
                throw new JsonException($"Unknown FolderInstrument member {value.GetType().Name}.");
        }
    }
}

public sealed record FolderOrigin
{
    [JsonPropertyName("x")]
    public required double X { get; init; }

    [JsonPropertyName("y")]
    public required double Y { get; init; }
}

[JsonConverter(typeof(InstrumentConverter))]
public interface Instrument
{
}

/// <summary>Reads <see cref="Instrument"/> by dispatching on its 'kind' tag.</summary>
public sealed class InstrumentConverter : JsonConverter<Instrument>
{
    public override Instrument Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var element = document.RootElement;
        var tag = element.TryGetProperty("kind", out var tagElement) && tagElement.ValueKind == JsonValueKind.String
            ? tagElement.GetString()
            : null;

        return tag switch
        {
            "card" => element.Deserialize<Card>(options)!,
            "bank" => element.Deserialize<Bank>(options)!,
            _ => throw new JsonException($"Unknown Instrument kind: {tag}"),
        };
    }

    public override void Write(Utf8JsonWriter writer, Instrument value, JsonSerializerOptions options)
    {
        switch (value)
        {
            case Card member:
                JsonSerializer.Serialize(writer, member, options);
                break;
            case Bank member:
                JsonSerializer.Serialize(writer, member, options);
                break;
            default:
                throw new JsonException($"Unknown Instrument member {value.GetType().Name}.");
        }
    }
}
