// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Example.Sdk.Models;

/// <summary>A seat, whose field names are all reserved somewhere</summary>
public sealed record Seat
{
    [JsonPropertyName("class")]
    public required string Class { get; init; }

    [JsonPropertyName("from")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateOnly? From { get; init; }

    [JsonPropertyName("date")]
    public required DateOnly Date { get; init; }

    [JsonPropertyName("time")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public TimeOnly? Time { get; init; }

    [JsonPropertyName("copy")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Copy { get; init; }

    [JsonPropertyName("modelDump")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ModelDump { get; init; }

    [JsonPropertyName("json")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Json { get; init; }

    [JsonPropertyName("in")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? In { get; init; }

    [JsonPropertyName("is")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public bool? Is { get; init; }

    [JsonPropertyName("object")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Object { get; init; }

    [JsonPropertyName("default")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Default { get; init; }
}

/// <summary>Path params declared as a model whose field is a keyword, referenced via `params: SeatRef`</summary>
public sealed record SeatRef
{
    [JsonPropertyName("class")]
    public required string Class { get; init; }
}

public sealed record Note
{
    [JsonPropertyName("text")]
    public required string Text { get; init; }
}
