// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Example.Sdk.Models;

/// <summary>A service heartbeat — deliberately no bigint field and no `area` key</summary>
public sealed record Heartbeat
{
    [JsonPropertyName("status")]
    public required string Status { get; init; }

    [JsonPropertyName("checkedAt")]
    public required DateTimeOffset CheckedAt { get; init; }
}
