import type { ContractRootNode, ContractTypeNode, FieldDefault, FieldNode, ModelNode, ScalarTypeNode } from '@contractkit/core';
import { buildModelIndex, computeModelsWithInput, resolveEffectiveFields, topoSortModels } from '@contractkit/core';
import type { HoistedDecl, HoistResult } from './hoist.js';
import { docLines, quoteSwiftString, toSwiftCaseName, toSwiftPropertyName } from './naming.js';

// ─── Public entry point ────────────────────────────────────────────────────

export interface SwiftModelCodegenOptions {
    /** Model names that have a distinct `Input` variant, including ones declared in other files. */
    modelsWithInput?: ReadonlySet<string>;
    /**
     * Every model in the project, for flattening bases and intersections. Defaults to an index of
     * this root's own models, which is enough for a single-file project and for unit tests.
     */
    modelIndex?: ReadonlyMap<string, ModelNode>;
    /** Names assigned to anonymous types by {@link collectHoistedTypes}, across the whole project. */
    hoisted?: HoistResult;
    /** Stored properties that close a value-type cycle, from {@link collectBoxedFields}. */
    boxed?: ReadonlySet<string>;
    warn?: (message: string) => void;
}

/**
 * Generate the Swift models file for one contract root: a `Codable` struct per model, plus
 * `<Name>Input` variants, `String` enums, typealiases, and the enums standing in for the unions
 * and anonymous shapes this file owns.
 *
 * Every generated file lands in one Swift module, so a reference to a model declared in another
 * `.ck` file needs no import and resolves by name alone.
 */
export function generateSwiftModels(root: ContractRootNode, opts: SwiftModelCodegenOptions): string {
    const modelsWithInput = resolveModelsWithInput(root.models, opts.modelsWithInput);
    const modelIndex = opts.modelIndex ?? buildModelIndex(root.models);

    const ctx: RenderContext = {
        modelsWithInput,
        modelIndex,
        hoisted: opts.hoisted,
        boxed: opts.boxed,
        warn: opts.warn,
    };

    const bodies: string[] = [];
    const append = (lines: string[]): void => {
        // A model whose type is a union emits nothing here — the hoisting pass owns the enum named
        // after it — so the blank separator has to be conditional or it leaves a gap behind.
        if (lines.length === 0) return;
        bodies.push('', ...lines);
    };
    for (const model of topoSortModels(root.models)) append(generateModel(model, ctx));
    for (const decl of opts.hoisted?.byFile.get(root.file) ?? []) append(generateHoisted(decl, ctx));

    return renderFile(bodies);
}

/**
 * The complete set of model names that need a distinct `Input` variant: the ones passed in, plus
 * the transitive closure over `models`.
 *
 * The hoisting pass and the renderer both have to agree on this — a hoisted shape whose Input twin
 * one of them thinks is unnecessary would leave the other referring to a type nobody emitted.
 */
export function resolveModelsWithInput(models: readonly ModelNode[], external: ReadonlySet<string> = new Set()): Set<string> {
    const seed = new Set(external);
    return new Set([...seed, ...computeModelsWithInput([...models], seed)]);
}

// ─── Render context ────────────────────────────────────────────────────────

export interface RenderContext {
    modelsWithInput: ReadonlySet<string>;
    modelIndex: ReadonlyMap<string, ModelNode>;
    hoisted?: HoistResult;
    boxed?: ReadonlySet<string>;
    warn?: (message: string) => void;
}

/** Build a rendering context for a file other than a models file, such as a client. */
export function createRenderContext(opts: SwiftModelCodegenOptions & { modelsWithInput: ReadonlySet<string> }): RenderContext {
    return {
        modelsWithInput: opts.modelsWithInput,
        modelIndex: opts.modelIndex ?? new Map(),
        hoisted: opts.hoisted,
        boxed: opts.boxed,
        warn: opts.warn,
    };
}

/**
 * Assemble a generated Swift file: header, imports, then bodies. Every file imports Foundation;
 * one that touches the network also imports `FoundationNetworking`, which is where
 * swift-corelibs-foundation keeps `URLSession` on Linux.
 */
export function renderFile(bodies: string[], opts: { networking?: boolean } = {}): string {
    const lines: string[] = ['// Auto-generated by @contractkit/plugin-swift. Do not edit manually.', 'import Foundation'];
    if (opts.networking) lines.push('#if canImport(FoundationNetworking)', 'import FoundationNetworking', '#endif');
    lines.push(...bodies);
    lines.push('');
    return lines.join('\n');
}

// ─── Type rendering ────────────────────────────────────────────────────────

/**
 * Render a ContractKit type as its Swift type expression. Never returns an optional type unless
 * the type itself is one — the caller appends `?` from the field's own `optional`/`nullable` flags.
 *
 * @param forInput - When true, a reference to a model or hoisted shape with an Input variant
 *   renders as `<Name>Input`.
 * @throws {Error} Via the scalar renderer, if a scalar has no Swift mapping.
 */
export function renderSwiftType(type: ContractTypeNode, ctx: RenderContext, forInput = false): string {
    const decl = ctx.hoisted?.byNode.get(type);
    if (decl) return hoistedTypeName(decl, forInput);

    switch (type.kind) {
        case 'scalar':
            return renderScalar(type.name);
        case 'literal':
            return literalSwiftType(type.value);
        case 'array':
            return `[${renderSwiftType(type.item, ctx, forInput)}]`;
        case 'record': {
            const key = renderSwiftType(type.key, ctx, forInput);
            const value = renderSwiftType(type.value, ctx, forInput);
            if (key !== 'String') {
                ctx.warn?.(
                    `A record key of type '${key}' is not representable as a JSON object key; emitting [String: ${value}]. ` +
                        `Parse the key yourself, or declare the key as a string.`,
                );
            }
            return `[String: ${value}]`;
        }
        case 'ref':
            return forInput && ctx.modelsWithInput.has(type.name) ? `${type.name}Input` : type.name;
        case 'lazy':
            return renderSwiftType(type.inner, ctx, forInput);
        case 'union': {
            // A union with at most one non-null member never gets an enum: it is either Swift's
            // own Optional or nothing at all.
            const nonNull = type.members.filter(m => !isNullScalar(m));
            const nullable = nonNull.length !== type.members.length;
            if (nonNull.length === 0) return 'JSONValue';
            if (nonNull.length === 1) {
                const inner = renderSwiftType(nonNull[0]!, ctx, forInput);
                return nullable && !inner.endsWith('?') ? `${inner}?` : inner;
            }
            return 'JSONValue';
        }
        case 'tuple':
        case 'enum':
        case 'inlineObject':
        case 'intersection':
        case 'discriminatedUnion':
            // Reached only when the shape could not be given a name — a discriminated union whose
            // tag is not statically known, a shape declared inline in an operation rather than in
            // a contract, or a caller that skipped the hoisting pass.
            return 'JSONValue';
    }
}

function hoistedTypeName(decl: HoistedDecl, forInput: boolean): string {
    const name = forInput && decl.needsInput ? `${decl.name}Input` : decl.name;
    return decl.nullable ? `${name}?` : name;
}

function isNullScalar(type: ContractTypeNode): boolean {
    return type.kind === 'scalar' && type.name === 'null';
}

function unwrapLazy(type: ContractTypeNode): ContractTypeNode {
    return type.kind === 'lazy' ? unwrapLazy(type.inner) : type;
}

/**
 * Map a ContractKit scalar to its Swift type.
 *
 * @throws {Error} When a scalar has no mapping, so a scalar added to core fails the build here
 *   rather than emitting Swift that does not compile.
 */
export function renderScalar(name: ScalarTypeNode['name']): string {
    switch (name) {
        case 'string':
        case 'email':
        case 'url':
        case 'interval':
            return 'String';
        case 'number':
            return 'Double';
        case 'int':
            return 'Int';
        case 'bigint':
            return 'BigIntValue';
        case 'decimal':
            return 'DecimalValue';
        case 'boolean':
            return 'Bool';
        case 'date':
            return 'LocalDate';
        case 'time':
            return 'LocalTime';
        case 'datetime':
            return 'Date';
        case 'duration':
            return 'IsoDuration';
        case 'uuid':
            return 'UUID';
        case 'binary':
            return 'Data';
        case 'null':
        case 'unknown':
        case 'json':
        case 'object':
            return 'JSONValue';
        default: {
            const _exhaustive: never = name;
            throw new Error(`plugin-swift: unmapped scalar '${String(_exhaustive)}' — add a case`);
        }
    }
}

function literalSwiftType(value: string | number | boolean): string {
    if (typeof value === 'string') return 'String';
    if (typeof value === 'boolean') return 'Bool';
    return Number.isInteger(value) ? 'Int' : 'Double';
}

/** A literal's value as a Swift expression of {@link literalSwiftType}. */
function literalExpression(value: string | number | boolean): string {
    if (typeof value === 'string') return quoteSwiftString(value);
    if (typeof value === 'boolean') return String(value);
    return Number.isInteger(value) ? String(value) : String(value);
}

// ─── Default values ────────────────────────────────────────────────────────

/**
 * Render a contract default as a Swift expression of the field's own type. Returns `undefined`
 * when the value cannot be expressed, so the field is emitted without a default rather than with
 * one that will not compile.
 */
function renderDefault(value: FieldDefault, type: ContractTypeNode, ctx: RenderContext): string | undefined {
    const inner = unwrapLazy(type);

    if (typeof value === 'boolean') return String(value);

    // A `bigint` value comes from a `bigint` field, whose case below writes it from its exact digits.
    if (typeof value === 'number' || typeof value === 'bigint') {
        if (inner.kind === 'scalar') {
            switch (inner.name) {
                case 'int':
                    return String(value);
                case 'number':
                    return Number.isInteger(value) ? `${value}.0` : String(value);
                case 'decimal':
                    return `DecimalValue("${value}")`;
                case 'bigint':
                    return `BigIntValue("${value}")`;
            }
        }
        return String(value);
    }

    // A string default against an enum names one of its members. When the enum was hoisted into a
    // real Swift enum, that is expressible; a bare inline enum has no type to qualify.
    if (inner.kind === 'enum') {
        const decl = ctx.hoisted?.byNode.get(inner);
        if (!decl || !inner.values.includes(value)) return undefined;
        return `.${enumCaseNames(inner.values).get(value)}`;
    }

    // The same default written against a NAMED enum contract — `rating: Rating = "neutral"`, where
    // `contract Rating: enum(...)` — arrives here as a ref rather than as the enum node.
    if (inner.kind === 'ref') {
        const target = ctx.modelIndex.get(inner.name);
        const targetType = target?.type ? unwrapLazy(target.type) : undefined;
        if (targetType?.kind !== 'enum' || !targetType.values.includes(value)) return undefined;
        return `.${enumCaseNames(targetType.values).get(value)}`;
    }
    if (inner.kind === 'scalar') {
        switch (inner.name) {
            case 'decimal':
                return `DecimalValue(${quoteSwiftString(value)})`;
            case 'bigint':
                return `BigIntValue(${quoteSwiftString(value)})`;
            case 'date':
                return `LocalDate(${quoteSwiftString(value)})`;
            case 'time':
                return `LocalTime(${quoteSwiftString(value)})`;
            case 'duration':
                return `IsoDuration(${quoteSwiftString(value)})`;
            case 'string':
            case 'email':
            case 'url':
            case 'interval':
                return quoteSwiftString(value);
            default:
                // uuid and datetime have no literal syntax; leave the field required.
                return undefined;
        }
    }
    return quoteSwiftString(value);
}

// ─── Wire key casing ───────────────────────────────────────────────────────

/** The key casing a contract's `format(input=)` / `format(output=)` names. */
type WireCase = NonNullable<ModelNode['outputCase']>;

/**
 * A field name as it travels, which is not always the name the contract declares it under.
 *
 * The two transforms are spelled exactly as `plugin-typescript` spells them, deliberately: the
 * server parses and emits through that plugin's schemas, so a Swift client that disagreed with it
 * about where an underscore goes would be wrong in a way no test in either package could see.
 */
function applyWireCase(name: string, wireCase: WireCase | undefined): string {
    if (!wireCase || wireCase === 'camel') return name;
    if (wireCase === 'snake') return name.replace(/[A-Z]/g, c => `_${c.toLowerCase()}`);
    return name.charAt(0).toUpperCase() + name.slice(1);
}

/** A case that actually renames something. `camel` is the identity and is treated as absent. */
function renamingCase(wireCase: WireCase | undefined): WireCase | undefined {
    return wireCase && wireCase !== 'camel' ? wireCase : undefined;
}

/**
 * Which casing a generated struct's keys travel in, per direction.
 *
 * A response is decoded through `format(output=)` and a request is encoded through
 * `format(input=)`. A model split into a read struct and an `Input` twin takes one each. A model
 * that is NOT split is one struct used both ways — and because every struct spells out its own
 * `init(from:)` and `encode(to:)`, it can decode under one key set and encode under another.
 */
function wireCasesFor(model: ModelNode, forInput: boolean, split: boolean): { decode?: WireCase; encode?: WireCase } {
    const input = renamingCase(model.inputCase);
    const output = renamingCase(model.outputCase);
    if (split) return forInput ? { decode: input, encode: input } : { decode: output, encode: output };
    return { decode: output, encode: input };
}

/**
 * Whether a type puts an anonymous object under a renamed model.
 *
 * Such an object is hoisted into a struct of its own, which is rendered without the owning model's
 * casing — the hoisting pass records no owner to take it from. That is a real gap rather than a
 * decision, so it is reported at the one place the owner is still known.
 */
function containsInlineObject(type: ContractTypeNode | undefined): boolean {
    if (!type) return false;
    switch (type.kind) {
        case 'inlineObject':
            return true;
        case 'lazy':
            return containsInlineObject(type.inner);
        case 'array':
            return containsInlineObject(type.item);
        case 'record':
            return containsInlineObject(type.value);
        case 'tuple':
            return type.items.some(containsInlineObject);
        case 'union':
        case 'discriminatedUnion':
        case 'intersection':
            return (type.members ?? []).some(containsInlineObject);
        default:
            return false;
    }
}

/** Report the gap above, once per model rather than once per field. */
function warnUncasedNesting(model: ModelNode, fields: readonly FieldNode[], ctx: RenderContext): void {
    const wireCase = renamingCase(model.outputCase) ?? renamingCase(model.inputCase);
    if (!wireCase) return;
    if (!fields.some(f => containsInlineObject(f.type)) && !containsInlineObject(model.type)) return;
    ctx.warn?.(
        `Contract '${model.name}' is declared format(${model.outputCase ? 'output' : 'input'}=${wireCase}) and holds an anonymous object. ` +
            `The struct hoisted out of that object keeps its declared key names, so its keys will not be ${wireCase}-cased. Name the shape as its own contract to fix it.`,
    );
}

// ─── Model generation ──────────────────────────────────────────────────────

function generateModel(model: ModelNode, ctx: RenderContext): string[] {
    if (model.type) return generateAliasModel(model, ctx);
    return generateStructModel(model, effectiveFieldsFor(model, ctx), ctx);
}

/** A model rendered as a struct, split into a read struct and an `Input` twin when it has to be. */
function generateStructModel(model: ModelNode, effective: FieldNode[], ctx: RenderContext): string[] {
    const needsSplit = ctx.modelsWithInput.has(model.name) || effective.some(f => f.visibility !== 'normal');
    warnUncasedNesting(model, effective, ctx);

    const doc = { description: model.description, deprecated: model.deprecated };
    if (!needsSplit) {
        return renderStruct(model.name, effective, ctx, false, { ...doc, owner: model.name, ...wireCasesFor(model, false, false) });
    }

    const readFields = effective.filter(f => f.visibility !== 'writeonly');
    const inputFields = effective.filter(f => f.visibility !== 'readonly');
    return [
        ...renderStruct(model.name, readFields, ctx, false, { ...doc, owner: model.name, ...wireCasesFor(model, false, true) }),
        '',
        ...renderStruct(`${model.name}Input`, inputFields, ctx, true, { ...doc, owner: model.name, ...wireCasesFor(model, true, true) }),
    ];
}

/**
 * Bases are flattened rather than expressed as Swift inheritance: a struct cannot extend another,
 * and a class hierarchy would give up value semantics and synthesized `Equatable`.
 * `resolveEffectiveFields` applies the same later-wins override rule the inheritance validator
 * enforces.
 */
function effectiveFieldsFor(model: ModelNode, ctx: RenderContext): FieldNode[] {
    if (!model.bases || model.bases.length === 0) return model.fields;
    const { fields, unresolved } = resolveEffectiveFields(model.name, ctx.modelIndex);
    for (const name of unresolved) {
        ctx.warn?.(`Contract '${model.name}' extends '${name}', which is not defined; its fields are missing from the generated struct.`);
    }
    return fields;
}

function generateAliasModel(model: ModelNode, ctx: RenderContext): string[] {
    const type = model.type!;
    const inner = unwrapLazy(type);

    // A union alias is emitted by the hoisting pass, which owns the enum named after it.
    if (ctx.hoisted?.byNode.has(inner)) return [];

    if (inner.kind === 'enum') return generateEnum(model.name, inner.values, ctx, model.description, model.deprecated);

    // An intersection or inline object at model level names a real shape, so it becomes a struct
    // rather than an alias to an opaque JSON object.
    if (inner.kind === 'intersection' || inner.kind === 'inlineObject') {
        const { fields, unresolved } = resolveEffectiveFields(inner, ctx.modelIndex);
        for (const name of unresolved) {
            ctx.warn?.(`Contract '${model.name}' references '${name}', which is not defined; its fields are missing from the generated struct.`);
        }
        return generateStructModel(model, fields, ctx);
    }

    // A tuple alias is a struct under the model's own name, travelling as a JSON array.
    if (inner.kind === 'tuple') {
        const read = renderTupleStruct(model.name, inner.items, ctx, false, model.description, model.deprecated);
        if (!ctx.modelsWithInput.has(model.name)) return read;
        return [...read, '', ...renderTupleStruct(`${model.name}Input`, inner.items, ctx, true, model.description, model.deprecated)];
    }

    const lines: string[] = [];
    lines.push(...declarationDoc(model.description, model.deprecated, ''));
    lines.push(`public typealias ${model.name} = ${renderSwiftType(type, ctx, false)}`);
    if (ctx.modelsWithInput.has(model.name)) {
        lines.push(`public typealias ${model.name}Input = ${renderSwiftType(type, ctx, true)}`);
    }
    return lines;
}

function enumCaseNames(values: string[]): Map<string, string> {
    const out = new Map<string, string>();
    const used = new Set<string>();
    for (const value of values) out.set(value, uniqueName(toSwiftCaseName(value), used));
    return out;
}

function generateEnum(name: string, values: string[], ctx: RenderContext, description?: string, deprecated?: boolean): string[] {
    const cases = enumCaseNames(values);
    const lines: string[] = [];
    lines.push(...declarationDoc(description, deprecated, ''));
    lines.push(`public enum ${name}: String, Codable, CaseIterable, Sendable {`);
    for (const value of values) {
        lines.push(`    case ${cases.get(value)} = ${quoteSwiftString(value)}`);
    }
    lines.push('}');
    // An enum has no fields, so no visibility can differ between reading and writing it.
    if (ctx.modelsWithInput.has(name)) lines.push(`public typealias ${name}Input = ${name}`);
    return lines;
}

// ─── Struct rendering ──────────────────────────────────────────────────────

interface StructOptions {
    description?: string;
    deprecated?: boolean;
    /** The declaration the field belongs to in the boxed-field set — the read name, for an Input twin too. */
    owner: string;
    /** Key casing for `init(from:)`. */
    decode?: WireCase;
    /** Key casing for `encode(to:)`. */
    encode?: WireCase;
}

/** How one stored property is declared, initialised, decoded, and encoded. */
interface RenderedField {
    /** The name the contract declares, for spelling the wire key. */
    sourceName: string;
    /** The public property name, keyword-escaped. */
    propName: string;
    /** The stored property: the same as `propName`, or the private box behind it. */
    storageName: string;
    publicType: string;
    storageType: string;
    boxed: boolean;
    /** Whether the public property is an Optional. */
    optional: boolean;
    initDefault?: string;
    doc: string[];
    decode: string;
    guard?: string[];
    encode: string;
}

function renderStruct(name: string, fields: FieldNode[], ctx: RenderContext, forInput: boolean, opts: StructOptions): string[] {
    const lines: string[] = [];
    lines.push(...declarationDoc(opts.description, opts.deprecated, ''));
    lines.push(`public struct ${name}: Codable, Equatable, Sendable {`);

    // A contract with no visible fields still has to be a type a caller can hold and decode.
    if (fields.length === 0) {
        lines.push('    public init() {}');
        lines.push('');
        lines.push('    public init(from decoder: Decoder) throws {');
        lines.push('        _ = try decoder.container(keyedBy: DynamicCodingKey.self)');
        lines.push('    }');
        lines.push('');
        lines.push('    public func encode(to encoder: Encoder) throws {');
        lines.push('        _ = encoder.container(keyedBy: DynamicCodingKey.self)');
        lines.push('    }');
        lines.push('}');
        return lines;
    }

    const rendered = fields.map(field => renderField(field, ctx, forInput, opts.owner));
    const separateEncodingKeys = opts.encode !== opts.decode;
    const encodeKeys = separateEncodingKeys ? 'EncodingKeys' : 'CodingKeys';

    // Stored properties, with a computed accessor in front of each box.
    for (const f of rendered) {
        lines.push(...f.doc);
        if (!f.boxed) {
            lines.push(`    public var ${f.propName}: ${f.publicType}`);
            continue;
        }
        lines.push(`    private var ${f.storageName}: ${f.storageType}`);
        lines.push(`    public var ${f.propName}: ${f.publicType} {`);
        lines.push(`        get { ${f.storageName}${f.optional ? '?' : ''}.value }`);
        lines.push(`        set { ${f.storageName} = ${boxExpression('newValue', f.optional)} }`);
        lines.push('    }');
    }

    // The memberwise initializer, spelled out because the synthesized one is internal.
    lines.push('');
    const params = rendered.map(f => `${f.propName}: ${f.publicType}${f.initDefault !== undefined ? ` = ${f.initDefault}` : ''}`);
    lines.push(`    public init(${params.join(', ')}) {`);
    for (const f of rendered) {
        lines.push(`        self.${f.storageName} = ${f.boxed ? boxExpression(f.propName, f.optional) : f.propName}`);
    }
    lines.push('    }');

    // Keys. The wire name is always spelled out, so a keyword-escaped or re-cased property never
    // drifts from what the service expects.
    lines.push('');
    lines.push('    private enum CodingKeys: String, CodingKey {');
    for (const f of rendered) lines.push(`        case ${f.storageName} = ${quoteSwiftString(applyWireCase(f.sourceName, opts.decode))}`);
    lines.push('    }');
    if (separateEncodingKeys) {
        lines.push('');
        lines.push('    private enum EncodingKeys: String, CodingKey {');
        for (const f of rendered) lines.push(`        case ${f.storageName} = ${quoteSwiftString(applyWireCase(f.sourceName, opts.encode))}`);
        lines.push('    }');
    }

    lines.push('');
    lines.push('    public init(from decoder: Decoder) throws {');
    lines.push('        let container = try decoder.container(keyedBy: CodingKeys.self)');
    for (const f of rendered) {
        lines.push(`        self.${f.storageName} = ${f.decode}`);
        if (f.guard) lines.push(...f.guard.map(l => `        ${l}`));
    }
    lines.push('    }');

    lines.push('');
    lines.push('    public func encode(to encoder: Encoder) throws {');
    lines.push(`        var container = encoder.container(keyedBy: ${encodeKeys}.self)`);
    for (const f of rendered) lines.push(`        ${f.encode}`);
    lines.push('    }');
    lines.push('}');
    return lines;
}

function boxExpression(value: string, optional: boolean): string {
    return optional ? `${value}.map { Indirect($0) }` : `Indirect(${value})`;
}

/**
 * Decide how one field is stored and coded. The four shapes the language allows each map onto a
 * distinct pair of `KeyedDecodingContainer`/`KeyedEncodingContainer` calls, so an omitted optional,
 * an explicit null, a default, and a literal all mean on the wire exactly what the contract says.
 */
function renderField(field: FieldNode, ctx: RenderContext, forInput: boolean, owner: string): RenderedField {
    const propName = toSwiftPropertyName(field.name);
    const inner = unwrapLazy(field.type);
    const rendered = renderSwiftType(field.type, ctx, forInput);
    const renderedNullable = rendered.endsWith('?');
    const core = renderedNullable ? rendered.slice(0, -1) : rendered;
    const key = `.${propName}`;

    const boxed = ctx.boxed?.has(`${owner}.${field.name}`) ?? false;
    const storageName = boxed ? `_${propName.replace(/`/g, '')}` : propName;
    const storageCore = boxed ? `Indirect<${core}>` : core;
    const boxedKey = boxed ? `.${storageName}` : key;

    const explicitDefault = field.default !== undefined ? renderDefault(field.default, field.type, ctx) : undefined;
    const nullable = field.nullable || renderedNullable;
    const doc = fieldDoc(field, '    ');

    // Shape 1 — a default: always present in Swift, filled in when the wire omits it.
    if (explicitDefault !== undefined) {
        const optional = nullable;
        return {
            sourceName: field.name,
            propName,
            storageName,
            publicType: optional ? `${core}?` : core,
            storageType: optional ? `${storageCore}?` : storageCore,
            boxed,
            optional,
            initDefault: explicitDefault,
            doc,
            decode: `try container.decodeIfPresent(${storageCore}.self, forKey: ${boxedKey}) ?? ${explicitDefault}`,
            encode: `try container.encode(self.${storageName}, forKey: ${boxedKey})`,
        };
    }

    // Shape 2 — a literal: one value, validated on the way in and written on the way out.
    if (inner.kind === 'literal') {
        const expected = literalExpression(inner.value);
        if (field.optional || nullable) {
            return {
                sourceName: field.name,
                propName,
                storageName,
                publicType: `${core}?`,
                storageType: `${storageCore}?`,
                boxed,
                optional: true,
                initDefault: expected,
                doc,
                decode: `try container.decodeIfPresent(${storageCore}.self, forKey: ${boxedKey})`,
                guard: [
                    `guard self.${storageName} == nil || self.${storageName} == ${expected} else {`,
                    `    throw DecodingError.dataCorruptedError(forKey: ${boxedKey}, in: container, debugDescription: "Expected ${escapeForDebug(expected)}")`,
                    '}',
                ],
                encode: `try container.encodeIfPresent(self.${storageName}, forKey: ${boxedKey})`,
            };
        }
        return {
            sourceName: field.name,
            propName,
            storageName,
            publicType: core,
            storageType: storageCore,
            boxed,
            optional: false,
            initDefault: expected,
            doc,
            decode: `try container.decode(${storageCore}.self, forKey: ${boxedKey})`,
            guard: [
                `guard self.${storageName} == ${expected} else {`,
                `    throw DecodingError.dataCorruptedError(forKey: ${boxedKey}, in: container, debugDescription: "Expected ${escapeForDebug(expected)}")`,
                '}',
            ],
            encode: `try container.encode(self.${storageName}, forKey: ${boxedKey})`,
        };
    }

    // Shape 3 — optional: may be omitted, and is omitted again when nil.
    if (field.optional) {
        return {
            sourceName: field.name,
            propName,
            storageName,
            publicType: `${core}?`,
            storageType: `${storageCore}?`,
            boxed,
            optional: true,
            initDefault: 'nil',
            doc,
            decode: `try container.decodeIfPresent(${storageCore}.self, forKey: ${boxedKey})`,
            encode: `try container.encodeIfPresent(self.${storageName}, forKey: ${boxedKey})`,
        };
    }

    // Shape 4 — required but nullable: the key has to be there, and a nil goes out as an explicit
    // null rather than being dropped.
    if (nullable) {
        return {
            sourceName: field.name,
            propName,
            storageName,
            publicType: `${core}?`,
            storageType: `${storageCore}?`,
            boxed,
            optional: true,
            doc,
            decode: `try container.decode(${storageCore}?.self, forKey: ${boxedKey})`,
            encode: `try container.encode(self.${storageName}, forKey: ${boxedKey})`,
        };
    }

    // Shape 5 — required.
    return {
        sourceName: field.name,
        propName,
        storageName,
        publicType: core,
        storageType: storageCore,
        boxed,
        optional: false,
        doc,
        decode: `try container.decode(${storageCore}.self, forKey: ${boxedKey})`,
        encode: `try container.encode(self.${storageName}, forKey: ${boxedKey})`,
    };
}

/** A Swift expression, made safe to sit inside a string literal's debug description. */
function escapeForDebug(expression: string): string {
    return expression.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

// ─── Hoisted declarations ──────────────────────────────────────────────────

/** Emit the declaration standing in for one anonymous type, plus its Input twin when it needs one. */
function generateHoisted(decl: HoistedDecl, ctx: RenderContext): string[] {
    const read = generateHoistedVariant(decl, ctx, false);
    if (!decl.needsInput) return read;
    return [...read, '', ...generateHoistedVariant(decl, ctx, true)];
}

function generateHoistedVariant(decl: HoistedDecl, ctx: RenderContext, forInput: boolean): string[] {
    const name = forInput ? `${decl.name}Input` : decl.name;
    switch (decl.kind) {
        case 'enum':
            return generateEnum(name, decl.values ?? [], ctx, decl.description);
        case 'struct':
            return renderStruct(
                name,
                (decl.fields ?? []).filter(f => (forInput ? f.visibility !== 'readonly' : f.visibility !== 'writeonly')),
                ctx,
                forInput,
                { description: decl.description, owner: decl.name },
            );
        case 'tuple':
            return renderTupleStruct(name, decl.items ?? [], ctx, forInput, decl.description, undefined, decl.name);
        case 'plainUnion':
            return generatePlainUnion(decl, name, ctx, forInput);
        case 'discriminatedUnion':
            return generateDiscriminatedUnion(decl, name, ctx, forInput);
    }
}

/**
 * A contract tuple as a struct with positional properties, travelling as a JSON array. Swift's own
 * tuples are not `Codable`, and a struct also gives the caller named access and `Equatable`.
 */
function renderTupleStruct(
    name: string,
    items: ContractTypeNode[],
    ctx: RenderContext,
    forInput: boolean,
    description?: string,
    deprecated?: boolean,
    owner: string = name,
): string[] {
    const rendered = items.map((item, i) => {
        const type = renderSwiftType(item, ctx, forInput);
        const boxed = ctx.boxed?.has(`${owner}._${i}`) ?? false;
        return { propName: `_${i}`, storageName: boxed ? `__${i}` : `_${i}`, type, storageType: boxed ? `Indirect<${type}>` : type, boxed };
    });

    const lines: string[] = [];
    lines.push(...declarationDoc(description, deprecated, ''));
    lines.push(`public struct ${name}: Codable, Equatable, Sendable {`);
    for (const f of rendered) {
        if (!f.boxed) {
            lines.push(`    public var ${f.propName}: ${f.type}`);
            continue;
        }
        lines.push(`    private var ${f.storageName}: ${f.storageType}`);
        lines.push(`    public var ${f.propName}: ${f.type} {`);
        lines.push(`        get { ${f.storageName}.value }`);
        lines.push(`        set { ${f.storageName} = Indirect(newValue) }`);
        lines.push('    }');
    }
    lines.push('');
    lines.push(`    public init(${rendered.map(f => `_ ${f.propName}: ${f.type}`).join(', ')}) {`);
    for (const f of rendered) lines.push(`        self.${f.storageName} = ${f.boxed ? `Indirect(${f.propName})` : f.propName}`);
    lines.push('    }');
    lines.push('');
    lines.push('    public init(from decoder: Decoder) throws {');
    lines.push('        var container = try decoder.unkeyedContainer()');
    lines.push(`        if let count = container.count, count != ${items.length} {`);
    lines.push(
        `            throw DecodingError.dataCorruptedError(in: container, debugDescription: "Expected ${items.length} elements for ${name}, got \\(count)")`,
    );
    lines.push('        }');
    for (const f of rendered) lines.push(`        self.${f.storageName} = try container.decode(${f.storageType}.self)`);
    lines.push('    }');
    lines.push('');
    lines.push('    public func encode(to encoder: Encoder) throws {');
    lines.push('        var container = encoder.unkeyedContainer()');
    for (const f of rendered) lines.push(`        try container.encode(self.${f.storageName})`);
    lines.push('    }');
    lines.push('}');
    return lines;
}

/**
 * A plain `union(A | B)` becomes an enum with one payload case per member, so callers get an
 * exhaustive `switch` instead of an untyped JSON value.
 *
 * Decoding tries each member in declaration order and takes the first that parses, which is exactly
 * what Zod's `z.union` does on the server. Anything else would let the client and the service
 * disagree about a payload both of them accept.
 */
function generatePlainUnion(decl: HoistedDecl, name: string, ctx: RenderContext, forInput: boolean): string[] {
    const members = (decl.members ?? []).map(member => ({ ...member, swiftType: renderSwiftType(member.type, ctx, forInput) }));

    const lines: string[] = [];
    lines.push(...declarationDoc(decl.description, undefined, ''));
    lines.push(`public indirect enum ${name}: Codable, Equatable, Sendable {`);
    for (const member of members) lines.push(`    case ${member.caseName}(${member.swiftType})`);
    lines.push('');
    lines.push('    public init(from decoder: Decoder) throws {');
    lines.push('        let container = try decoder.singleValueContainer()');
    members.forEach((member, i) => {
        lines.push(`        ${i === 0 ? 'if' : '} else if'} let value = try? container.decode(${member.swiftType}.self) {`);
        lines.push(`            self = .${member.caseName}(value)`);
    });
    lines.push('        } else {');
    lines.push(`            throw DecodingError.dataCorruptedError(in: container, debugDescription: "No ${name} member matched the payload")`);
    lines.push('        }');
    lines.push('    }');
    lines.push('');
    lines.push('    public func encode(to encoder: Encoder) throws {');
    lines.push('        var container = encoder.singleValueContainer()');
    lines.push('        switch self {');
    for (const member of members) {
        lines.push(`        case .${member.caseName}(let value):`);
        lines.push('            try container.encode(value)');
    }
    lines.push('        }');
    lines.push('    }');
    lines.push('}');
    return lines;
}

/**
 * A `discriminated(by=tag, A | B)` becomes an enum with one case per member. Decoding reads the tag
 * through a dynamic key and then hands the same decoder to the member it names, so the member's
 * own `init(from:)` — literal check included — does the rest. Encoding delegates to the member, so
 * the tag stays a real property of it and one contract can belong to several unions.
 */
function generateDiscriminatedUnion(decl: HoistedDecl, name: string, ctx: RenderContext, forInput: boolean): string[] {
    const members = (decl.members ?? []).map(member => ({
        ...member,
        swiftType: memberTypeName(member.typeName, ctx, forInput),
    }));
    const discriminator = quoteSwiftString(decl.discriminator ?? '');
    const key = `DynamicCodingKey(stringValue: ${discriminator})`;

    const lines: string[] = [];
    lines.push(...declarationDoc(decl.description, undefined, ''));
    lines.push(`public indirect enum ${name}: Codable, Equatable, Sendable {`);
    for (const member of members) lines.push(`    case ${member.caseName}(${member.swiftType})`);
    lines.push('');
    lines.push('    public init(from decoder: Decoder) throws {');
    lines.push('        let container = try decoder.container(keyedBy: DynamicCodingKey.self)');
    lines.push(`        let tag = try container.decode(JSONValue.self, forKey: ${key})`);
    lines.push('        switch tag {');
    for (const member of members) {
        lines.push(`        case ${tagPattern(member.tag ?? '', member.type, decl.discriminator ?? '', ctx)}:`);
        lines.push(`            self = .${member.caseName}(try ${member.swiftType}(from: decoder))`);
    }
    lines.push('        default:');
    lines.push(
        `            throw DecodingError.dataCorruptedError(forKey: ${key}, in: container, debugDescription: "Unknown ${name} ${decl.discriminator}: \\(tag)")`,
    );
    lines.push('        }');
    lines.push('    }');
    lines.push('');
    lines.push('    public func encode(to encoder: Encoder) throws {');
    lines.push('        switch self {');
    for (const member of members) {
        lines.push(`        case .${member.caseName}(let value):`);
        lines.push('            try value.encode(to: encoder)');
    }
    lines.push('        }');
    lines.push('    }');
    lines.push('}');
    return lines;
}

/** The `JSONValue` pattern a member's tag literal matches, in the literal's own JSON type. */
function tagPattern(tag: string, member: ContractTypeNode, discriminator: string, ctx: RenderContext): string {
    const literal = discriminatorLiteral(member, discriminator, ctx);
    if (typeof literal === 'boolean') return `.bool(${literal})`;
    if (typeof literal === 'number') return `.number(${literal})`;
    return `.string(${quoteSwiftString(tag)})`;
}

/** The literal value of a member's discriminator field, or `undefined` when it is not a literal. */
function discriminatorLiteral(member: ContractTypeNode, discriminator: string, ctx: RenderContext): string | number | boolean | undefined {
    const field = resolveEffectiveFields(member, ctx.modelIndex).fields.find(f => f.name === discriminator);
    const type = field ? unwrapLazy(field.type) : undefined;
    return type?.kind === 'literal' ? type.value : undefined;
}

/** The concrete type name of a union member, in the read or input variant. */
function memberTypeName(typeName: string, ctx: RenderContext, forInput: boolean): string {
    if (!forInput) return typeName;
    const decl = ctx.hoisted?.byName.get(typeName);
    if (decl) return decl.needsInput ? `${typeName}Input` : typeName;
    return ctx.modelsWithInput.has(typeName) ? `${typeName}Input` : typeName;
}

// ─── Shared helpers ────────────────────────────────────────────────────────

/**
 * Documentation for a declaration. Deprecation is noted in the doc comment rather than with
 * `@available(*, deprecated)`: the attribute on a model would make every generated client method
 * that names it warn, and on a field it would make the struct's own initializer warn.
 */
function declarationDoc(description: string | undefined, deprecated: boolean | undefined, indent: string): string[] {
    const parts: string[] = [];
    if (description) parts.push(description);
    if (deprecated) parts.push('- Warning: Deprecated in the contract.');
    if (parts.length === 0) return [];
    return docLines(parts.join('\n'), indent);
}

function fieldDoc(field: FieldNode, indent: string): string[] {
    return declarationDoc(field.description, field.deprecated, indent);
}

function uniqueName(name: string, used: Set<string>): string {
    if (!used.has(name)) {
        used.add(name);
        return name;
    }
    let n = 2;
    while (used.has(`${name}${n}`)) n++;
    used.add(`${name}${n}`);
    return `${name}${n}`;
}
