/**
 * The `Runtime/Scalars.swift` file: the wrapper types for the ContractKit scalars Foundation has
 * no faithful type for, and the protocol that lets a typed response header be read.
 *
 * Each wrapper keeps the value as its source text. Foundation's `Decimal` has already been through
 * a double by the time JSON hands it over, and `Duration` has no ISO 8601 parser, so keeping the text
 * is the only way to hand the caller exactly what the service said. The names avoid the Foundation
 * and standard-library ones on purpose: a generated `Decimal` would be ambiguous with
 * `Foundation.Decimal` in every file that imports both.
 */

interface StringScalar {
    name: string;
    doc: string;
}

const STRING_SCALARS: readonly StringScalar[] = [
    {
        name: 'DecimalValue',
        doc:
            'An exact decimal number, kept as its source text. Travels as a quoted JSON string, never as a\n' +
            'JSON number: by the time a number reaches this type it has already been through a double, so\n' +
            'the precision the contract asked for is gone. Hand `rawValue` to whatever big-decimal library\n' +
            'you use for arithmetic.',
    },
    {
        name: 'LocalDate',
        doc: 'A calendar date without a time zone, as ISO 8601 text: `2024-03-01`.',
    },
    {
        name: 'LocalTime',
        doc: 'A time of day without a time zone, as ISO 8601 text: `13:45:00`.',
    },
    {
        name: 'IsoDuration',
        doc: 'A duration as ISO 8601 text: `PT1H30M`. Kept as text; Swift has no parser for the format.',
    },
];

/** Generate `Runtime/Scalars.swift`. Content depends on nothing. */
export function generateScalarsSwift(): string {
    const wrappers = STRING_SCALARS.map(scalar => renderStringScalar(scalar.name, scalar.doc)).join('\n');
    return String.raw`// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// A value that can be read back out of an HTTP header. Header values arrive as text, so every type
/// a contract may declare on a response header knows how to parse itself from one.
public protocol HeaderDecodable {
    init?(headerValue: String)
}

extension String: HeaderDecodable {
    public init?(headerValue: String) {
        self = headerValue
    }
}

extension Int: HeaderDecodable {
    public init?(headerValue: String) {
        self.init(headerValue.trimmingCharacters(in: .whitespaces))
    }
}

extension Double: HeaderDecodable {
    public init?(headerValue: String) {
        self.init(headerValue.trimmingCharacters(in: .whitespaces))
    }
}

extension Bool: HeaderDecodable {
    public init?(headerValue: String) {
        switch headerValue.trimmingCharacters(in: .whitespaces).lowercased() {
        case "true", "1":
            self = true
        case "false", "0":
            self = false
        default:
            return nil
        }
    }
}

extension UUID: HeaderDecodable {
    public init?(headerValue: String) {
        self.init(uuidString: headerValue.trimmingCharacters(in: .whitespaces))
    }
}

extension Date: HeaderDecodable {
    public init?(headerValue: String) {
        guard let date = SdkJSON.parseDate(headerValue.trimmingCharacters(in: .whitespaces)) else { return nil }
        self = date
    }
}

/// An arbitrary-precision integer, kept as its digit string. Encodes as a plain digit string.
/// Decoding accepts a digit string, the ${'`'}123n${'`'} form the TypeScript SDK emits, and a JSON number, so a
/// body written by any ContractKit client reads back here.
public struct BigIntValue: Codable, Hashable, Sendable, CustomStringConvertible, HeaderDecodable {
    public var rawValue: String

    public init(_ rawValue: String) {
        self.rawValue = rawValue
    }

    public init?(headerValue: String) {
        self.init(headerValue.trimmingCharacters(in: .whitespaces))
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let text = try? container.decode(String.self) {
            rawValue = text.hasSuffix("n") ? String(text.dropLast()) : text
        } else if let number = try? container.decode(Int64.self) {
            rawValue = String(number)
        } else if let number = try? container.decode(Double.self) {
            rawValue = JSONValue.text(for: number)
        } else {
            throw DecodingError.dataCorruptedError(in: container, debugDescription: "Expected a JSON string or number for BigIntValue")
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public var description: String { rawValue }
}
${wrappers}`;
}

function renderStringScalar(name: string, doc: string): string {
    const docLines = doc
        .split('\n')
        .map(line => `/// ${line}`)
        .join('\n');
    return String.raw`
${docLines}
public struct ${name}: Codable, Hashable, Sendable, CustomStringConvertible, HeaderDecodable {
    public var rawValue: String

    public init(_ rawValue: String) {
        self.rawValue = rawValue
    }

    public init?(headerValue: String) {
        self.init(headerValue.trimmingCharacters(in: .whitespaces))
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        rawValue = try container.decode(String.self)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }

    public var description: String { rawValue }
}
`;
}
