// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Net.Http;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using Example.Sdk.Models;
using Example.Sdk.Runtime;

namespace Example.Sdk.Clients;

/// <summary>Operations declared in &lt;c&gt;billing.ck&lt;/c&gt;.</summary>
public sealed class BillingClient(SdkHttp http)
{
    /// <summary>create a payment</summary>
    /// <exception cref="SdkException">On 400.</exception>
    public async Task<CreatePaymentResult> CreatePaymentAsync(PaymentInput body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("payments"),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        var headers = new CreatePaymentHeaders(
            http.RequireHeader(response, "x-request-id"),
            long.Parse(http.RequireHeader(response, "x-ratelimit-remaining"), CultureInfo.InvariantCulture),
            response.Header("x-cache-hit") is { } xCacheHit ? xCacheHit == "true" : null,
            response.Header("x-expires-after") is { } xExpiresAfter ? DateTimeOffset.Parse(xExpiresAfter, CultureInfo.InvariantCulture) : null);
        return new CreatePaymentResult(http.ReadJson<Payment>(response), headers);
    }

    /// <summary>list payments</summary>
    public async Task<List<Payment>> ListPaymentsAsync(ListPaymentsQuery query, ListPaymentsHeaders customHeaders, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("payments"),
            query: http.Params(query),
            headers: http.Params(customHeaders),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<List<Payment>>(response);
    }

    /// <summary>create several payments at once</summary>
    public async Task<List<Payment>> CreatePaymentsAsync(List<PaymentInput> body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("payments", "batch"),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<List<Payment>>(response);
    }

    /// <summary>fetch one payment</summary>
    /// <exception cref="SdkException">On 404.</exception>
    public async Task<Payment> GetPaymentAsync(Guid paymentId, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("payments", http.Segment(paymentId)),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<Payment>(response);
    }

    /// <summary>update a payment with form data</summary>
    public async Task UpdatePaymentWithFormAsync(Guid paymentId, UpdatePaymentForm body, CancellationToken cancellationToken = default)
    {
        await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("payments", http.Segment(paymentId)),
            content: http.FormContent(body),
            cancellationToken: cancellationToken).ConfigureAwait(false);
    }

    /// <summary>delete a payment — declares only a documented error status</summary>
    /// <exception cref="SdkException">On 400.</exception>
    public async Task DeletePaymentAsync(Guid paymentId, CancellationToken cancellationToken = default)
    {
        await http.ExecuteAsync(
            HttpMethod.Delete,
            http.Path("payments", http.Segment(paymentId)),
            cancellationToken: cancellationToken).ConfigureAwait(false);
    }

    /// <summary>upload a receipt image</summary>
    public async Task<Payment> UploadReceiptAsync(Guid paymentId, IEnumerable<SdkPart> body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("payments", http.Segment(paymentId), "receipt"),
            content: http.MultipartContent(body),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<Payment>(response);
    }

    /// <summary>look up a refund by its originating payment</summary>
    /// <exception cref="SdkException">On 404.</exception>
    [Obsolete("Deprecated in the contract")]
    public async Task<Payment> GetRefundAsync(PaymentRef pathParams, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("refunds", http.Segment(pathParams.PaymentId)),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<Payment>(response);
    }

    /// <summary>store a credential</summary>
    public async Task<Credential> CreateCredentialAsync(AdminCredentialInput body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("credentials"),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<Credential>(response);
    }

    /// <summary>open a session</summary>
    public async Task<Session> CreateSessionAsync(SessionInput body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("sessions"),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<Session>(response);
    }
}

/// <summary>Response headers declared on POST /payments.</summary>
public sealed record CreatePaymentHeaders(string XRequestId, long XRatelimitRemaining, bool? XCacheHit, DateTimeOffset? XExpiresAfter);

/// <summary>The body of POST /payments, with the response headers the contract declares.</summary>
public sealed record CreatePaymentResult(Payment Data, CreatePaymentHeaders Headers);

/// <summary>The query parameters declared on GET /payments.</summary>
public sealed record ListPaymentsQuery
{
    [JsonPropertyName("limit")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? Limit { get; init; }

    [JsonPropertyName("cursor")]
    public required string Cursor { get; init; }

    [JsonPropertyName("status")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public JsonElement? Status { get; init; }
}

/// <summary>The request headers declared on GET /payments.</summary>
public sealed record ListPaymentsHeaders
{
    [JsonPropertyName("api-key")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ApiKey { get; init; }

    [JsonPropertyName("x-tenant")]
    public required string XTenant { get; init; }
}
