// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Net.Http;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using Example.Sdk.Models;
using Example.Sdk.Runtime;

namespace Example.Sdk.Clients;

/// <summary>Operations declared in &lt;c&gt;hyphenated.ck&lt;/c&gt;.</summary>
public sealed class HyphenatedClient(SdkHttp http)
{
    /// <summary>fetch an invoice</summary>
    /// <exception cref="SdkException">On 404.</exception>
    public async Task<Invoice> GetInvoiceAsync(Guid invoiceId, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("invoices", http.Segment(invoiceId)),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<Invoice>(response);
    }
}
