// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Net.Http;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using Example.Sdk.Models;
using Example.Sdk.Runtime;

namespace Example.Sdk.Clients;

/// <summary>Operations declared in &lt;c&gt;kitchen.ck&lt;/c&gt;.</summary>
public sealed class KitchenClient(SdkHttp http)
{
    /// <summary>several statuses, and two content types on one of them</summary>
    public async Task<GetFolderResponse> GetFolderAsync(Guid folderId, GetFolderHeaders customHeaders, GetFolderQuery? query = null, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("folders", http.Segment(folderId)),
            query: http.Params(query),
            headers: http.Params(customHeaders),
            expectStatuses: new[] { 404 },
            cancellationToken: cancellationToken).ConfigureAwait(false);
        switch (response.Status)
        {
            case 204:
            {
                return new GetFolderResponse.Status204();
            }

            case 404:
            {
                return new GetFolderResponse.Status404(http.ReadJson<Shared>(response));
            }

            default:
            {
                var headers = new GetFolder200Headers(
                    long.Parse(http.RequireHeader(response, "x-count"), CultureInfo.InvariantCulture),
                    response.Header("x-when") is { } xWhen ? DateTimeOffset.Parse(xWhen, CultureInfo.InvariantCulture) : null);
                switch (response.ContentType)
                {
                    case "text/plain":
                        return new GetFolderResponse.Status200TextPlain(response.Text, headers);
                    default:
                        return new GetFolderResponse.Status200ApplicationJson(http.ReadJson<Folder>(response), headers);
                }
            }
        }
    }

    /// <summary>a method name that is a keyword in the target languages</summary>
    public async Task<Instrument> ImportAsync(Guid folderId, SharedInput body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Put,
            http.Path("folders", http.Segment(folderId)),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<Instrument>(response);
    }

    public async Task<Stamped> StampAsync(Stamped body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("stamps"),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<Stamped>(response);
    }

    /// <exception cref="SdkException">On 400.</exception>
    public async Task<Token> MintAsync(Token body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Post,
            http.Path("tokens"),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<Token>(response);
    }

    public async Task<List<Token>> ListTokensAsync(CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("tokens"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<List<Token>>(response);
    }
}

/// <summary>The query parameters declared on GET /folders/{folder-id}.</summary>
public sealed record GetFolderQuery
{
    [JsonPropertyName("depth")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? Depth { get; init; }

    [JsonPropertyName("tags")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public List<string>? Tags { get; init; }
}

/// <summary>The request headers declared on GET /folders/{folder-id}.</summary>
public sealed record GetFolderHeaders
{
    [JsonPropertyName("x-trace")]
    public required string XTrace { get; init; }

    [JsonPropertyName("x-opt")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? XOpt { get; init; }
}

/// <summary>Response headers declared on GET /folders/{folder-id}.</summary>
public sealed record GetFolder200Headers(long XCount, DateTimeOffset? XWhen);

/// <summary>
/// What GET /folders/{folder-id} returned.
///
/// The operation declares several statuses the service produces, so the status is part of the value.
/// </summary>
public abstract record GetFolderResponse
{
    private GetFolderResponse() { }

    public sealed record Status200ApplicationJson(Folder Data, GetFolder200Headers Headers) : GetFolderResponse;

    public sealed record Status200TextPlain(string Data, GetFolder200Headers Headers) : GetFolderResponse;

    public sealed record Status204() : GetFolderResponse;

    public sealed record Status404(Shared Data) : GetFolderResponse;
}
