// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Net.Http;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using Example.Sdk.Models;
using Example.Sdk.Runtime;

namespace Example.Sdk.Clients;

/// <summary>Operations declared in &lt;c&gt;reserved.ck&lt;/c&gt;.</summary>
public sealed class ReservedClient(SdkHttp http)
{
    /// <summary>fetch one seat</summary>
    public async Task<GetSeatResult> GetSeatAsync(string @class, GetSeatQuery? query = null, GetSeatHeaders? customHeaders = null, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("seats", http.Segment(@class)),
            query: http.Params(query),
            headers: http.Params(customHeaders),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        var headers = new GetSeatResponseHeaders(
            response.Header("from") is { } from ? from : null);
        return new GetSeatResult(http.ReadJson<Seat>(response), headers);
    }

    /// <summary>fetch a row by its seat class</summary>
    public async Task<Seat> GetRowAsync(SeatRef pathParams, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("rows", http.Segment(pathParams.Class)),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<Seat>(response);
    }

    /// <summary>replace a note</summary>
    public async Task<Note> PutNoteAsync(string body_, Note body, CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Put,
            http.Path("notes", http.Segment(body_)),
            content: http.JsonContent(body, "application/json"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<Note>(response);
    }
}

/// <summary>The query parameters declared on GET /seats/{class}.</summary>
public sealed record GetSeatQuery
{
    [JsonPropertyName("from")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateOnly? From { get; init; }

    [JsonPropertyName("in")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? In { get; init; }

    [JsonPropertyName("pageSize")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? PageSize { get; init; }
}

/// <summary>The request headers declared on GET /seats/{class}.</summary>
public sealed record GetSeatHeaders
{
    [JsonPropertyName("from")]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? From { get; init; }
}

/// <summary>Response headers declared on GET /seats/{class}.</summary>
public sealed record GetSeatResponseHeaders(string? From);

/// <summary>The body of GET /seats/{class}, with the response headers the contract declares.</summary>
public sealed record GetSeatResult(Seat Data, GetSeatResponseHeaders Headers);
