// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Net.Http;
using System.Numerics;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;
using Example.Sdk.Models;
using Example.Sdk.Runtime;

namespace Example.Sdk.Clients;

/// <summary>Operations declared in &lt;c&gt;simple.ck&lt;/c&gt;.</summary>
public sealed class SimpleClient(SdkHttp http)
{
    /// <summary>current service status</summary>
    public async Task<Heartbeat> GetStatusAsync(CancellationToken cancellationToken = default)
    {
        var response = await http.ExecuteAsync(
            HttpMethod.Get,
            http.Path("status"),
            cancellationToken: cancellationToken).ConfigureAwait(false);
        return http.ReadJson<Heartbeat>(response);
    }
}
