import { resolve, join } from 'node:path';
import type { ContractKitPlugin } from '@maroonedsoftware/contractkit';
import { generatePydanticModels, deriveModelsModuleName } from './codegen-models.js';
import {
    generatePythonClient,
    deriveClientClassName,
    deriveClientModuleName,
    deriveClientPropertyName,
    hasPublicOperations,
    BASE_CLIENT_PY,
} from './codegen-client.js';

export interface PythonSdkPluginConfig {
    /** Output directory relative to rootDir (default: "python-sdk") */
    baseDir?: string;
    /** Python package name used in the aggregator class name (default: "Sdk") */
    packageName?: string;
    /**
     * Whether to emit client methods for operations marked `internal`. Defaults to `false` —
     * internal ops are omitted so consumers don't pick them up. Set to `true` for an
     * internal-use SDK that should expose them.
     */
    includeInternal?: boolean;
}

// ─── Default export: loaded via plugins array, reads config from ctx.options ─

const plugin: ContractKitPlugin = {
    name: 'python-sdk',
    cacheKey: 'python-sdk',
    async generateTargets(inputs, ctx) {
        const config = ctx.options as PythonSdkPluginConfig;
        return createPythonSdkPlugin(config, ctx.rootDir).generateTargets!(inputs, ctx);
    },
};

export default plugin;

// ─── Factory: for programmatic use with explicit config ────────────────────

export function createPythonSdkPlugin(config: PythonSdkPluginConfig, rootDir: string): ContractKitPlugin {
    return {
        name: 'python-sdk',
        cacheKey: `python-sdk:${JSON.stringify(config)}`,
        async generateTargets({ contractRoots, opRoots, modelsWithInput: _modelsWithInput }, ctx) {
            const modelsWithInput = _modelsWithInput as Set<string>;
            const outDir = resolve(rootDir, config.baseDir ?? 'python-sdk');

            // ── Build model module path map ──
            // model name → importable Python module string, e.g. "._models_payment"
            const modelModulePaths = new Map<string, string>();
            const contractEntries: { moduleName: string; outPath: string; root: typeof contractRoots[number] }[] = [];

            for (const contractRoot of contractRoots) {
                const moduleName = deriveModelsModuleName(contractRoot.file);
                const outPath = join(outDir, `${moduleName}.py`);
                contractEntries.push({ moduleName, outPath, root: contractRoot });

                for (const model of contractRoot.models) {
                    modelModulePaths.set(model.name, `.${moduleName}`);
                    if (modelsWithInput.has(model.name)) {
                        modelModulePaths.set(`${model.name}Input`, `.${moduleName}`);
                    }
                }
            }

            // ── Emit model files ──
            for (const { moduleName, outPath, root } of contractEntries) {
                const content = generatePydanticModels(root, {
                    modelModulePaths,
                    currentModule: `.${moduleName}`,
                    modelsWithInput,
                });
                ctx.emitFile(outPath, content);
            }

            // ── Emit client files ──
            const clientInfos: { moduleName: string; className: string; propertyName: string }[] = [];
            for (const opRoot of opRoots) {
                if (!hasPublicOperations(opRoot, config.includeInternal)) continue;
                const moduleName = deriveClientModuleName(opRoot.file);
                const outPath = join(outDir, `${moduleName}.py`);
                clientInfos.push({
                    moduleName,
                    className: deriveClientClassName(opRoot.file),
                    propertyName: deriveClientPropertyName(opRoot.file),
                });
                ctx.emitFile(outPath, generatePythonClient(opRoot, {
                    modelModulePaths,
                    currentModule: `.${moduleName}`,
                    modelsWithInput,
                    includeInternal: config.includeInternal,
                }));
            }

            // ── Emit shared _base_client.py ──
            ctx.emitFile(join(outDir, '_base_client.py'), BASE_CLIENT_PY);

            // ── Emit requirements.txt ──
            ctx.emitFile(join(outDir, 'requirements.txt'), 'httpx\npydantic>=2.0\n');

            // ── Emit __init__.py aggregator ──
            const sdkClassName = config.packageName
                ? config.packageName
                    .split(/[-._\s]+/)
                    .map(s => s.charAt(0).toUpperCase() + s.slice(1))
                    .join('') + 'Sdk'
                : 'Sdk';

            const initLines: string[] = [
                '# Auto-generated by contractkit-plugin-python-sdk. Do not edit manually.',
                'from ._base_client import BaseClient, SdkError',
            ];
            for (const c of clientInfos) {
                initLines.push(`from .${c.moduleName} import ${c.className}`);
            }
            initLines.push('');
            initLines.push('');
            if (clientInfos.length > 0) {
                initLines.push(`class ${sdkClassName}(BaseClient):`);
                initLines.push(`    def __init__(self, base_url: str, headers: dict[str, str] | None = None):`);
                initLines.push(`        super().__init__(base_url, headers)`);
                for (const c of clientInfos) {
                    initLines.push(`        self.${c.propertyName} = ${c.className}(base_url, headers)`);
                }
                initLines.push('');
            } else {
                initLines.push(`class ${sdkClassName}(BaseClient):`);
                initLines.push(`    pass`);
                initLines.push('');
            }

            const allNames = ['BaseClient', 'SdkError', sdkClassName, ...clientInfos.map(c => c.className)];
            initLines.push(`__all__ = [${allNames.map(n => JSON.stringify(n)).join(', ')}]`);
            initLines.push('');

            ctx.emitFile(join(outDir, '__init__.py'), initLines.join('\n'));
        },
    };
}
