import { describe, expect, it } from 'vitest';
import { generateRuntimeCs } from '../src/runtime.js';
import { generateConvertersCs } from '../src/runtime-converters.js';
import { generatePolyfillsCs } from '../src/runtime-polyfills.js';
import { generateSdkCs } from '../src/codegen-sdk.js';

describe('generateRuntimeCs', () => {
    const out = generateRuntimeCs('Acme.Sdk');

    it('declares the runtime namespace and the generated-file header', () => {
        expect(out).toContain('namespace Acme.Sdk.Runtime;');
        expect(out.startsWith('// <auto-generated/>')).toBe(true);
        // `<auto-generated/>` turns the nullable context off, so it has to be turned back on.
        expect(out).toContain('#nullable enable');
    });

    it('exposes the surface generated clients are written against', () => {
        expect(out).toContain('public sealed class SdkHttp : IDisposable');
        expect(out).toContain('public async Task<SdkResponse> ExecuteAsync(');
        expect(out).toContain('public T ReadJson<T>(SdkResponse response)');
        expect(out).toContain('public string RequireHeader(SdkResponse response, string name)');
        expect(out).toContain('public string Path(params string[] segments)');
        expect(out).toContain('public string Segment<T>(T value)');
        expect(out).toContain('public IEnumerable<KeyValuePair<string, string>> Params<T>(T value)');
    });

    it('carries a PATCH verb of its own, the one HttpMethod does not spell on every framework', () => {
        expect(out).toContain('public static readonly HttpMethod Patch = new HttpMethod("PATCH");');
    });

    it('offers a content factory per request body kind', () => {
        expect(out).toContain('public HttpContent JsonContent<T>(T value, string mediaType)');
        expect(out).toContain('public HttpContent FormContent<T>(T value)');
        expect(out).toContain('public HttpContent MultipartContent(IEnumerable<SdkPart> parts)');
        expect(out).toContain('public HttpContent TextContent(string value, string mediaType)');
        expect(out).toContain('public HttpContent BinaryContent(byte[] value, string mediaType)');
    });

    it('derives the error from HttpRequestException, so callers of the base type still catch it', () => {
        expect(out).toContain('public class SdkException : HttpRequestException');
        expect(out).toContain('public T? TryReadBody<T>(JsonSerializerOptions? options = null)');
    });

    it('throws only for a status outside 2xx that the operation did not declare', () => {
        expect(out).toContain('if ((status < 200 || status > 299) && (expectStatuses is null || !expectStatuses.Contains(status)))');
    });

    it('reads the body eagerly, which is what lets a method switch on status and then decode', () => {
        expect(out).toContain('HttpCompletionOption.ResponseContentRead');
        expect(out).toContain('ReadAsByteArrayAsync');
    });

    it('strips content-type parameters, so a charset does not defeat a mime comparison', () => {
        expect(out).toContain('Message.Content.Headers.ContentType?.MediaType');
    });

    it('disposes a client it created and leaves a caller-supplied one alone', () => {
        expect(out).toContain('_ownsClient = options.HttpClient is null;');
        expect(out).toContain('if (_ownsClient) Client.Dispose();');
    });

    it('takes the older spelling of the two members netstandard2.0 declares differently', () => {
        // HttpRequestException gained a status-carrying constructor in .NET 5, and
        // ReadAsByteArrayAsync a cancellable overload; both have a fallback on the old framework.
        expect(out).toContain('        : base(message ?? $"Request failed with status {status}")\n#else');
        expect(out).toContain('var bytes = await message.Content.ReadAsByteArrayAsync().ConfigureAwait(false);');
        // The status conversion has no caller on the old framework, so it is not compiled there.
        expect(out).toContain('#if !NETSTANDARD2_0\n    private static HttpStatusCode? ToStatusCode(int status)');
    });
});

describe('generatePolyfillsCs', () => {
    const out = generatePolyfillsCs('Acme.Sdk');

    it('compiles on netstandard2.0 alone, so a project with no old leg carries nothing', () => {
        expect(out).toContain('#if NETSTANDARD2_0');
        expect(out.trimEnd().endsWith('#endif')).toBe(true);
    });

    it('declares the attributes the compiler looks for before it accepts init and required', () => {
        expect(out).toContain('namespace System.Runtime.CompilerServices');
        expect(out).toContain('internal static class IsExternalInit');
        expect(out).toContain('internal sealed class RequiredMemberAttribute : Attribute');
        expect(out).toContain('internal sealed class CompilerFeatureRequiredAttribute : Attribute');
        expect(out).toContain('internal sealed class SetsRequiredMembersAttribute : Attribute');
    });

    it('declares the date and time types in the SDK’s own namespace, not in System', () => {
        expect(out).toContain('namespace Acme.Sdk.Runtime');
        expect(out).toContain('public readonly struct DateOnly : IEquatable<DateOnly>, IComparable<DateOnly>, IComparable');
        expect(out).toContain('public readonly struct TimeOnly : IEquatable<TimeOnly>, IComparable<TimeOnly>, IComparable');
        expect(out).not.toContain('namespace System;');
    });

    it('writes the same wire form the framework types do, so one service reads either leg', () => {
        expect(out).toContain(`_value.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)`);
        expect(out).toContain(`_value.ToString("hh':'mm':'ss", CultureInfo.InvariantCulture)`);
        // Seven digits, not the trimmed form: System.Text.Json writes 09:30:15.2500000.
        expect(out).toContain(`_value.ToString("hh':'mm':'ss'.'fffffff", CultureInfo.InvariantCulture)`);
        // Reading stays lenient, so a body written by a trimming client still parses.
        expect(out).toContain(`{ "HH:mm:ss.FFFFFFF", "HH:mm" }`);
    });

    it('converts to the types a XAML picker binds to', () => {
        expect(out).toContain('public DateTime ToDateTime()');
        expect(out).toContain('public TimeSpan ToTimeSpan()');
        expect(out).toContain('public static TimeOnly FromTimeSpan(TimeSpan value)');
        expect(out).toContain('public static DateOnly FromDateTime(DateTime value)');
    });
});

describe('generateConvertersCs', () => {
    const out = generateConvertersCs('Acme.Sdk');

    it('registers exactly the scalar converters an attribute cannot carry', () => {
        expect(out).toContain('public static readonly JsonSerializerOptions Options = CreateOptions();');
        expect(out).toContain('options.Converters.Add(new BigIntegerConverter());');
        expect(out).toContain('options.Converters.Add(new DecimalStringConverter());');
        expect(out).toContain('options.Converters.Add(new IsoTimeSpanConverter());');
    });

    it('writes a decimal as a quoted string and refuses to read an unquoted number', () => {
        expect(out).toContain('public sealed class DecimalStringConverter : JsonConverter<decimal>');
        expect(out).toContain('throw new JsonException($"Expected a quoted decimal string, got {reader.TokenType}.");');
        expect(out).toContain('writer.WriteStringValue(value.ToString(CultureInfo.InvariantCulture));');
    });

    it('reads the bigint forms every other ContractKit SDK writes', () => {
        expect(out).toContain("BigInteger.Parse(text.TrimEnd('n'), NumberStyles.Integer, CultureInfo.InvariantCulture)");
        // Both branches copy to an array: the span overload of GetString is not on every framework.
        expect(out).toContain('reader.HasValueSequence ? reader.ValueSequence.ToArray() : reader.ValueSpan.ToArray()');
    });

    it('carries a duration as ISO 8601 rather than the BCL default', () => {
        expect(out).toContain('XmlConvert.ToTimeSpan(text)');
        expect(out).toContain('writer.WriteStringValue(XmlConvert.ToString(value));');
    });

    it('registers a date and time converter only where those types are the SDK’s own', () => {
        expect(out).toContain('#if NETSTANDARD2_0');
        expect(out).toContain('options.Converters.Add(new DateOnlyConverter());');
        expect(out).toContain('options.Converters.Add(new TimeOnlyConverter());');
        expect(out).toContain('public sealed class DateOnlyConverter : JsonConverter<DateOnly>');
        expect(out).toContain('public sealed class TimeOnlyConverter : JsonConverter<TimeOnly>');
    });
});

describe('generateSdkCs', () => {
    it('shares one SdkHttp across every client, so the SDK keeps one connection pool', () => {
        const out = generateSdkCs('Acme.Sdk', 'AcmeSdk', [
            { className: 'BillingClient', propertyName: 'Billing' },
            { className: 'InvoicesClient', propertyName: 'Invoices' },
        ]);
        expect(out).toContain('public sealed class AcmeSdk : IDisposable');
        expect(out).toContain('Http = new SdkHttp(options);');
        expect(out).toContain('Billing = new BillingClient(Http);');
        expect(out).toContain('Invoices = new InvoicesClient(Http);');
        expect(out).toContain('public BillingClient Billing { get; }');
        expect(out).toContain('using Acme.Sdk.Clients;');
    });

    it('compiles with no clients at all, and then imports no client namespace', () => {
        const out = generateSdkCs('Acme.Sdk', 'Sdk', []);
        expect(out).toContain('public sealed class Sdk : IDisposable');
        expect(out).not.toContain('using Acme.Sdk.Clients;');
    });
});
