/**
 * The `Runtime/Polyfills.cs` file: what .NET Standard 2.0 does not carry.
 *
 * Emitted only when the SDK targets netstandard2.0, and compiled only on that leg of a multi-target
 * build, so a project on net10.0 alone never sees any of it. Two groups, for two different reasons:
 *
 * - The attributes the C# compiler looks for before it will accept an `init` accessor, a `required`
 *   member, or the records built on them. The compiler asks for these by full name and does not care
 *   which assembly declares them, so `internal` copies are enough and cannot collide with a
 *   consumer's own.
 * - `DateOnly` and `TimeOnly`, which arrived in .NET 6. These are declared in the SDK's own runtime
 *   namespace rather than in `System`, because a consumer is free to reference a package that
 *   backfills `System.DateOnly` for their own code and two declarations of one full name are
 *   ambiguous wherever they meet. Generated files import the runtime namespace, so `DateOnly`
 *   resolves to the polyfill here on netstandard2.0 and to the framework's type on net10.0 without a
 *   line of conditional code in a model.
 */

/** Generate `Runtime/Polyfills.cs` for `namespaceName`. Content depends on nothing but the namespace. */
export function generatePolyfillsCs(namespaceName: string): string {
    return `// <auto-generated/>
// Generated by @contractkit/plugin-csharp. Do not edit manually.
#nullable enable

#if NETSTANDARD2_0

using System;
using System.Globalization;

namespace System.Runtime.CompilerServices
{
    /// <summary>
    /// The marker the compiler requires before it will emit an <c>init</c> accessor.
    /// </summary>
    internal static class IsExternalInit
    {
    }

    /// <summary>
    /// Marks a member whose initialization the compiler requires at every construction site.
    /// </summary>
    [AttributeUsage(AttributeTargets.Field | AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    internal sealed class RequiredMemberAttribute : Attribute
    {
    }

    /// <summary>
    /// Names a compiler feature a member depends on, so a compiler that does not have it refuses the
    /// member rather than misreading it.
    /// </summary>
    [AttributeUsage(AttributeTargets.All, AllowMultiple = true, Inherited = false)]
    internal sealed class CompilerFeatureRequiredAttribute : Attribute
    {
        public CompilerFeatureRequiredAttribute(string featureName)
        {
            FeatureName = featureName;
        }

        public string FeatureName { get; }

        public bool IsOptional { get; init; }

        public const string RefStructs = nameof(RefStructs);

        public const string RequiredMembers = nameof(RequiredMembers);
    }
}

namespace System.Diagnostics.CodeAnalysis
{
    /// <summary>
    /// Marks a constructor that sets every required member itself.
    /// </summary>
    [AttributeUsage(AttributeTargets.Constructor, AllowMultiple = false, Inherited = false)]
    internal sealed class SetsRequiredMembersAttribute : Attribute
    {
    }
}

namespace ${namespaceName}.Runtime
{
    /// <summary>
    /// A calendar date with no time and no offset. Stands in for <c>System.DateOnly</c>.
    /// </summary>
    /// <remarks>
    /// Carries what a generated SDK and the code around it need: construction, ordering, conversion
    /// to and from <see cref="DateTime"/>, and the <c>yyyy-MM-dd</c> form a contract's <c>date</c>
    /// travels as. Not a complete reimplementation of the framework type.
    /// </remarks>
    public readonly struct DateOnly : IEquatable<DateOnly>, IComparable<DateOnly>, IComparable
    {
        private readonly DateTime _value;

        public DateOnly(int year, int month, int day)
        {
            _value = new DateTime(year, month, day);
        }

        private DateOnly(DateTime value)
        {
            _value = value.Date;
        }

        public static DateOnly MinValue => new DateOnly(DateTime.MinValue);

        public static DateOnly MaxValue => new DateOnly(DateTime.MaxValue);

        public int Year => _value.Year;

        public int Month => _value.Month;

        public int Day => _value.Day;

        public int DayOfYear => _value.DayOfYear;

        public DayOfWeek DayOfWeek => _value.DayOfWeek;

        /// <summary>The date part of <paramref name="value"/>, dropping its time and kind.</summary>
        public static DateOnly FromDateTime(DateTime value) => new DateOnly(value);

        /// <summary>This date at midnight, with an unspecified kind. What a XAML date picker binds to.</summary>
        public DateTime ToDateTime() => _value;

        /// <summary>This date at <paramref name="time"/>, with an unspecified kind.</summary>
        public DateTime ToDateTime(TimeOnly time) => _value.Add(time.ToTimeSpan());

        public DateOnly AddDays(int value) => new DateOnly(_value.AddDays(value));

        public DateOnly AddMonths(int value) => new DateOnly(_value.AddMonths(value));

        public DateOnly AddYears(int value) => new DateOnly(_value.AddYears(value));

        public static DateOnly Parse(string s) => Parse(s, CultureInfo.InvariantCulture);

        /// <exception cref="FormatException">When <paramref name="s"/> is not a date.</exception>
        public static DateOnly Parse(string s, IFormatProvider? provider)
        {
            if (!TryParse(s, provider, out var result))
            {
                throw new FormatException("'" + s + "' is not a date.");
            }

            return result;
        }

        public static bool TryParse(string? s, out DateOnly result) => TryParse(s, CultureInfo.InvariantCulture, out result);

        /// <remarks>
        /// The wire form is tried first and exactly; anything else the culture reads as a date is
        /// then taken by its date part, which is what the framework type does too.
        /// </remarks>
        public static bool TryParse(string? s, IFormatProvider? provider, out DateOnly result)
        {
            var culture = provider ?? CultureInfo.InvariantCulture;
            if (DateTime.TryParseExact(s, "yyyy-MM-dd", culture, DateTimeStyles.None, out var exact))
            {
                result = new DateOnly(exact);
                return true;
            }

            if (DateTime.TryParse(s, culture, DateTimeStyles.None, out var parsed))
            {
                result = new DateOnly(parsed);
                return true;
            }

            result = default;
            return false;
        }

        /// <summary>The ISO 8601 form, <c>yyyy-MM-dd</c>. Also how the date travels on the wire.</summary>
        public override string ToString() => _value.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);

        public string ToString(string? format) => _value.ToString(format, CultureInfo.InvariantCulture);

        public string ToString(string? format, IFormatProvider? provider) => _value.ToString(format, provider);

        public bool Equals(DateOnly other) => _value == other._value;

        public override bool Equals(object? obj) => obj is DateOnly other && Equals(other);

        public override int GetHashCode() => _value.GetHashCode();

        public int CompareTo(DateOnly other) => _value.CompareTo(other._value);

        public int CompareTo(object? obj)
        {
            if (obj is null) return 1;
            if (obj is DateOnly other) return CompareTo(other);
            throw new ArgumentException("Object must be of type DateOnly.", nameof(obj));
        }

        public static bool operator ==(DateOnly left, DateOnly right) => left.Equals(right);

        public static bool operator !=(DateOnly left, DateOnly right) => !left.Equals(right);

        public static bool operator <(DateOnly left, DateOnly right) => left.CompareTo(right) < 0;

        public static bool operator <=(DateOnly left, DateOnly right) => left.CompareTo(right) <= 0;

        public static bool operator >(DateOnly left, DateOnly right) => left.CompareTo(right) > 0;

        public static bool operator >=(DateOnly left, DateOnly right) => left.CompareTo(right) >= 0;
    }

    /// <summary>
    /// A time of day with no date and no offset. Stands in for <c>System.TimeOnly</c>.
    /// </summary>
    /// <remarks>
    /// At least zero and less than 24 hours, which is what separates it from the
    /// <see cref="TimeSpan"/> a contract's <c>duration</c> maps to.
    /// </remarks>
    public readonly struct TimeOnly : IEquatable<TimeOnly>, IComparable<TimeOnly>, IComparable
    {
        private static readonly TimeSpan OneDay = TimeSpan.FromDays(1);

        /// <summary>Accepted on the way in: the wire form, with or without a fraction, and <c>HH:mm</c>.</summary>
        private static readonly string[] Formats = { "HH:mm:ss.FFFFFFF", "HH:mm" };

        private readonly TimeSpan _value;

        public TimeOnly(int hour, int minute)
            : this(new TimeSpan(hour, minute, 0))
        {
        }

        public TimeOnly(int hour, int minute, int second)
            : this(new TimeSpan(hour, minute, second))
        {
        }

        public TimeOnly(int hour, int minute, int second, int millisecond)
            : this(new TimeSpan(0, hour, minute, second, millisecond))
        {
        }

        private TimeOnly(TimeSpan value)
        {
            if (value < TimeSpan.Zero || value >= OneDay)
            {
                throw new ArgumentOutOfRangeException(nameof(value), "A time of day is at least zero and less than 24 hours.");
            }

            _value = value;
        }

        public static TimeOnly MinValue => new TimeOnly(TimeSpan.Zero);

        public static TimeOnly MaxValue => new TimeOnly(OneDay - TimeSpan.FromTicks(1));

        public int Hour => _value.Hours;

        public int Minute => _value.Minutes;

        public int Second => _value.Seconds;

        public int Millisecond => _value.Milliseconds;

        public long Ticks => _value.Ticks;

        /// <summary>The time part of <paramref name="value"/>.</summary>
        public static TimeOnly FromDateTime(DateTime value) => new TimeOnly(value.TimeOfDay);

        /// <exception cref="ArgumentOutOfRangeException">When <paramref name="value"/> is negative or a day or more.</exception>
        public static TimeOnly FromTimeSpan(TimeSpan value) => new TimeOnly(value);

        /// <summary>This time as a span since midnight. What a XAML time picker binds to.</summary>
        public TimeSpan ToTimeSpan() => _value;

        public static TimeOnly Parse(string s) => Parse(s, CultureInfo.InvariantCulture);

        /// <exception cref="FormatException">When <paramref name="s"/> is not a time of day.</exception>
        public static TimeOnly Parse(string s, IFormatProvider? provider)
        {
            if (!TryParse(s, provider, out var result))
            {
                throw new FormatException("'" + s + "' is not a time of day.");
            }

            return result;
        }

        public static bool TryParse(string? s, out TimeOnly result) => TryParse(s, CultureInfo.InvariantCulture, out result);

        public static bool TryParse(string? s, IFormatProvider? provider, out TimeOnly result)
        {
            var culture = provider ?? CultureInfo.InvariantCulture;
            if (DateTime.TryParseExact(s, Formats, culture, DateTimeStyles.None, out var exact))
            {
                result = new TimeOnly(exact.TimeOfDay);
                return true;
            }

            if (DateTime.TryParse(s, culture, DateTimeStyles.None, out var parsed))
            {
                result = new TimeOnly(parsed.TimeOfDay);
                return true;
            }

            result = default;
            return false;
        }

        /// <summary>
        /// The ISO 8601 form: <c>HH:mm:ss</c>, and a fraction of seven digits when there is one.
        /// </summary>
        /// <remarks>
        /// Byte for byte what System.Text.Json's own converter writes for a <c>TimeOnly</c> on
        /// net10.0 — including the seven digits, which it does not trim — so a service cannot tell
        /// which leg of the build sent a body.
        /// </remarks>
        public override string ToString() =>
            _value.Ticks % TimeSpan.TicksPerSecond == 0
                ? _value.ToString("hh':'mm':'ss", CultureInfo.InvariantCulture)
                : _value.ToString("hh':'mm':'ss'.'fffffff", CultureInfo.InvariantCulture);

        public string ToString(string? format) => _value.ToString(format, CultureInfo.InvariantCulture);

        public string ToString(string? format, IFormatProvider? provider) => _value.ToString(format, provider);

        public bool Equals(TimeOnly other) => _value == other._value;

        public override bool Equals(object? obj) => obj is TimeOnly other && Equals(other);

        public override int GetHashCode() => _value.GetHashCode();

        public int CompareTo(TimeOnly other) => _value.CompareTo(other._value);

        public int CompareTo(object? obj)
        {
            if (obj is null) return 1;
            if (obj is TimeOnly other) return CompareTo(other);
            throw new ArgumentException("Object must be of type TimeOnly.", nameof(obj));
        }

        public static bool operator ==(TimeOnly left, TimeOnly right) => left.Equals(right);

        public static bool operator !=(TimeOnly left, TimeOnly right) => !left.Equals(right);

        public static bool operator <(TimeOnly left, TimeOnly right) => left.CompareTo(right) < 0;

        public static bool operator <=(TimeOnly left, TimeOnly right) => left.CompareTo(right) <= 0;

        public static bool operator >(TimeOnly left, TimeOnly right) => left.CompareTo(right) > 0;

        public static bool operator >=(TimeOnly left, TimeOnly right) => left.CompareTo(right) >= 0;
    }
}

#endif
`;
}
