import { kdocLines } from './naming.js';

export interface SdkAggregatorClient {
    className: string;
    propertyName: string;
}

/**
 * Generate the SDK entry point: one property per generated client, all sharing a single
 * [SdkHttp] and therefore a single Ktor `HttpClient`.
 *
 * The Python SDK gives each sub-client its own connection pool; that is a bug worth not repeating,
 * since a caller holding one SDK expects one set of connections.
 */
export function generateSdkKt(packageName: string, sdkName: string, clients: readonly SdkAggregatorClient[]): string {
    const lines: string[] = ['// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.'];
    lines.push(`package ${packageName}`);
    lines.push('');
    for (const client of clients) lines.push(`import ${packageName}.clients.${client.className}`);
    lines.push(`import ${packageName}.runtime.SdkConfig`);
    lines.push(`import ${packageName}.runtime.SdkHttp`);
    lines.push('');
    lines.push(
        ...kdocLines(
            'Entry point to the generated SDK.\n\n' +
                'Holds one [SdkHttp], shared by every client, so the SDK keeps a single connection pool.\n' +
                'Closing it closes the underlying Ktor client, unless you supplied your own.',
            '',
        ),
    );
    lines.push(`class ${sdkName}(config: SdkConfig) : AutoCloseable {`);
    lines.push('    val http: SdkHttp = SdkHttp(config)');
    for (const client of clients) {
        lines.push(`    val ${client.propertyName}: ${client.className} = ${client.className}(http)`);
    }
    lines.push('');
    lines.push('    override fun close() {');
    lines.push('        http.close()');
    lines.push('    }');
    lines.push('}');
    lines.push('');
    return lines.join('\n');
}
