import type { ContractRootNode, ContractTypeNode, FieldNode, ModelNode, ScalarTypeNode } from '@contractkit/core';
import { buildModelIndex, computeModelsWithInput, resolveEffectiveFields, topoSortModels } from '@contractkit/core';
import { kdocLines, toKotlinEnumEntryName, toKotlinPropertyName } from './naming.js';

// ─── Public entry point ────────────────────────────────────────────────────

export interface KotlinModelCodegenOptions {
    /** Kotlin package the SDK is generated into. Models land in `<packageName>.models`. */
    packageName: string;
    /** Model names that have a distinct `Input` variant, including ones declared in other files. */
    modelsWithInput?: ReadonlySet<string>;
    /**
     * Every model in the project, for flattening bases and intersections. Defaults to an index of
     * this root's own models, which is enough for a single-file project and for unit tests.
     */
    modelIndex?: ReadonlyMap<string, ModelNode>;
    warn?: (message: string) => void;
}

/**
 * Generate the Kotlin models file for one contract root: a `@Serializable data class` per model,
 * plus `<Name>Input` variants, enum classes, and type aliases.
 *
 * Every model in the project shares the single `<packageName>.models` package, so a reference to a
 * model declared in another `.ck` file needs no import and resolves by name alone.
 */
export function generateKotlinModels(root: ContractRootNode, opts: KotlinModelCodegenOptions): string {
    const externalModelsWithInput = new Set(opts.modelsWithInput ?? []);
    const localModelsWithInput = computeModelsWithInput(root.models, externalModelsWithInput);
    const modelsWithInput = new Set([...localModelsWithInput, ...externalModelsWithInput]);
    const modelIndex = opts.modelIndex ?? buildModelIndex(root.models);

    const ctx: RenderContext = {
        packageName: opts.packageName,
        modelsWithInput,
        modelIndex,
        imports: new ImportTracker(),
        warn: opts.warn,
    };

    const bodies: string[] = [];
    for (const model of topoSortModels(root.models)) {
        bodies.push('');
        bodies.push(...generateModel(model, ctx));
    }

    return renderFile(`${opts.packageName}.models`, ctx.imports, bodies);
}

// ─── Render context and imports ────────────────────────────────────────────

interface RenderContext {
    packageName: string;
    modelsWithInput: ReadonlySet<string>;
    modelIndex: ReadonlyMap<string, ModelNode>;
    imports: ImportTracker;
    warn?: (message: string) => void;
}

/**
 * Collects the fully-qualified names a generated file imports. Kotlin has no import grouping
 * convention the compiler enforces, so one sorted block keeps the output stable across runs.
 */
export class ImportTracker {
    private readonly names = new Set<string>();
    /** Opt-in markers that have to appear in a `@file:OptIn(...)` annotation above `package`. */
    private readonly optIns = new Set<string>();

    add(fqName: string): void {
        this.names.add(fqName);
    }

    /** Require `@file:OptIn(<marker>::class)`; `fqName` is the marker annotation's own import. */
    addOptIn(marker: string, fqName: string): void {
        this.optIns.add(marker);
        this.names.add(fqName);
    }

    render(): string[] {
        return [...this.names].sort().map(n => `import ${n}`);
    }

    renderFileOptIn(): string[] {
        if (this.optIns.size === 0) return [];
        const markers = [...this.optIns].sort().map(m => `${m}::class`);
        return [`@file:OptIn(${markers.join(', ')})`, ''];
    }
}

/** Assemble a generated Kotlin file: header, file-level opt-ins, package, imports, then bodies. */
export function renderFile(packageName: string, imports: ImportTracker, bodies: string[]): string {
    const lines: string[] = ['// Auto-generated by @contractkit/plugin-kotlin. Do not edit manually.'];
    lines.push(...imports.renderFileOptIn());
    lines.push(`package ${packageName}`);
    const importLines = imports.render();
    if (importLines.length > 0) {
        lines.push('');
        lines.push(...importLines);
    }
    lines.push(...bodies);
    lines.push('');
    return lines.join('\n');
}

// ─── Type rendering ────────────────────────────────────────────────────────

/**
 * Render a ContractKit type as its Kotlin type expression. Never returns a nullable type — the
 * caller appends `?` from the field's own `optional`/`nullable` flags.
 *
 * @param forInput - When true, a `ref` to a model with an Input variant renders as `<Name>Input`.
 * @throws {Error} Via the scalar renderer, if a scalar has no Kotlin mapping.
 */
export function renderKotlinType(type: ContractTypeNode, ctx: RenderContext, forInput = false): string {
    switch (type.kind) {
        case 'scalar':
            return renderScalar(type.name, ctx);
        case 'literal':
            return literalKotlinType(type.value);
        case 'array':
            return `List<${renderKotlinType(type.item, ctx, forInput)}>`;
        case 'record': {
            const key = renderKotlinType(type.key, ctx, forInput);
            const value = renderKotlinType(type.value, ctx, forInput);
            if (key !== 'String') {
                ctx.warn?.(
                    `A record key of type '${key}' is not representable as a JSON object key; emitting Map<String, ${value}>. ` +
                        `Parse the key yourself, or declare the key as a string.`,
                );
                return `Map<String, ${value}>`;
            }
            return `Map<String, ${value}>`;
        }
        case 'tuple':
            return renderTuple(type.items, ctx, forInput);
        case 'ref':
            return forInput && ctx.modelsWithInput.has(type.name) ? `${type.name}Input` : type.name;
        case 'lazy':
            return renderKotlinType(type.inner, ctx, forInput);
        // Phase 1 fallbacks. Each becomes a named declaration once hoisting lands.
        case 'enum':
            return renderScalar('string', ctx);
        case 'inlineObject':
        case 'intersection':
            ctx.imports.add('kotlinx.serialization.json.JsonObject');
            return 'JsonObject';
        case 'union':
        case 'discriminatedUnion':
            ctx.imports.add('kotlinx.serialization.json.JsonElement');
            return 'JsonElement';
    }
}

/**
 * A 2- or 3-tuple maps onto Kotlin's own `Pair`/`Triple`, serialized as a JSON array by a runtime
 * serializer the field carries as an annotation. Any other arity, and any tuple nested inside a
 * collection, falls back to `JsonArray`: a property-level `@Serializable(with = ...)` applies to the
 * property's own type, so it cannot reach a tuple inside a `List`.
 */
function renderTuple(items: ContractTypeNode[], ctx: RenderContext, forInput: boolean): string {
    if (items.length === 2 || items.length === 3) {
        const rendered = items.map(t => renderKotlinType(t, ctx, forInput));
        return items.length === 2 ? `Pair<${rendered.join(', ')}>` : `Triple<${rendered.join(', ')}>`;
    }
    ctx.imports.add('kotlinx.serialization.json.JsonArray');
    return 'JsonArray';
}

/**
 * The `@Serializable(with = ...)` annotation a field needs for its own type, or `undefined`.
 * Only tuples need one: `Pair`/`Triple` would otherwise serialize as `{"first":…,"second":…}`.
 */
function typeSerializerAnnotation(type: ContractTypeNode, ctx: RenderContext): string | undefined {
    const inner = type.kind === 'lazy' ? type.inner : type;
    if (inner.kind !== 'tuple') return undefined;
    if (inner.items.length === 2) {
        ctx.imports.add(`${ctx.packageName}.runtime.PairAsArraySerializer`);
        ctx.imports.add('kotlinx.serialization.Serializable');
        return '@Serializable(with = PairAsArraySerializer::class)';
    }
    if (inner.items.length === 3) {
        ctx.imports.add(`${ctx.packageName}.runtime.TripleAsArraySerializer`);
        ctx.imports.add('kotlinx.serialization.Serializable');
        return '@Serializable(with = TripleAsArraySerializer::class)';
    }
    return undefined;
}

/**
 * Map a ContractKit scalar to its Kotlin Multiplatform type, registering the import it needs.
 *
 * @throws {Error} When a scalar has no mapping, so a scalar added to core fails the build here
 *   rather than emitting Kotlin that does not compile.
 */
export function renderScalar(name: ScalarTypeNode['name'], ctx: RenderContext): string {
    switch (name) {
        case 'string':
        case 'email':
        case 'url':
        case 'interval':
            return 'String';
        case 'number':
            return 'Double';
        // `int` is a JS safe integer in the source language, which overflows Kotlin's 32-bit Int.
        case 'int':
            return 'Long';
        case 'bigint':
            ctx.imports.add(`${ctx.packageName}.runtime.BigInt`);
            return 'BigInt';
        case 'decimal':
            ctx.imports.add(`${ctx.packageName}.runtime.Decimal`);
            return 'Decimal';
        case 'boolean':
            return 'Boolean';
        case 'date':
            ctx.imports.add('kotlinx.datetime.LocalDate');
            return 'LocalDate';
        case 'time':
            ctx.imports.add('kotlinx.datetime.LocalTime');
            return 'LocalTime';
        case 'datetime':
            ctx.imports.add('kotlin.time.Instant');
            return 'Instant';
        case 'duration':
            ctx.imports.add('kotlin.time.Duration');
            return 'Duration';
        case 'uuid':
            ctx.imports.addOptIn('ExperimentalUuidApi', 'kotlin.uuid.ExperimentalUuidApi');
            ctx.imports.add('kotlin.uuid.Uuid');
            return 'Uuid';
        case 'binary':
            return 'ByteArray';
        case 'null':
            return 'Nothing?';
        case 'unknown':
        case 'json':
        case 'object':
            ctx.imports.add('kotlinx.serialization.json.JsonElement');
            return 'JsonElement';
        default: {
            const _exhaustive: never = name;
            throw new Error(`plugin-kotlin: unmapped scalar '${String(_exhaustive)}' — add a case`);
        }
    }
}

function literalKotlinType(value: string | number | boolean): string {
    if (typeof value === 'string') return 'String';
    if (typeof value === 'boolean') return 'Boolean';
    return Number.isInteger(value) ? 'Long' : 'Double';
}

// ─── Default values ────────────────────────────────────────────────────────

/**
 * Render a contract default as a Kotlin expression of the field's own type. Returns `undefined`
 * when the value cannot be expressed (an identifier default naming something we cannot resolve),
 * so the field is emitted without an initializer rather than with one that will not compile.
 */
function renderDefault(value: string | number | boolean, type: ContractTypeNode, ctx: RenderContext): string | undefined {
    const inner = type.kind === 'lazy' ? type.inner : type;

    if (typeof value === 'boolean') return String(value);

    if (typeof value === 'number') {
        if (inner.kind === 'scalar') {
            switch (inner.name) {
                case 'int':
                    return `${value}L`;
                case 'number':
                    return Number.isInteger(value) ? `${value}.0` : String(value);
                case 'decimal':
                    ctx.imports.add(`${ctx.packageName}.runtime.Decimal`);
                    return `Decimal("${value}")`;
                case 'bigint':
                    ctx.imports.add(`${ctx.packageName}.runtime.BigInt`);
                    return `BigInt("${value}")`;
            }
        }
        return Number.isInteger(value) ? `${value}L` : String(value);
    }

    // A string default against an enum names one of its members, not a string literal.
    if (inner.kind === 'enum') return undefined;
    if (inner.kind === 'scalar') {
        switch (inner.name) {
            case 'decimal':
                ctx.imports.add(`${ctx.packageName}.runtime.Decimal`);
                return `Decimal(${quoteKotlinString(value)})`;
            case 'bigint':
                ctx.imports.add(`${ctx.packageName}.runtime.BigInt`);
                return `BigInt(${quoteKotlinString(value)})`;
            case 'string':
            case 'email':
            case 'url':
            case 'interval':
                return quoteKotlinString(value);
            default:
                // date/uuid/datetime and friends have no literal syntax; leave the field required.
                return undefined;
        }
    }
    return quoteKotlinString(value);
}

/** Quote a string as a Kotlin literal. `$` starts a template expression, so it is escaped too. */
export function quoteKotlinString(value: string): string {
    const escaped = value
        .replace(/\\/g, '\\\\')
        .replace(/"/g, '\\"')
        .replace(/\$/g, '\\$')
        .replace(/\n/g, '\\n')
        .replace(/\r/g, '\\r')
        .replace(/\t/g, '\\t');
    return `"${escaped}"`;
}

// ─── Model generation ──────────────────────────────────────────────────────

function generateModel(model: ModelNode, ctx: RenderContext): string[] {
    if (model.type) return generateAliasModel(model, ctx);

    const effective = effectiveFieldsFor(model, ctx);
    const needsSplit = ctx.modelsWithInput.has(model.name) || effective.some(f => f.visibility !== 'normal');

    if (!needsSplit) return generateDataClass(model.name, effective, ctx, false, model);

    const readFields = effective.filter(f => f.visibility !== 'writeonly');
    const inputFields = effective.filter(f => f.visibility !== 'readonly');
    return [
        ...generateDataClass(model.name, readFields, ctx, false, model),
        '',
        ...generateDataClass(`${model.name}Input`, inputFields, ctx, true, model),
    ];
}

/**
 * Bases are flattened rather than expressed as Kotlin inheritance: a `data class` cannot extend
 * another `data class`, and the language's own composition (an interface per base) would not give
 * the subclass the base's constructor properties. `resolveEffectiveFields` applies the same
 * later-wins override rule the inheritance validator enforces.
 */
function effectiveFieldsFor(model: ModelNode, ctx: RenderContext): FieldNode[] {
    if (!model.bases || model.bases.length === 0) return model.fields;
    const { fields, unresolved } = resolveEffectiveFields(model.name, ctx.modelIndex);
    for (const name of unresolved) {
        ctx.warn?.(`Contract '${model.name}' extends '${name}', which is not defined; its fields are missing from the generated class.`);
    }
    return fields;
}

function generateAliasModel(model: ModelNode, ctx: RenderContext): string[] {
    const type = model.type!;
    const inner = type.kind === 'lazy' ? type.inner : type;

    if (inner.kind === 'enum') {
        return generateEnumClass(model.name, inner.values, ctx, model);
    }
    // An intersection or inline object at model level names a real shape, so it becomes a class
    // rather than an alias to `JsonObject`.
    if (inner.kind === 'intersection' || inner.kind === 'inlineObject') {
        const { fields, unresolved } = resolveEffectiveFields(inner, ctx.modelIndex);
        for (const name of unresolved) {
            ctx.warn?.(`Contract '${model.name}' references '${name}', which is not defined; its fields are missing from the generated class.`);
        }
        const needsSplit = ctx.modelsWithInput.has(model.name) || fields.some(f => f.visibility !== 'normal');
        if (!needsSplit) return generateDataClass(model.name, fields, ctx, false, model);
        return [
            ...generateDataClass(
                model.name,
                fields.filter(f => f.visibility !== 'writeonly'),
                ctx,
                false,
                model,
            ),
            '',
            ...generateDataClass(
                `${model.name}Input`,
                fields.filter(f => f.visibility !== 'readonly'),
                ctx,
                true,
                model,
            ),
        ];
    }

    const lines: string[] = [];
    lines.push(...docLines(model.description, model.deprecated, ''));
    lines.push(`typealias ${model.name} = ${renderKotlinType(type, ctx, false)}`);
    if (ctx.modelsWithInput.has(model.name)) {
        lines.push(`typealias ${model.name}Input = ${renderKotlinType(type, ctx, true)}`);
    }
    return lines;
}

function generateEnumClass(name: string, values: string[], ctx: RenderContext, model?: ModelNode): string[] {
    ctx.imports.add('kotlinx.serialization.SerialName');
    ctx.imports.add('kotlinx.serialization.Serializable');

    const lines: string[] = [];
    lines.push(...docLines(model?.description, model?.deprecated, ''));
    lines.push('@Serializable');
    lines.push(`enum class ${name} {`);
    const used = new Set<string>();
    for (const value of values) {
        lines.push(`    @SerialName(${quoteKotlinString(value)})`);
        lines.push(`    ${uniqueName(toKotlinEnumEntryName(value), used)},`);
    }
    lines.push('}');
    // An enum needs no Input variant: it has no fields, so no visibility can differ.
    if (ctx.modelsWithInput.has(name)) lines.push(`typealias ${name}Input = ${name}`);
    return lines;
}

function generateDataClass(name: string, fields: FieldNode[], ctx: RenderContext, forInput: boolean, model: ModelNode): string[] {
    ctx.imports.add('kotlinx.serialization.Serializable');

    const lines: string[] = [];
    lines.push(...docLines(model.description, model.deprecated, ''));
    lines.push('@Serializable');

    // A `data class` needs at least one constructor property; a contract with no visible fields
    // still has to produce a serializable type.
    if (fields.length === 0) {
        lines.push(`class ${name}`);
        return lines;
    }

    lines.push(`data class ${name}(`);
    for (const field of fields) {
        lines.push(...renderField(field, ctx, forInput));
    }
    lines.push(')');
    return lines;
}

function renderField(field: FieldNode, ctx: RenderContext, forInput: boolean): string[] {
    const lines: string[] = [];
    const propName = toKotlinPropertyName(field.name);
    const wireName = propName.replace(/`/g, '');

    let typeStr = renderKotlinType(field.type, ctx, forInput);
    const explicitDefault = field.default !== undefined ? renderDefault(field.default, field.type, ctx) : undefined;
    const isOptional = field.optional || explicitDefault !== undefined;
    if ((field.nullable || isOptional) && !typeStr.endsWith('?')) typeStr += '?';

    let initializer: string | undefined = explicitDefault;
    if (initializer === undefined && field.optional) initializer = 'null';
    // A `literal()` field carries exactly one value, so it defaults to it rather than being asked
    // for at every call site. The value is put on the wire by `encodeDefaults` in the runtime Json.
    if (initializer === undefined && !field.optional && !field.nullable) {
        const inner = field.type.kind === 'lazy' ? field.type.inner : field.type;
        if (inner.kind === 'literal') {
            initializer = typeof inner.value === 'string' ? quoteKotlinString(inner.value) : renderDefault(inner.value, inner, ctx);
        }
    }

    lines.push(...docLines(field.description, field.deprecated, '    '));
    const annotations: string[] = [];
    const serializerAnnotation = typeSerializerAnnotation(field.type, ctx);
    if (serializerAnnotation) annotations.push(serializerAnnotation);
    if (wireName !== field.name) {
        ctx.imports.add('kotlinx.serialization.SerialName');
        annotations.push(`@SerialName(${quoteKotlinString(field.name)})`);
    }

    const prefix = annotations.length > 0 ? `${annotations.join(' ')} ` : '';
    const suffix = initializer !== undefined ? ` = ${initializer}` : '';
    lines.push(`    ${prefix}val ${propName}: ${typeStr}${suffix},`);
    return lines;
}

/**
 * KDoc for a declaration, with a `@deprecated` tag rather than the `@Deprecated` annotation for
 * fields: an annotated property makes a data class's own generated `copy` and `toString` warn.
 */
function docLines(description: string | undefined, deprecated: boolean | undefined, indent: string): string[] {
    const parts: string[] = [];
    if (description) parts.push(description);
    if (deprecated) parts.push('@deprecated');
    if (parts.length === 0) return [];
    return kdocLines(parts.join('\n'), indent);
}

function uniqueName(name: string, used: Set<string>): string {
    if (!used.has(name)) {
        used.add(name);
        return name;
    }
    let n = 2;
    while (used.has(`${name}${n}`)) n++;
    used.add(`${name}${n}`);
    return `${name}${n}`;
}

export type { RenderContext };
