// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// A customer payment
public struct Payment: Codable, Equatable, Sendable {
    public var id: UUID
    public var amount: Double
    public var unitPrice: DecimalValue
    public var quantity: BigIntValue
    public var createdAt: Date
    public var processingTime: IsoDuration?
    public var status: PaymentStatus

    public init(id: UUID, amount: Double, unitPrice: DecimalValue, quantity: BigIntValue, createdAt: Date, processingTime: IsoDuration? = nil, status: PaymentStatus = .pending) {
        self.id = id
        self.amount = amount
        self.unitPrice = unitPrice
        self.quantity = quantity
        self.createdAt = createdAt
        self.processingTime = processingTime
        self.status = status
    }

    private enum CodingKeys: String, CodingKey {
        case id = "id"
        case amount = "amount"
        case unitPrice = "unitPrice"
        case quantity = "quantity"
        case createdAt = "createdAt"
        case processingTime = "processingTime"
        case status = "status"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(UUID.self, forKey: .id)
        self.amount = try container.decode(Double.self, forKey: .amount)
        self.unitPrice = try container.decode(DecimalValue.self, forKey: .unitPrice)
        self.quantity = try container.decode(BigIntValue.self, forKey: .quantity)
        self.createdAt = try container.decode(Date.self, forKey: .createdAt)
        self.processingTime = try container.decodeIfPresent(IsoDuration.self, forKey: .processingTime)
        self.status = try container.decodeIfPresent(PaymentStatus.self, forKey: .status) ?? .pending
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.id, forKey: .id)
        try container.encode(self.amount, forKey: .amount)
        try container.encode(self.unitPrice, forKey: .unitPrice)
        try container.encode(self.quantity, forKey: .quantity)
        try container.encode(self.createdAt, forKey: .createdAt)
        try container.encodeIfPresent(self.processingTime, forKey: .processingTime)
        try container.encode(self.status, forKey: .status)
    }
}

/// A customer payment
public struct PaymentInput: Codable, Equatable, Sendable {
    public var amount: Double
    public var unitPrice: DecimalValue
    public var quantity: BigIntValue
    public var createdAt: Date
    public var processingTime: IsoDuration?
    public var status: PaymentStatus

    public init(amount: Double, unitPrice: DecimalValue, quantity: BigIntValue, createdAt: Date, processingTime: IsoDuration? = nil, status: PaymentStatus = .pending) {
        self.amount = amount
        self.unitPrice = unitPrice
        self.quantity = quantity
        self.createdAt = createdAt
        self.processingTime = processingTime
        self.status = status
    }

    private enum CodingKeys: String, CodingKey {
        case amount = "amount"
        case unitPrice = "unitPrice"
        case quantity = "quantity"
        case createdAt = "createdAt"
        case processingTime = "processingTime"
        case status = "status"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.amount = try container.decode(Double.self, forKey: .amount)
        self.unitPrice = try container.decode(DecimalValue.self, forKey: .unitPrice)
        self.quantity = try container.decode(BigIntValue.self, forKey: .quantity)
        self.createdAt = try container.decode(Date.self, forKey: .createdAt)
        self.processingTime = try container.decodeIfPresent(IsoDuration.self, forKey: .processingTime)
        self.status = try container.decodeIfPresent(PaymentStatus.self, forKey: .status) ?? .pending
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.amount, forKey: .amount)
        try container.encode(self.unitPrice, forKey: .unitPrice)
        try container.encode(self.quantity, forKey: .quantity)
        try container.encode(self.createdAt, forKey: .createdAt)
        try container.encodeIfPresent(self.processingTime, forKey: .processingTime)
        try container.encode(self.status, forKey: .status)
    }
}

/// A stored credential — has a writeonly child, so its Base schema is read
public struct Credential: Codable, Equatable, Sendable {
    public var id: UUID

    public init(id: UUID) {
        self.id = id
    }

    private enum CodingKeys: String, CodingKey {
        case id = "id"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(UUID.self, forKey: .id)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.id, forKey: .id)
    }
}

/// A stored credential — has a writeonly child, so its Base schema is read
public struct CredentialInput: Codable, Equatable, Sendable {
    public var secret: String

    public init(secret: String) {
        self.secret = secret
    }

    private enum CodingKeys: String, CodingKey {
        case secret = "secret"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.secret = try container.decode(String.self, forKey: .secret)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.secret, forKey: .secret)
    }
}

/// A writeonly model nothing extends — its Base schema has no reader
public struct Session: Codable, Equatable, Sendable {
    public var id: String

    public init(id: String) {
        self.id = id
    }

    private enum CodingKeys: String, CodingKey {
        case id = "id"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(String.self, forKey: .id)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.id, forKey: .id)
    }
}

/// A writeonly model nothing extends — its Base schema has no reader
public struct SessionInput: Codable, Equatable, Sendable {
    public var id: String
    public var refreshToken: String

    public init(id: String, refreshToken: String) {
        self.id = id
        self.refreshToken = refreshToken
    }

    private enum CodingKeys: String, CodingKey {
        case id = "id"
        case refreshToken = "refreshToken"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(String.self, forKey: .id)
        self.refreshToken = try container.decode(String.self, forKey: .refreshToken)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.id, forKey: .id)
        try container.encode(self.refreshToken, forKey: .refreshToken)
    }
}

/// Path params declared as a model, referenced via `params: PaymentRef`
public struct PaymentRef: Codable, Equatable, Sendable {
    public var paymentId: UUID

    public init(paymentId: UUID) {
        self.paymentId = paymentId
    }

    private enum CodingKeys: String, CodingKey {
        case paymentId = "paymentId"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.paymentId = try container.decode(UUID.self, forKey: .paymentId)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.paymentId, forKey: .paymentId)
    }
}

public struct UpdatePaymentForm: Codable, Equatable, Sendable {
    public var note: String?

    public init(note: String? = nil) {
        self.note = note
    }

    private enum CodingKeys: String, CodingKey {
        case note = "note"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.note = try container.decodeIfPresent(String.self, forKey: .note)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.note, forKey: .note)
    }
}

public struct UploadReceiptForm: Codable, Equatable, Sendable {
    public var caption: String?
    public var file: Data?

    public init(caption: String? = nil, file: Data? = nil) {
        self.caption = caption
        self.file = file
    }

    private enum CodingKeys: String, CodingKey {
        case caption = "caption"
        case file = "file"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.caption = try container.decodeIfPresent(String.self, forKey: .caption)
        self.file = try container.decodeIfPresent(Data.self, forKey: .file)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.caption, forKey: .caption)
        try container.encodeIfPresent(self.file, forKey: .file)
    }
}

/// Query params declared as a model, referenced via `query: PaymentFilter`
public struct PaymentFilter: Codable, Equatable, Sendable {
    public var status: PaymentFilterStatus?
    public var since: Date?
    public var ids: [UUID]?

    public init(status: PaymentFilterStatus? = nil, since: Date? = nil, ids: [UUID]? = nil) {
        self.status = status
        self.since = since
        self.ids = ids
    }

    private enum CodingKeys: String, CodingKey {
        case status = "status"
        case since = "since"
        case ids = "ids"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.status = try container.decodeIfPresent(PaymentFilterStatus.self, forKey: .status)
        self.since = try container.decodeIfPresent(Date.self, forKey: .since)
        self.ids = try container.decodeIfPresent([UUID].self, forKey: .ids)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.status, forKey: .status)
        try container.encodeIfPresent(self.since, forKey: .since)
        try container.encodeIfPresent(self.ids, forKey: .ids)
    }
}

/// Request headers declared as a model. Hyphenated, because a server sees header names lowercased.
public struct TenantHeaders: Codable, Equatable, Sendable {
    public var xTenant: String

    public init(xTenant: String) {
        self.xTenant = xTenant
    }

    private enum CodingKeys: String, CodingKey {
        case xTenant = "x-tenant"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.xTenant = try container.decode(String.self, forKey: .xTenant)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.xTenant, forKey: .xTenant)
    }
}

/// Extends a writeonly base and is itself writeonly
public struct AdminCredential: Codable, Equatable, Sendable {
    public var id: UUID
    public var scope: String

    public init(id: UUID, scope: String) {
        self.id = id
        self.scope = scope
    }

    private enum CodingKeys: String, CodingKey {
        case id = "id"
        case scope = "scope"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(UUID.self, forKey: .id)
        self.scope = try container.decode(String.self, forKey: .scope)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.id, forKey: .id)
        try container.encode(self.scope, forKey: .scope)
    }
}

/// Extends a writeonly base and is itself writeonly
public struct AdminCredentialInput: Codable, Equatable, Sendable {
    public var secret: String
    public var scope: String
    public var token: String

    public init(secret: String, scope: String, token: String) {
        self.secret = secret
        self.scope = scope
        self.token = token
    }

    private enum CodingKeys: String, CodingKey {
        case secret = "secret"
        case scope = "scope"
        case token = "token"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.secret = try container.decode(String.self, forKey: .secret)
        self.scope = try container.decode(String.self, forKey: .scope)
        self.token = try container.decode(String.self, forKey: .token)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.secret, forKey: .secret)
        try container.encode(self.scope, forKey: .scope)
        try container.encode(self.token, forKey: .token)
    }
}

public enum PaymentStatus: String, Codable, CaseIterable, Sendable {
    case pending = "pending"
    case completed = "completed"
    case failed = "failed"
}

public enum PaymentFilterStatus: String, Codable, CaseIterable, Sendable {
    case pending = "pending"
    case completed = "completed"
    case failed = "failed"
}
