// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

public struct Invoice: Codable, Equatable, Sendable {
    public var id: UUID
    public var total: DecimalValue

    public init(id: UUID, total: DecimalValue) {
        self.id = id
        self.total = total
    }

    private enum CodingKeys: String, CodingKey {
        case id = "id"
        case total = "total"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(UUID.self, forKey: .id)
        self.total = try container.decode(DecimalValue.self, forKey: .total)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.id, forKey: .id)
        try container.encode(self.total, forKey: .total)
    }
}

public struct InvoiceInput: Codable, Equatable, Sendable {
    public var total: DecimalValue

    public init(total: DecimalValue) {
        self.total = total
    }

    private enum CodingKeys: String, CodingKey {
        case total = "total"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.total = try container.decode(DecimalValue.self, forKey: .total)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.total, forKey: .total)
    }
}
