// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// A named enum, so a field default has to resolve to a member rather than its wire spelling
public enum Rating: String, Codable, CaseIterable, Sendable {
    case good = "good"
    case neutral = "neutral"
    case bad = "bad"
}

public struct Card: Codable, Equatable, Sendable {
    public var kind: String
    public var last4: String

    public init(kind: String = "card", last4: String) {
        self.kind = kind
        self.last4 = last4
    }

    private enum CodingKeys: String, CodingKey {
        case kind = "kind"
        case last4 = "last4"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.kind = try container.decode(String.self, forKey: .kind)
        guard kind == "card" else {
            throw DecodingError.dataCorruptedError(forKey: .kind, in: container, debugDescription: "Expected \"card\"")
        }
        self.last4 = try container.decode(String.self, forKey: .last4)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kind, forKey: .kind)
        try container.encode(last4, forKey: .last4)
    }
}

public struct Bank: Codable, Equatable, Sendable {
    public var kind: String
    public var iban: String

    public init(kind: String = "bank", iban: String) {
        self.kind = kind
        self.iban = iban
    }

    private enum CodingKeys: String, CodingKey {
        case kind = "kind"
        case iban = "iban"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.kind = try container.decode(String.self, forKey: .kind)
        guard kind == "bank" else {
            throw DecodingError.dataCorruptedError(forKey: .kind, in: container, debugDescription: "Expected \"bank\"")
        }
        self.iban = try container.decode(String.self, forKey: .iban)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kind, forKey: .kind)
        try container.encode(iban, forKey: .iban)
    }
}

/// Decodes snake_case keys and encodes PascalCase ones
public struct Token: Codable, Equatable, Sendable {
    public var accessToken: String
    public var expiresIn: Int

    public init(accessToken: String, expiresIn: Int = 3600) {
        self.accessToken = accessToken
        self.expiresIn = expiresIn
    }

    private enum CodingKeys: String, CodingKey {
        case accessToken = "access_token"
        case expiresIn = "expires_in"
    }

    private enum EncodingKeys: String, CodingKey {
        case accessToken = "AccessToken"
        case expiresIn = "ExpiresIn"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.accessToken = try container.decode(String.self, forKey: .accessToken)
        self.expiresIn = try container.decodeIfPresent(Int.self, forKey: .expiresIn) ?? 3600
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: EncodingKeys.self)
        try container.encode(accessToken, forKey: .accessToken)
        try container.encode(expiresIn, forKey: .expiresIn)
    }
}

public struct Owned: Codable, Equatable, Sendable {
    public var id: UUID

    public init(id: UUID) {
        self.id = id
    }

    private enum CodingKeys: String, CodingKey {
        case id = "id"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(UUID.self, forKey: .id)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
    }
}

public struct OwnedInput: Codable, Equatable, Sendable {
    public var secret: String

    public init(secret: String) {
        self.secret = secret
    }

    private enum CodingKeys: String, CodingKey {
        case secret = "secret"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.secret = try container.decode(String.self, forKey: .secret)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(secret, forKey: .secret)
    }
}

public struct Named: Codable, Equatable, Sendable {
    public var name: String

    public init(name: String) {
        self.name = name
    }

    private enum CodingKeys: String, CodingKey {
        case name = "name"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.name = try container.decode(String.self, forKey: .name)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
    }
}

/// Two flattened bases, split into a read and an input shape
public struct Shared: Codable, Equatable, Sendable {
    public var id: UUID
    public var name: String
    public var label: String
    public var instrument: Instrument?

    public init(id: UUID, name: String, label: String = "x", instrument: Instrument? = nil) {
        self.id = id
        self.name = name
        self.label = label
        self.instrument = instrument
    }

    private enum CodingKeys: String, CodingKey {
        case id = "id"
        case name = "name"
        case label = "label"
        case instrument = "instrument"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(UUID.self, forKey: .id)
        self.name = try container.decode(String.self, forKey: .name)
        self.label = try container.decodeIfPresent(String.self, forKey: .label) ?? "x"
        self.instrument = try container.decodeIfPresent(Instrument.self, forKey: .instrument)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(label, forKey: .label)
        try container.encodeIfPresent(instrument, forKey: .instrument)
    }
}

/// Two flattened bases, split into a read and an input shape
public struct SharedInput: Codable, Equatable, Sendable {
    public var secret: String
    public var name: String
    public var label: String
    public var instrument: Instrument?

    public init(secret: String, name: String, label: String = "x", instrument: Instrument? = nil) {
        self.secret = secret
        self.name = name
        self.label = label
        self.instrument = instrument
    }

    private enum CodingKeys: String, CodingKey {
        case secret = "secret"
        case name = "name"
        case label = "label"
        case instrument = "instrument"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.secret = try container.decode(String.self, forKey: .secret)
        self.name = try container.decode(String.self, forKey: .name)
        self.label = try container.decodeIfPresent(String.self, forKey: .label) ?? "x"
        self.instrument = try container.decodeIfPresent(Instrument.self, forKey: .instrument)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(secret, forKey: .secret)
        try container.encode(name, forKey: .name)
        try container.encode(label, forKey: .label)
        try container.encodeIfPresent(instrument, forKey: .instrument)
    }
}

/// Self recursion through lazy(), mutual recursion through Doc, every container, both union
/// forms, every scalar, and field names that are keywords in the target languages
public struct Folder: Codable, Equatable, Sendable {
    public var id: UUID
    public var `class`: String
    public var `default`: String?
    public var rating: Rating
    private var _parent: Indirect<Folder>?
    public var parent: Folder? {
        get { _parent?.value }
        set { _parent = newValue.map { Indirect($0) } }
    }
    private var _readme: Indirect<Doc>?
    public var readme: Doc? {
        get { _readme?.value }
        set { _readme = newValue.map { Indirect($0) } }
    }
    public var children: [Folder]
    public var byName: [String: Folder]?
    public var span: FolderSpan?
    public var stamped: FolderStamped?
    public var label: FolderLabel
    public var pinned: FolderPinned?
    public var instrument: FolderInstrument?
    public var origin: FolderOrigin?
    public var size: BigIntValue
    public var price: DecimalValue
    public var day: LocalDate?
    public var at: LocalTime?
    public var ttl: IsoDuration?
    public var blob: Data?
    public var extra: JSONValue?
    public var raw: JSONValue?

    public init(id: UUID, `class`: String, `default`: String? = nil, rating: Rating = .neutral, parent: Folder? = nil, readme: Doc? = nil, children: [Folder], byName: [String: Folder]? = nil, span: FolderSpan? = nil, stamped: FolderStamped? = nil, label: FolderLabel, pinned: FolderPinned?, instrument: FolderInstrument? = nil, origin: FolderOrigin? = nil, size: BigIntValue, price: DecimalValue, day: LocalDate? = nil, at: LocalTime? = nil, ttl: IsoDuration? = nil, blob: Data? = nil, extra: JSONValue? = nil, raw: JSONValue? = nil) {
        self.id = id
        self.`class` = `class`
        self.`default` = `default`
        self.rating = rating
        self._parent = parent.map { Indirect($0) }
        self._readme = readme.map { Indirect($0) }
        self.children = children
        self.byName = byName
        self.span = span
        self.stamped = stamped
        self.label = label
        self.pinned = pinned
        self.instrument = instrument
        self.origin = origin
        self.size = size
        self.price = price
        self.day = day
        self.at = at
        self.ttl = ttl
        self.blob = blob
        self.extra = extra
        self.raw = raw
    }

    private enum CodingKeys: String, CodingKey {
        case id = "id"
        case `class` = "class"
        case `default` = "default"
        case rating = "rating"
        case _parent = "parent"
        case _readme = "readme"
        case children = "children"
        case byName = "byName"
        case span = "span"
        case stamped = "stamped"
        case label = "label"
        case pinned = "pinned"
        case instrument = "instrument"
        case origin = "origin"
        case size = "size"
        case price = "price"
        case day = "day"
        case at = "at"
        case ttl = "ttl"
        case blob = "blob"
        case extra = "extra"
        case raw = "raw"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(UUID.self, forKey: .id)
        self.`class` = try container.decode(String.self, forKey: .`class`)
        self.`default` = try container.decodeIfPresent(String.self, forKey: .`default`)
        self.rating = try container.decodeIfPresent(Rating.self, forKey: .rating) ?? .neutral
        self._parent = try container.decodeIfPresent(Indirect<Folder>.self, forKey: ._parent)
        self._readme = try container.decodeIfPresent(Indirect<Doc>.self, forKey: ._readme)
        self.children = try container.decode([Folder].self, forKey: .children)
        self.byName = try container.decodeIfPresent([String: Folder].self, forKey: .byName)
        self.span = try container.decodeIfPresent(FolderSpan.self, forKey: .span)
        self.stamped = try container.decodeIfPresent(FolderStamped.self, forKey: .stamped)
        self.label = try container.decode(FolderLabel.self, forKey: .label)
        self.pinned = try container.decode(FolderPinned?.self, forKey: .pinned)
        self.instrument = try container.decodeIfPresent(FolderInstrument.self, forKey: .instrument)
        self.origin = try container.decodeIfPresent(FolderOrigin.self, forKey: .origin)
        self.size = try container.decode(BigIntValue.self, forKey: .size)
        self.price = try container.decode(DecimalValue.self, forKey: .price)
        self.day = try container.decodeIfPresent(LocalDate.self, forKey: .day)
        self.at = try container.decodeIfPresent(LocalTime.self, forKey: .at)
        self.ttl = try container.decodeIfPresent(IsoDuration.self, forKey: .ttl)
        self.blob = try container.decodeIfPresent(Data.self, forKey: .blob)
        self.extra = try container.decodeIfPresent(JSONValue.self, forKey: .extra)
        self.raw = try container.decodeIfPresent(JSONValue.self, forKey: .raw)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(`class`, forKey: .`class`)
        try container.encodeIfPresent(`default`, forKey: .`default`)
        try container.encode(rating, forKey: .rating)
        try container.encodeIfPresent(_parent, forKey: ._parent)
        try container.encodeIfPresent(_readme, forKey: ._readme)
        try container.encode(children, forKey: .children)
        try container.encodeIfPresent(byName, forKey: .byName)
        try container.encodeIfPresent(span, forKey: .span)
        try container.encodeIfPresent(stamped, forKey: .stamped)
        try container.encode(label, forKey: .label)
        try container.encode(pinned, forKey: .pinned)
        try container.encodeIfPresent(instrument, forKey: .instrument)
        try container.encodeIfPresent(origin, forKey: .origin)
        try container.encode(size, forKey: .size)
        try container.encode(price, forKey: .price)
        try container.encodeIfPresent(day, forKey: .day)
        try container.encodeIfPresent(at, forKey: .at)
        try container.encodeIfPresent(ttl, forKey: .ttl)
        try container.encodeIfPresent(blob, forKey: .blob)
        try container.encodeIfPresent(extra, forKey: .extra)
        try container.encodeIfPresent(raw, forKey: .raw)
    }
}

public struct Doc: Codable, Equatable, Sendable {
    public var id: UUID
    private var _folder: Indirect<Folder>?
    public var folder: Folder? {
        get { _folder?.value }
        set { _folder = newValue.map { Indirect($0) } }
    }

    public init(id: UUID, folder: Folder? = nil) {
        self.id = id
        self._folder = folder.map { Indirect($0) }
    }

    private enum CodingKeys: String, CodingKey {
        case id = "id"
        case _folder = "folder"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(UUID.self, forKey: .id)
        self._folder = try container.decodeIfPresent(Indirect<Folder>.self, forKey: ._folder)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(_folder, forKey: ._folder)
    }
}

public struct FolderSpan: Codable, Equatable, Sendable {
    public var _0: Int
    public var _1: Int

    public init(_ _0: Int, _ _1: Int) {
        self._0 = _0
        self._1 = _1
    }

    public init(from decoder: Decoder) throws {
        var container = try decoder.unkeyedContainer()
        if let count = container.count, count != 2 {
            throw DecodingError.dataCorruptedError(in: container, debugDescription: "Expected 2 elements for FolderSpan, got \(count)")
        }
        self._0 = try container.decode(Int.self)
        self._1 = try container.decode(Int.self)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.unkeyedContainer()
        try container.encode(_0)
        try container.encode(_1)
    }
}

public struct FolderStamped: Codable, Equatable, Sendable {
    public var _0: UUID
    public var _1: Date
    public var _2: Bool

    public init(_ _0: UUID, _ _1: Date, _ _2: Bool) {
        self._0 = _0
        self._1 = _1
        self._2 = _2
    }

    public init(from decoder: Decoder) throws {
        var container = try decoder.unkeyedContainer()
        if let count = container.count, count != 3 {
            throw DecodingError.dataCorruptedError(in: container, debugDescription: "Expected 3 elements for FolderStamped, got \(count)")
        }
        self._0 = try container.decode(UUID.self)
        self._1 = try container.decode(Date.self)
        self._2 = try container.decode(Bool.self)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.unkeyedContainer()
        try container.encode(_0)
        try container.encode(_1)
        try container.encode(_2)
    }
}

public indirect enum FolderLabel: Codable, Equatable, Sendable {
    case string(String)
    case int(Int)

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(String.self) {
            self = .string(value)
        } else if let value = try? container.decode(Int.self) {
            self = .int(value)
        } else {
            throw DecodingError.dataCorruptedError(in: container, debugDescription: "No FolderLabel member matched the payload")
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .string(let value):
            try container.encode(value)
        case .int(let value):
            try container.encode(value)
        }
    }
}

public indirect enum FolderPinned: Codable, Equatable, Sendable {
    case doc(Doc)
    case folder(Folder)

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(Doc.self) {
            self = .doc(value)
        } else if let value = try? container.decode(Folder.self) {
            self = .folder(value)
        } else {
            throw DecodingError.dataCorruptedError(in: container, debugDescription: "No FolderPinned member matched the payload")
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .doc(let value):
            try container.encode(value)
        case .folder(let value):
            try container.encode(value)
        }
    }
}

public indirect enum FolderInstrument: Codable, Equatable, Sendable {
    case card(Card)
    case bank(Bank)

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(Card.self) {
            self = .card(value)
        } else if let value = try? container.decode(Bank.self) {
            self = .bank(value)
        } else {
            throw DecodingError.dataCorruptedError(in: container, debugDescription: "No FolderInstrument member matched the payload")
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .card(let value):
            try container.encode(value)
        case .bank(let value):
            try container.encode(value)
        }
    }
}

public struct FolderOrigin: Codable, Equatable, Sendable {
    public var x: Double
    public var y: Double

    public init(x: Double, y: Double) {
        self.x = x
        self.y = y
    }

    private enum CodingKeys: String, CodingKey {
        case x = "x"
        case y = "y"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.x = try container.decode(Double.self, forKey: .x)
        self.y = try container.decode(Double.self, forKey: .y)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(x, forKey: .x)
        try container.encode(y, forKey: .y)
    }
}

public indirect enum Instrument: Codable, Equatable, Sendable {
    case card(Card)
    case bank(Bank)

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: DynamicCodingKey.self)
        let tag = try container.decode(JSONValue.self, forKey: DynamicCodingKey(stringValue: "kind"))
        switch tag {
        case .string("card"):
            self = .card(try Card(from: decoder))
        case .string("bank"):
            self = .bank(try Bank(from: decoder))
        default:
            throw DecodingError.dataCorruptedError(forKey: DynamicCodingKey(stringValue: "kind"), in: container, debugDescription: "Unknown Instrument kind: \(tag)")
        }
    }

    public func encode(to encoder: Encoder) throws {
        switch self {
        case .card(let value):
            try value.encode(to: encoder)
        case .bank(let value):
            try value.encode(to: encoder)
        }
    }
}
