// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// A seat, whose field names are all reserved somewhere
public struct Seat: Codable, Equatable, Sendable {
    public var `class`: String
    public var from: LocalDate?
    public var `in`: String?
    public var `is`: Bool?
    public var object: String?
    public var `default`: String?

    public init(`class`: String, from: LocalDate? = nil, `in`: String? = nil, `is`: Bool? = nil, object: String? = nil, `default`: String? = nil) {
        self.`class` = `class`
        self.from = from
        self.`in` = `in`
        self.`is` = `is`
        self.object = object
        self.`default` = `default`
    }

    private enum CodingKeys: String, CodingKey {
        case `class` = "class"
        case from = "from"
        case `in` = "in"
        case `is` = "is"
        case object = "object"
        case `default` = "default"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.`class` = try container.decode(String.self, forKey: .`class`)
        self.from = try container.decodeIfPresent(LocalDate.self, forKey: .from)
        self.`in` = try container.decodeIfPresent(String.self, forKey: .`in`)
        self.`is` = try container.decodeIfPresent(Bool.self, forKey: .`is`)
        self.object = try container.decodeIfPresent(String.self, forKey: .object)
        self.`default` = try container.decodeIfPresent(String.self, forKey: .`default`)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(`class`, forKey: .`class`)
        try container.encodeIfPresent(from, forKey: .from)
        try container.encodeIfPresent(`in`, forKey: .`in`)
        try container.encodeIfPresent(`is`, forKey: .`is`)
        try container.encodeIfPresent(object, forKey: .object)
        try container.encodeIfPresent(`default`, forKey: .`default`)
    }
}

/// Path params declared as a model whose field is a keyword, referenced via `params: SeatRef`
public struct SeatRef: Codable, Equatable, Sendable {
    public var `class`: String

    public init(`class`: String) {
        self.`class` = `class`
    }

    private enum CodingKeys: String, CodingKey {
        case `class` = "class"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.`class` = try container.decode(String.self, forKey: .`class`)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(`class`, forKey: .`class`)
    }
}
