// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// A seat, whose field names are all reserved somewhere in Python
public struct Seat: Codable, Equatable, Sendable {
    public var `class`: String
    public var from: LocalDate?
    public var date: LocalDate
    public var copy: String?
    public var modelDump: String?
    public var json: String?

    public init(`class`: String, from: LocalDate? = nil, date: LocalDate, copy: String? = nil, modelDump: String? = nil, json: String? = nil) {
        self.`class` = `class`
        self.from = from
        self.date = date
        self.copy = copy
        self.modelDump = modelDump
        self.json = json
    }

    private enum CodingKeys: String, CodingKey {
        case `class` = "class"
        case from = "from"
        case date = "date"
        case copy = "copy"
        case modelDump = "modelDump"
        case json = "json"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.`class` = try container.decode(String.self, forKey: .`class`)
        self.from = try container.decodeIfPresent(LocalDate.self, forKey: .from)
        self.date = try container.decode(LocalDate.self, forKey: .date)
        self.copy = try container.decodeIfPresent(String.self, forKey: .copy)
        self.modelDump = try container.decodeIfPresent(String.self, forKey: .modelDump)
        self.json = try container.decodeIfPresent(String.self, forKey: .json)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(`class`, forKey: .`class`)
        try container.encodeIfPresent(from, forKey: .from)
        try container.encode(date, forKey: .date)
        try container.encodeIfPresent(copy, forKey: .copy)
        try container.encodeIfPresent(modelDump, forKey: .modelDump)
        try container.encodeIfPresent(json, forKey: .json)
    }
}

/// Path params declared as a model whose field is a keyword, referenced via `params: SeatRef`
public struct SeatRef: Codable, Equatable, Sendable {
    public var `class`: String

    public init(`class`: String) {
        self.`class` = `class`
    }

    private enum CodingKeys: String, CodingKey {
        case `class` = "class"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.`class` = try container.decode(String.self, forKey: .`class`)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(`class`, forKey: .`class`)
    }
}
