// Auto-generated by @contractkit/plugin-swift. Do not edit manually.
import Foundation

/// A service heartbeat — deliberately no bigint field and no `area` key
public struct Heartbeat: Codable, Equatable, Sendable {
    public var status: String
    public var checkedAt: Date

    public init(status: String, checkedAt: Date) {
        self.status = status
        self.checkedAt = checkedAt
    }

    private enum CodingKeys: String, CodingKey {
        case status = "status"
        case checkedAt = "checkedAt"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.status = try container.decode(String.self, forKey: .status)
        self.checkedAt = try container.decode(Date.self, forKey: .checkedAt)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.status, forKey: .status)
        try container.encode(self.checkedAt, forKey: .checkedAt)
    }
}
